import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {z} from 'zod';
import {CLAUDE, CLAUDE_FONT} from '../tokens/claude';
import {SAFE} from '../tokens/layout';

const kinds = ['continuation','reorganization','scorecard','signal-flow','independent','functions','scale','recommendation','actions','consumers','defensive','components','responsibilities','shared','dataset','analytical-flow','pipeline','boundaries','outcome'] as const;
export const causalCoutureWeek4Schema = z.object({kind: z.enum(kinds)});
export type CausalCoutureWeek4Props = z.infer<typeof causalCoutureWeek4Schema>;
const serif=CLAUDE_FONT.serif, sans=CLAUDE_FONT.ui, mono=CLAUDE_FONT.mono;
const wash='#FFF5F0', muted='#F4F3EB';
const titles:Record<typeof kinds[number],string>={
  continuation:'From Design to Phase 4 Preparation', reorganization:'One Analytical Foundation', scorecard:'The Existing Business Scorecard',
  'signal-flow':'From Signals to Decisions', independent:'Independently Calculated Signals', functions:'Reusable Analytical Functions',
  scale:'A Consistent 0–100 Structure', recommendation:'A Structured Recommendation Layer', actions:'Planned Action Categories',
  consumers:'One Structure. Multiple Consumers.', defensive:'Defensive Analytical Handling', components:'Phase 4 Component Responsibilities',
  responsibilities:'What Each Component Owns', shared:'The Shared Analytical Layer', dataset:'Existing Data Feeding Phase 4',
  'analytical-flow':'The Intended Analytical Flow', pipeline:'Preserving the Existing Pipeline', boundaries:'The Analytical Boundaries',
  outcome:'Phase 4 Architecture Prepared',
};

const Card:React.FC<{children:React.ReactNode;accent?:boolean;dashed?:boolean;muted?:boolean;small?:boolean;status?:string;align?:'center'|'left'}>=({children,accent,dashed,muted:dim,small,status,align='center'})=><div style={{
  minHeight:small?86:116,padding:small?'14px 16px':'21px 24px',borderRadius:20,
  border:`${dashed?'2px dashed':'2px solid'} ${accent?CLAUDE.SPARK:CLAUDE.BORDER}`,
  background:accent?wash:dim?muted:CLAUDE.CARD,boxShadow:'0 10px 30px rgba(61,57,41,.075)',
  display:'flex',flexDirection:'column',alignItems:align==='left'?'flex-start':'center',justifyContent:'center',gap:8,
  textAlign:align,fontFamily:sans,fontSize:small?19:25,fontWeight:650,lineHeight:1.16,color:CLAUDE.INK,whiteSpace:'pre-line'}}>
  {status&&<div style={{fontFamily:mono,fontSize:13,letterSpacing:1.4,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{status}</div>}{children}</div>;
const Arrow:React.FC<{down?:boolean}>=({down})=><div style={{fontFamily:sans,fontSize:38,lineHeight:1,textAlign:'center',color:CLAUDE.SPARK,transform:down?'rotate(90deg)':undefined}}>→</div>;
const Key:React.FC<{children:React.ReactNode}>=({children})=><div style={{display:'inline-flex',padding:'8px 14px',border:`1px solid ${CLAUDE.SPARK}`,borderRadius:999,background:wash,fontFamily:mono,fontSize:14,letterSpacing:1.2,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{children}</div>;
const Flow:React.FC<{items:string[];accentAt?:number;planned?:boolean}>=({items,accentAt=items.length-1,planned})=><div style={{display:'flex',alignItems:'center',gap:8,width:'100%'}}>{items.map((x,i)=><React.Fragment key={x}><div style={{flex:1,minWidth:0}}><Card small accent={i===accentAt} dashed={planned} status={planned?'Planned':undefined}>{x}</Card></div>{i<items.length-1&&<Arrow/>}</React.Fragment>)}</div>;
const scores=['Demand Pressure','Stock Risk','Engagement Momentum','Conversion Strength'];
const modules=['Core Analytics','Scenario Intelligence','Trend Intelligence','Alert Intelligence','Dashboard Aggregation'];

const Body:React.FC<CausalCoutureWeek4Props>=({kind})=>{switch(kind){
  case'continuation':return <div style={{display:'grid',gap:24}}><Flow items={['Scenario Framework','User Experience','Modular Backend Direction']} accentAt={2}/><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:20,alignItems:'center'}}><Card muted>Prepared for Implementation</Card><Arrow/><Card accent dashed status="Next preparation stage">Phase 4 Analytical & Backend Architecture</Card></div></div>;
  case'reorganization':return <div style={{display:'grid',gap:24}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:15}}>{['Dashboard Calculation','Scenario Calculation','Alert Calculation','Frontend Calculation'].map(x=><Card key={x} muted small status="Duplication risk">{x}</Card>)}</div><Arrow down/><div style={{width:'58%',margin:'0 auto'}}><Card accent dashed status="Architectural goal">Shared Analytical Foundation</Card></div></div>;
  case'scorecard':return <div style={{display:'grid',gap:22}}><div style={{textAlign:'center'}}><Key>Existing Phase 3 scorecard</Key></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:18}}>{scores.map(x=><Card key={x}>{x}</Card>)}</div><div style={{fontFamily:serif,fontSize:27,textAlign:'center',color:CLAUDE.INK_SOFT}}>Foundation for the planned Phase 4 intelligence layer</div></div>;
  case'signal-flow':return <div style={{display:'grid',gridTemplateColumns:'1.25fr .1fr .65fr .1fr .8fr',gap:16,alignItems:'center'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:13}}>{scores.map(x=><Card key={x} small>{x}</Card>)}</div><Arrow/><Card accent>Overall Signal</Card><Arrow/><Card dashed status="Recommendation layer">Business Recommendation</Card></div>;
  case'independent':return <div style={{display:'grid',gap:22}}><div style={{textAlign:'center'}}><Key>Planned modular scorecard</Key></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16}}>{scores.map((x,i)=><Card key={x} accent={i===0} dashed status="Independent calculation">{x}</Card>)}</div><div style={{fontFamily:serif,fontSize:28,textAlign:'center'}}>Separate components · reusable signals</div></div>;
  case'functions':return <div style={{display:'grid',gap:23}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:15}}>{scores.map(x=><Card key={x} small accent dashed status="Reusable analytical function">{x}</Card>)}</div><div style={{fontSize:40,color:CLAUDE.SPARK,textAlign:'center'}}>↙　↓　↓　↘</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:15}}>{['Dashboard','Scenario Analysis','Alerts','Frontend'].map(x=><Card key={x} small status="Planned consumer">{x}</Card>)}</div></div>;
  case'scale':return <div style={{display:'grid',gap:19}}><div style={{textAlign:'center'}}><Key>Defined common structure · no score values</Key></div>{scores.map(x=><div key={x} style={{display:'grid',gridTemplateColumns:'.35fr 1.8fr .25fr',gap:15,alignItems:'center',fontFamily:sans,fontWeight:650,fontSize:20}}><span>{x}</span><div style={{height:25,border:`2px solid ${CLAUDE.BORDER}`,borderRadius:99,background:CLAUDE.CARD}}/><div style={{display:'flex',justifyContent:'space-between',fontFamily:mono,color:CLAUDE.SPARK}}><span>0</span><span>100</span></div></div>)}<div style={{fontFamily:serif,fontSize:25,textAlign:'center',color:CLAUDE.INK_SOFT}}>Consistent comparison and presentation · no formulas or thresholds</div></div>;
  case'recommendation':return <div style={{display:'grid',gridTemplateColumns:'.75fr .12fr 1.4fr',gap:22,alignItems:'center'}}><Card muted>Plain-Text Recommendation</Card><Arrow/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:15}}>{['Action','Priority','Confidence','Reason'].map((x,i)=><Card key={x} accent={i===0} dashed status="Defined field">{x}</Card>)}</div></div>;
  case'actions':return <div style={{display:'grid',gap:25}}><div style={{textAlign:'center'}}><Key>Possible structured outputs · not observed results</Key></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:18}}>{['REORDER','MONITOR','HOLD','DEPRIORITIZE'].map(x=><Card key={x} dashed status="Planned action category"><span style={{fontFamily:mono,fontSize:25}}>{x}</span></Card>)}</div><div style={{fontFamily:serif,fontSize:25,textAlign:'center',color:CLAUDE.INK_SOFT}}>No category triggers or thresholds defined here</div></div>;
  case'consumers':return <div style={{display:'grid',gap:22}}><div style={{width:'55%',margin:'0 auto'}}><Card accent status="Shared structure">Action → Priority → Confidence → Reason</Card></div><div style={{fontSize:42,color:CLAUDE.SPARK,textAlign:'center'}}>↙　↓　↓　↘</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16}}>{['Dashboard','Scenario Analysis','Alerts','Frontend'].map(x=><Card key={x} dashed status="Later consumer">{x}</Card>)}</div></div>;
  case'defensive':return <div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr .12fr 1fr',gap:16,alignItems:'center'}}><div style={{display:'grid',gap:13}}><Card small>Small Dataset</Card><Card small muted>Missing Values</Card><Card small muted>Non-Numeric Values</Card></div><Arrow/><Card accent dashed status="Required handling">Defensive Analytical Boundary</Card><Arrow/><Card>Stable Analytical Workflow</Card></div>;
  case'components':return <div style={{display:'grid',gap:22}}><div style={{textAlign:'center'}}><Key>Planned Phase 4 responsibilities</Key></div><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:14}}>{modules.map((x,i)=><Card key={x} small accent={i===0} dashed status="Planned component">{x}</Card>)}</div><div style={{width:'45%',margin:'0 auto'}}><Card accent status="Shared foundation">Core Analytics</Card></div></div>;
  case'responsibilities':return <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:13}}><Card small accent align="left" status="Core Analytics">Baseline scores<br/>Recommendation logic</Card><Card small align="left" status="Scenario Intelligence">Hypothetical changes<br/>Baseline comparison</Card><Card small align="left" status="Trend Intelligence">Recent vs. previous periods</Card><Card small align="left" status="Alert Intelligence">Signal combinations requiring attention</Card><Card small align="left" status="Dashboard Aggregation">Frontend-ready combined response</Card></div>;
  case'shared':return <div style={{display:'grid',gap:23}}><div style={{width:'48%',margin:'0 auto'}}><Card accent status="Shared analytical layer">Core Scorecard Calculations</Card></div><div style={{fontSize:44,color:CLAUDE.SPARK,textAlign:'center'}}>↙　↘</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}><Card>Dashboard</Card><Card dashed status="Planned workflow">Scenario Lab</Card></div><div style={{textAlign:'center'}}><Key>One scorecard foundation · no duplicate versions</Key></div></div>;
  case'dataset':return <div style={{display:'grid',gridTemplateColumns:'1.1fr .12fr .8fr .12fr 1.1fr',gap:17,alignItems:'center'}}><div style={{border:`2px solid ${CLAUDE.BORDER}`,borderRadius:20,padding:18,background:CLAUDE.CARD,display:'grid',gap:8}}><div style={{fontFamily:mono,fontSize:14,color:CLAUDE.SPARK}}>EXISTING DATA FOUNDATION</div><div style={{fontFamily:serif,fontSize:30,fontWeight:700}}>Unified date × SKU Dataset</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:5}}>{Array.from({length:16}).map((_,i)=><div key={i} style={{height:22,background:i%5===0?wash:muted,border:`1px solid ${CLAUDE.BORDER}`}}/>)}</div></div><Arrow/><Card accent>Core Analytics</Card><Arrow/><Card dashed status="Planned Phase 4 consumers">Scenario · Trend · Alert · Dashboard</Card></div>;
  case'analytical-flow':return <div style={{display:'grid',gap:24}}><Flow items={['Unified Dataset','Core Analytics']} accentAt={1}/><Arrow down/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18}}>{['Trend Intelligence','Alert Intelligence','Scenario Analysis'].map(x=><Card key={x} dashed status="Planned intelligence">{x}</Card>)}</div><Arrow down/><Flow items={['Dashboard','Business Decision']} accentAt={1}/></div>;
  case'pipeline':return <div style={{display:'grid',gap:20}}><div style={{fontFamily:mono,fontSize:15,color:CLAUDE.INK_SOFT,textAlign:'center'}}>PLANNED INTELLIGENCE LAYER ADDED ON TOP</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:15}}>{['Core Analytics','Scenario','Trends & Alerts','Dashboard'].map(x=><Card key={x} dashed status="Phase 4 layer">{x}</Card>)}</div><div style={{height:3,background:CLAUDE.SPARK}}/><Flow items={['Ingestion','Preprocessing','Unified Dataset']} accentAt={2}/><div style={{textAlign:'center'}}><Key>Preserved Phase 1–3 data pipeline</Key></div></div>;
  case'boundaries':return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr .08fr 1fr',gap:19,alignItems:'stretch'}}><Card accent align="left" status="Observed signals">Patterns in uploaded data</Card><Card align="left" status="Scenario simulations">User-driven hypothetical changes<br/><span style={{color:CLAUDE.SPARK}}>NOT FORECASTING</span></Card><div style={{display:'flex',justifyContent:'center'}}><div style={{width:3,background:CLAUDE.SPARK}}/></div><Card muted align="left" status="Causal effects">Separate causal-inference methodology required<br/><span style={{color:CLAUDE.SPARK}}>NOT PRODUCED</span></Card></div>;
  case'outcome':return <div style={{display:'grid',gap:23}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:15}}>{['Modular Scorecard Prepared','Recommendation Structure Defined','Component Responsibilities Established','Integration Path Designed'].map((x,i)=><Card key={x} small accent={i===0}>{x}</Card>)}</div><div style={{fontFamily:serif,fontSize:48,fontWeight:700,textAlign:'center'}}>Analytical and Backend Architecture Prepared for Phase 4<span style={{color:CLAUDE.SPARK}}>.</span></div><div style={{display:'flex',justifyContent:'center',gap:28,fontFamily:sans,fontSize:27}}><span>Ushasvi Rachel</span><span style={{color:CLAUDE.SPARK}}>·</span><span>Humanitarians.ai</span></div></div>;
}}

export const CausalCoutureWeek4:React.FC<CausalCoutureWeek4Props>=(props)=>{const frame=useCurrentFrame();const{fps}=useVideoConfig();const entered=spring({frame,fps,config:{damping:24,stiffness:105,mass:.9}});const progress=interpolate(frame,[0,110],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:CLAUDE.PAGE,color:CLAUDE.INK}}><div style={{position:'absolute',left:SAFE.x,top:SAFE.y,fontFamily:sans,fontSize:17,letterSpacing:3,fontWeight:750,color:CLAUDE.INK_SOFT,textTransform:'uppercase'}}>Causal Couture</div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,top:118,height:3,background:CLAUDE.BORDER}}><div style={{height:'100%',width:`${progress*100}%`,background:CLAUDE.SPARK}}/></div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,top:156,fontFamily:serif,fontSize:58,fontWeight:700,lineHeight:1.05}}>{titles[props.kind]}</div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,top:275,bottom:135,display:'flex',alignItems:'center',justifyContent:'center',opacity:entered,transform:`translateY(${(1-entered)*24}px)`}}><div style={{width:'100%'}}><Body {...props}/></div></div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,bottom:62,display:'flex',justifyContent:'space-between',fontFamily:sans,fontSize:20,color:CLAUDE.INK_SOFT}}><span>Ushasvi Rachel</span><span>Humanitarians.ai</span></div></AbsoluteFill>};
