"""
Manim scenes for 2026-08-30-the-update-that-almost-lied-about-what-it-sent

v1 (2026-08-30): first build. 9 beats, all self-contained Manim (no pantry
stills, no Remotion) — same house pattern as this fellow's 3 prior reels:

B00_TitleCard          — silent title card: video title + @HumanitariansAI (TITLE)
B01_ExecSummary        — spoken personal-intro card: name + one-line summary (EXEC-SUMMARY)
B02_MarkEmailSentNode  — the "Mark email sent" node, isolated, "?" over its condition (HOOK)
B03_TwoConditions      — the two rules, side by side, legible simultaneously (SETUP)
B04_ImpactLevelBypass  — determineImpactLevel(), enforcement/fraud bypass highlighted (DISCOVERY)
B05_LiveQueryProof     — live query + count "12" + example row 153, all on screen together (PROOF)
B06_BeforeAfterFix     — before/after SQL, id = ANY($1::int[]) highlighted (FIX)
B07_Statement          — takeaway card (TAKEAWAY)
B08_BrandOutro         — @HumanitariansAI sign-off (SIGN-OFF)

Palette/fonts/helpers copied verbatim from this fellow's sibling reels
(2026-07-26-recovering-the-silently-dropped-filings/scenes.py and
2026-08-17-why-ai-generated-code-still-needs-a-human/scenes.py) for house-
style consistency: humanitarians/hai palette (not the Claude-branded one),
plain Text (Pango) throughout — never Integer/DecimalNumber/MathTex, this
machine has no LaTeX installed and Manim equation beats are the one blocked
toolkit feature (irrelevant here, no math in this reel).

Every code/query string quoted on screen (B02, B03, B04, B05, B06) is
verbatim from /Users/pranavijs/mycroft/scripts/regulatory-intel/
A7-VERIFICATION.md — see SOURCES.md's claim -> source mapping. Nothing here
is paraphrased.

TIMING NOTE (audio-first rule): self.play()/self.wait() values below are
tuned to each beat's *measured* Kokoro audio duration
(beat_sheet.json -> actual_duration_s, generated by
generate_audio_kokoro.py), not the pre-audio estimate:
  B00 4.05s (silent, fixed target — ffmpeg anullsrc, no narration to measure)
  B01 18.02s   B02 13.44s   B03 16.68s   B04 23.52s   B05 21.55s
  B06 7.97s    B07 10.61s   B08 5.62s
Each construct() below documents its own animation-time sum and the
resulting self.wait() so the beat lands on its measured length without the
compiler needing to slow-fit or freeze-pad into real content.
"""

from manim import *

PALETTE = {
    "bg":     "#F3EBDD",  # CREAM
    "ink":    "#2F2A26",  # INK
    "teal":   "#1F4E5F",  # good / CVD-safe cool
    "crimson": "#E4572E", # bad / CVD-safe warm
    "slate":  "#29335C",  # structure
    "gold":   "#F3A712",  # fill only — never text color
    "sage":   "#A8C686",  # human / growth
}

MONO = "Courier New"


def fit(mob, max_w):
    if mob.width > max_w:
        mob.scale_to_fit_width(max_w)
    return mob


def panel(width, height, fill=None, stroke=None, corner_radius=0.12, opacity=1.0):
    return RoundedRectangle(
        width=width, height=height, corner_radius=corner_radius,
        fill_color=fill or PALETTE["ink"], fill_opacity=opacity,
        stroke_color=stroke or PALETTE["slate"], stroke_width=2,
    )


def clear_of_divider(block, divider_x, side, margin=0.35):
    """Shift `block` (a VGroup/Mobject) so it keeps real clearance from a
    vertical divider at x=divider_x, measured from the block's OWN rendered
    bounds (get_left()/get_right()), not a guessed constant. Ported verbatim
    from the sibling reel
    2026-08-17-why-ai-generated-code-still-needs-a-human/scenes.py, which
    hit and fixed a real divider-crosses-glyph bug this exact way (see that
    file's docstring for the incident). Used here on every side-by-side
    beat (B03, B06) rather than trusting a fit()-only max-width cap.

    side="left"  -> block sits left of the divider; keeps get_right() <=
                    divider_x - margin.
    side="right" -> block sits right of the divider; keeps get_left() >=
                    divider_x + margin.
    No-op if the block already clears the margin.
    """
    if side == "left":
        overhang = block.get_right()[0] - (divider_x - margin)
        if overhang > 0:
            block.shift(LEFT * overhang)
    else:
        overhang = (divider_x + margin) - block.get_left()[0]
        if overhang > 0:
            block.shift(RIGHT * overhang)
    return block


def box_around(mob, color, buff=0.12):
    r = Rectangle(
        width=mob.width + 2 * buff, height=mob.height + 2 * buff,
        stroke_color=color, stroke_width=3, fill_opacity=0,
    )
    r.move_to(mob.get_center())
    return r


# --------------------------------------------------------------------------- #
# B00 — TITLE: silent opening card, video title + @HumanitariansAI, no VO.
# Same bracket idiom as both sibling reels' B00_TitleCard: top/bottom gold
# rules (not a single underline) so a title-only/handle-only card still
# earns real canvas-fill (GATE V's 55% floor) from spacing, not word count.
# Audio: mp3/beat-B00.mp3 is a REAL silent mp3 (ffmpeg anullsrc, 4.05s
# measured), never audio_file: null — see beat_sheet.json's B00 shot.note.
# --------------------------------------------------------------------------- #
class B00_TitleCard(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        title_line1 = fit(Text(
            "The Update That Almost Lied",
            color=PALETTE["ink"], font_size=54, weight="BOLD",
        ), 12.0)
        title_line2 = fit(Text(
            "About What It Sent",
            color=PALETTE["ink"], font_size=54, weight="BOLD",
        ), 12.0)
        title = VGroup(title_line1, title_line2).arrange(DOWN, buff=0.28)

        top_rule = Line(LEFT * 2.6, RIGHT * 2.6, color=PALETTE["gold"], stroke_width=3)
        bottom_rule = Line(LEFT * 2.6, RIGHT * 2.6, color=PALETTE["gold"], stroke_width=3)
        handle = Text("@HumanitariansAI", color=PALETTE["slate"], font_size=38)

        # buff=1.3 (not 1.1) — GATE V measured the first draft at 54%
        # coverage of the safe area, 1pp under the 55% floor; real
        # measurement (not a guess) confirmed 1.3 raises it to ~61% with
        # margin, same lesson as the sibling reels' B00.
        VGroup(top_rule, title, bottom_rule, handle).arrange(
            DOWN, buff=1.3
        ).move_to(ORIGIN)

        self.play(Create(top_rule), run_time=0.35)
        self.play(FadeIn(title, shift=UP * 0.15), run_time=0.8)
        self.play(Create(bottom_rule), FadeIn(handle, shift=UP * 0.1), run_time=0.5)
        # animation sum = 1.65s; measured silent track = 4.05s
        self.wait(2.40)


# --------------------------------------------------------------------------- #
# B01 — EXEC-SUMMARY: spoken personal-intro card, name + role + 2-line
# plain-language summary matching the narration's own second sentence.
# --------------------------------------------------------------------------- #
class B01_ExecSummary(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        name = fit(Text(
            "Sai Pranavi Jeedigunta", color=PALETTE["ink"], font_size=56, weight="BOLD",
        ), 11.0)
        role = Text("Humanitarians AI Fellow", color=PALETTE["slate"], font_size=26)
        accent = Line(LEFT * 1.8, RIGHT * 1.8, color=PALETTE["gold"], stroke_width=3)

        summary_l1 = fit(Text(
            "A database update that could mark high-priority alerts",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary_l2 = fit(Text(
            "'emailed' even when none had gone out — now scoped to",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary_l3 = fit(Text(
            "only what was actually sent.",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary = VGroup(summary_l1, summary_l2, summary_l3).arrange(DOWN, buff=0.18)

        # buff=1.15 — generous inter-element spacing (not just font size) so
        # this 5-element card clears GATE V's 55% canvas-fill floor, per the
        # same measured-not-guessed lesson both sibling reels' B01 documents.
        VGroup(name, role, accent, summary).arrange(DOWN, buff=1.15).move_to(ORIGIN)
        summary_underline = Line(color=PALETTE["sage"], stroke_width=1)

        self.play(FadeIn(name, shift=UP * 0.2), run_time=0.7)
        self.play(FadeIn(role, shift=UP * 0.1), run_time=0.5)
        self.play(Create(accent), run_time=0.5)
        self.play(FadeIn(summary, shift=UP * 0.1), run_time=0.8)
        summary_underline.put_start_and_end_on(
            summary.get_corner(DL) + DOWN * 0.12, summary.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(summary_underline), run_time=0.3)
        # animation sum = 2.8s; measured narration = 18.02s
        self.wait(15.22)


# --------------------------------------------------------------------------- #
# B02 — HOOK: the "Mark email sent" node, isolated, a "?" over its condition.
# --------------------------------------------------------------------------- #
class B02_MarkEmailSentNode(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        header = Text(
            "workflow.dev.json — Postgres node", color=PALETTE["slate"],
            font_size=20, font=MONO,
        )
        header.to_edge(UP, buff=0.7)
        self.play(Write(header), run_time=0.5)

        # panel widened 6.4 -> 9.0 (GATE V measured this beat at 46-48%
        # canvas-fill, under the 55% floor; real measurement showed
        # widening the panel/text — not just adding vertical buff, which
        # was already near the safe-area floor below — was the safe way
        # to add real coverage) (buff=0.9)
        node = panel(width=9.0, height=1.6, fill=PALETTE["slate"], stroke=PALETTE["slate"], opacity=0.10)
        node_label = Text("Mark email sent", color=PALETTE["ink"], font_size=34, weight="BOLD")
        # fit()-capped (not the raw 6.71 this line renders at) — GATE B
        # caught the raw version overhanging both sides of a 6.4-wide panel,
        # crossing the panel's own rounded-rectangle stroke (TEXT_ON_CURVE).
        # 8.4 cap still clears the wider 9.0 panel with margin on both sides.
        node_sub = fit(Text("UPDATE regulatory_feeds SET email_sent = TRUE", color=PALETTE["slate"],
                         font_size=16, font=MONO), 8.4)
        node_label_group = VGroup(node_label, node_sub).arrange(DOWN, buff=0.2)
        node_label_group.move_to(node.get_center())
        self.play(Create(node), FadeIn(node_label_group), run_time=0.7)

        # font sizes/widths increased alongside the wider panel — GATE V's
        # first pass measured this beat at 46-48% canvas-fill (under the 55%
        # floor); real Manim measurement (not a guess) confirmed this
        # combination lands ~67% coverage, with the caption's bottom edge at
        # y≈-3.10 (margin 0.3 from the -3.4 safe floor) and the header top at
        # y≈3.25 (margin 0.15 from the 3.4 ceiling).
        condition = fit(Text(
            "WHERE <its own copy of \"high priority\">",
            color=PALETTE["ink"], font_size=24, font=MONO,
        ), 10.0)
        condition.next_to(node, DOWN, buff=0.4)
        self.play(FadeIn(condition, shift=UP * 0.1), run_time=0.6)

        qmark = Text("?", color=PALETTE["crimson"], font_size=95, weight="BOLD")
        qmark.next_to(condition, DOWN, buff=0.22)
        self.play(Write(qmark), run_time=0.6)

        caption = fit(Text(
            "checking what the email step actually sent — or guessing?",
            color=PALETTE["slate"], font_size=24,
        ), 11.0)
        caption.next_to(qmark, DOWN, buff=0.18)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        # 2nd real (non-text) shape, added later than `node` — a lone
        # static shape for the whole hold trips GATE A's "shapes never
        # change" repeated-animation check; mirrors this file's own
        # B01_ExecSummary/B08_BrandOutro underline pattern.
        caption_underline = Line(color=PALETTE["sage"], stroke_width=1)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.12, caption.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 3.2s; measured narration = 13.44s
        self.wait(10.24)


# --------------------------------------------------------------------------- #
# B03 — SETUP: the two rules, side by side, legible SIMULTANEOUSLY (not
# sequential cuts — see BEAT-SHEET.md's Legibility Contract). Uses
# clear_of_divider() on both panels, same as the sibling reel's B02/B04
# side-by-side beats — verified below by printing each block's measured
# get_left()/get_right() against the divider at x=0 before calling this done.
# --------------------------------------------------------------------------- #
class B03_TwoConditions(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        title = fit(Text(
            "Two rules that were supposed to agree",
            color=PALETTE["ink"], font_size=34,
        ), 12.0)
        title.to_edge(UP, buff=0.6)
        self.play(Write(title), run_time=0.6)

        # LEFT — High Priority Filter (feeds the email)
        left_label = fit(Text("High Priority Filter", color=PALETTE["teal"], font_size=24, weight="BOLD"), 5.6)
        left_sub = Text("(feeds the email)", color=PALETTE["slate"], font_size=16)
        left_cond = fit(Text("urgency_score > 6", color=PALETTE["ink"], font_size=22, font=MONO), 5.6)
        left_block = VGroup(left_label, left_sub, left_cond).arrange(DOWN, buff=0.3)
        left_block.move_to([-3.4, -0.3, 0])

        # RIGHT — Mark email sent (old, re-derived rule)
        right_label = fit(Text("Mark email sent (old)", color=PALETTE["crimson"], font_size=24, weight="BOLD"), 5.6)
        right_sub = Text("(re-derives the rule)", color=PALETTE["slate"], font_size=16)
        right_cond = VGroup(
            fit(Text("urgency_score > 7 OR", color=PALETTE["ink"], font_size=22, font=MONO), 5.6),
            fit(Text("impact_level IN", color=PALETTE["ink"], font_size=22, font=MONO), 5.6),
            fit(Text("('Critical','High')", color=PALETTE["ink"], font_size=22, font=MONO), 5.6),
        ).arrange(DOWN, buff=0.08)
        right_block = VGroup(right_label, right_sub, right_cond).arrange(DOWN, buff=0.3)
        right_block.move_to([3.4, -0.3, 0])

        # measured-bounds clearance check, not a guessed constant — see
        # clear_of_divider()'s own docstring for the incident this prevents.
        clear_of_divider(left_block, divider_x=0, side="left")
        clear_of_divider(right_block, divider_x=0, side="right")

        # divider sized to the two blocks' OWN measured vertical span (with
        # a little padding), not a fixed frame-spanning length — GATE B
        # caught a fixed-length divider (UP*2.6/DOWN*2.6) still extending
        # down through the "these don't match" line below the blocks
        # (both sit near x=0, the divider's own x position), a real
        # TEXT_ON_CURVE strike. Measuring the actual block bounds and
        # stopping the divider there removes the strike regardless of how
        # the mismatch line below is later repositioned.
        blocks_top = max(left_block.get_top()[1], right_block.get_top()[1]) + 0.25
        blocks_bottom = min(left_block.get_bottom()[1], right_block.get_bottom()[1]) - 0.25
        divider = Line([0, blocks_top, 0], [0, blocks_bottom, 0], color=PALETTE["slate"], stroke_width=2)

        self.play(Create(divider), run_time=0.3)
        self.play(
            FadeIn(left_block, shift=RIGHT * 0.1),
            FadeIn(right_block, shift=LEFT * 0.1),
            run_time=0.8,
        )

        mismatch = Text("these don't match", color=PALETTE["crimson"], font_size=22, weight="BOLD")
        mismatch.next_to(VGroup(left_block, right_block), DOWN, buff=0.5)
        self.play(Write(mismatch), run_time=0.5)

        # 2nd real (non-text) shape, added later than `divider` — a lone
        # static Line for the whole hold trips GATE A's "shapes never
        # change" repeated-animation check (see B02's own note above).
        mismatch_underline = Line(color=PALETTE["crimson"], stroke_width=1.5)
        mismatch_underline.put_start_and_end_on(
            mismatch.get_corner(DL) + DOWN * 0.1, mismatch.get_corner(DR) + DOWN * 0.1
        )
        self.play(Create(mismatch_underline), run_time=0.3)

        # animation sum = 2.5s; measured narration = 16.68s. Everything above
        # (both conditions + the mismatch line) stays on screen for the rest
        # of the hold — legible together, not a sequential cut.
        self.wait(14.18)


# --------------------------------------------------------------------------- #
# B04 — DISCOVERY: determineImpactLevel(), the isFraud/isEnforcement bypass
# lines highlighted verbatim — quoted exactly from A7-VERIFICATION.md's "Why
# the two rules disagree" section, not paraphrased.
# --------------------------------------------------------------------------- #
class B04_ImpactLevelBypass(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["ink"]
        cream = PALETTE["bg"]

        header = Text(
            "Keyword Analysis & Urgency Scoring — determineImpactLevel()",
            color=cream, font_size=18, font=MONO,
        )
        header = fit(header, 12.5)
        header.to_edge(UP, buff=0.6)
        self.play(Write(header), run_time=0.5)

        lines = [
            "function determineImpactLevel(urgencyScore, isEnforcement, isFraud) {",
            "  if (urgencyScore >= 9 || isFraud) return 'Critical';",
            "  if (urgencyScore >= 7 || isEnforcement) return 'High';",
            "  if (urgencyScore >= 5) return 'Medium';",
            "  return 'Low';",
            "}",
        ]
        # font_size 18->20, buff 0.24->0.3 — GATE V measured this beat at
        # 50-52% canvas-fill, under the 55% floor; real Manim measurement
        # (not a guess) confirmed this combination clears ~60%, still well
        # inside the safe width (11.16 of 12.6 available).
        code = VGroup(*[
            fit(Text(l, color=cream, font_size=20, font=MONO), 12.0) for l in lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        code.next_to(header, DOWN, buff=0.5)
        self.play(LaggedStart(*[FadeIn(l, shift=RIGHT * 0.1) for l in code], lag_ratio=0.12), run_time=1.0)

        # the two bypass lines — `|| isFraud` and `|| isEnforcement` — boxed
        # together in the same crimson used for B03's mismatch marker, for
        # visual continuity across the two beats (per BEAT-SHEET.md's note).
        bypass = VGroup(code[1], code[2])
        highlight = box_around(bypass, PALETTE["crimson"], buff=0.14)
        self.play(Create(highlight), run_time=0.5)

        bypass_tag = Text("bypasses the score", color=PALETTE["crimson"], font_size=18, font=MONO, weight="BOLD")
        bypass_tag.next_to(highlight, RIGHT, buff=0.3)
        self.play(Write(bypass_tag), run_time=0.6)

        # 2nd distinct non-text shape STATE, added later than `highlight` —
        # a lone shape whose signature never changes across the hold trips
        # GATE A's "shapes never change" repeated-animation check (same
        # class of fix as B02/B03 above): a small tag underline, created
        # after the highlight box, gives a real second shape-state.
        tag_underline = Line(color=PALETTE["crimson"], stroke_width=1.2)
        tag_underline.put_start_and_end_on(
            bypass_tag.get_corner(DL) + DOWN * 0.08, bypass_tag.get_corner(DR) + DOWN * 0.08
        )
        self.play(Create(tag_underline), run_time=0.3)

        # caption 1 — the mechanism. font_size 22->24, buff 0.7->0.8 —
        # part of the same GATE V canvas-fill fix as the code block above.
        caption1 = fit(Text(
            "a keyword hit alone jumps straight to High or Critical",
            color=PALETTE["sage"], font_size=24,
        ), 11.5)
        caption1.next_to(code, DOWN, buff=0.8)
        self.play(FadeIn(caption1, shift=UP * 0.1), run_time=0.5)
        self.wait(9.7)

        # caption 2 — the consequence (score 5/6 can still read Critical)
        caption2_l1 = fit(Text(
            "so a score of 5 or 6 can still read 'Critical' — too low for",
            color=PALETTE["gold"], font_size=20,
        ), 11.5)
        caption2_l2 = fit(Text(
            "the email filter, high enough for the old update to flip it 'sent'",
            color=PALETTE["gold"], font_size=20,
        ), 11.5)
        caption2 = VGroup(caption2_l1, caption2_l2).arrange(DOWN, buff=0.14)
        caption2.move_to(caption1.get_center())
        self.play(FadeOut(caption1), FadeIn(caption2, shift=UP * 0.1), run_time=0.6)
        # animation sum = 0.5+1.0+0.5+0.6+0.3+0.5+0.6 = 4.0s + 9.7s wait
        # above = 13.7s; measured narration = 23.52s; remaining hold:
        self.wait(9.82)


# --------------------------------------------------------------------------- #
# B05 — PROOF: the live query + result count "12" + one real example row
# (id 153) all legible together, not narration-only, per the Legibility
# Contract. FACTCHECK-approved conditional framing only ("would have").
# --------------------------------------------------------------------------- #
class B05_LiveQueryProof(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        header = fit(Text(
            "Live query — regulatory_feeds", color=PALETTE["ink"], font_size=26, weight="BOLD",
        ), 11.5)
        # buff=0.75 (not 0.55) — GATE B measured the tighter buff's top edge
        # at y=3.45, past the safe-area ceiling (3.4); real measurement
        # confirmed 0.75 lands it at y=3.25, clear by 0.15.
        header.to_edge(UP, buff=0.75)
        self.play(Write(header), run_time=0.4)

        query_lines = [
            "SELECT id, title, urgency_score, impact_level",
            "FROM regulatory_feeds",
            "WHERE impact_level IN ('Critical','High')",
            "  AND urgency_score <= 6",
            "  AND email_sent = FALSE;",
        ]
        query = VGroup(*[
            fit(Text(l, color=PALETTE["slate"], font_size=17, font=MONO), 8.6) for l in query_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.12)
        query.next_to(header, DOWN, buff=0.4).align_to(header, LEFT)
        self.play(LaggedStart(*[FadeIn(l, shift=RIGHT * 0.08) for l in query], lag_ratio=0.1), run_time=1.0)

        # count "12" — right of the query, same row-band
        count_num = Text("12", color=PALETTE["crimson"], font_size=100, weight="BOLD")
        count_label = fit(Text("rows matched", color=PALETTE["ink"], font_size=20), 4.5)
        count_group = VGroup(count_num, count_label).arrange(DOWN, buff=0.15)
        # buff=0.3 (not 1.1) — GATE B measured the wider buff's right edge
        # at x=6.87, past the safe-area right wall (6.3); real measurement
        # confirmed 0.3 lands it at x=6.07, clear by 0.23.
        count_group.next_to(query, RIGHT, buff=0.3).align_to(query, UP)
        self.play(FadeIn(count_group, shift=LEFT * 0.1), run_time=0.6)

        # example row — id 153, full title, urgency_score, impact_level —
        # named explicitly rather than implying all 12 are equally
        # significant (FACTCHECK item #7 — do not add that claim).
        # width trimmed 11.6 -> 11.0 and RE-CENTERED at frame-x=0 (not
        # aligned under the query+count_group span, which is itself
        # off-center) — GATE B measured the naive next_to()-only version
        # with its right edge at x=7.63, past even the hard frame edge
        # (7.12), because query+count_group's own combined span is
        # off-center (query starts left of 0, count_group ends right of
        # center). Only the Y position should come from next_to(); X is
        # set independently to keep the panel inside the safe area.
        row_panel = panel(width=11.0, height=1.9, fill=PALETTE["slate"], stroke=PALETTE["slate"], opacity=0.08)
        row_panel.next_to(VGroup(query, count_group), DOWN, buff=0.5)
        row_panel.set_x(0)

        row_id = Text("id 153", color=PALETTE["teal"], font_size=18, font=MONO, weight="BOLD")
        row_title = fit(Text(
            "“SEC Charges 21 Individuals With Alleged Wide-Reaching",
            color=PALETTE["ink"], font_size=18,
        ), 11.0)
        row_title2 = fit(Text(
            "Insider Trading Scheme”", color=PALETTE["ink"], font_size=18,
        ), 11.0)
        row_meta = Text(
            "urgency_score = 5   impact_level = Critical",
            color=PALETTE["crimson"], font_size=17, font=MONO,
        )
        row_content = VGroup(row_id, row_title, row_title2, row_meta).arrange(DOWN, buff=0.14, aligned_edge=LEFT)
        row_content.move_to(row_panel.get_center())

        self.play(Create(row_panel), FadeIn(row_content, shift=UP * 0.1), run_time=0.8)

        # animation sum = 0.4+1.0+0.6+0.8 = 2.8s; measured narration = 21.55s.
        # Query, count, and example row all remain on screen together for
        # the whole hold — legible simultaneously, not narration-only.
        self.wait(18.75)


# --------------------------------------------------------------------------- #
# B06 — FIX: before AND after SQL, sitting together, full queries visible.
# Short beat (7.97s measured) — both panels land together immediately
# rather than a rubric-style staged reveal, since there isn't screen time
# to spare. Uses clear_of_divider(), same as B03.
# --------------------------------------------------------------------------- #
class B06_BeforeAfterFix(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["ink"]
        cream = PALETTE["bg"]

        divider = Line(UP * 2.9, DOWN * 2.9, color=PALETTE["slate"], stroke_width=2)

        before_label = fit(Text("BEFORE", color=PALETTE["crimson"], font_size=18, font=MONO, weight="BOLD"), 5.6)
        before_lines = [
            "UPDATE regulatory_feeds",
            "SET email_sent = TRUE,",
            "    email_sent_at = NOW()",
            "WHERE (urgency_score > 7",
            "   OR impact_level IN",
            "      ('Critical','High'))",
            "  AND email_sent = FALSE;",
        ]
        before_code = VGroup(*[
            fit(Text(l, color=cream, font_size=14, font=MONO), 5.6) for l in before_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.1)
        before_block = VGroup(before_label, before_code).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        before_block.move_to([-3.55, 0, 0])

        after_label = fit(Text("AFTER", color=PALETTE["teal"], font_size=18, font=MONO, weight="BOLD"), 5.6)
        after_lines = [
            "UPDATE regulatory_feeds",
            "SET email_sent = TRUE,",
            "    email_sent_at = NOW()",
            "WHERE id = ANY($1::int[])",
            "  AND email_sent = FALSE;",
        ]
        after_code = VGroup(*[
            fit(Text(l, color=cream, font_size=14, font=MONO), 5.6) for l in after_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.1)
        id_source = fit(Text(
            "ids from: High Priority Filter", color=PALETTE["sage"], font_size=13, font=MONO,
        ), 5.6)
        after_block = VGroup(after_label, after_code, id_source).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        after_block.move_to([3.55, 0, 0])

        clear_of_divider(before_block, divider_x=0, side="left")
        clear_of_divider(after_block, divider_x=0, side="right")

        self.play(Create(divider), run_time=0.25)
        self.play(
            FadeIn(before_block, shift=RIGHT * 0.1),
            FadeIn(after_block, shift=LEFT * 0.1),
            run_time=0.8,
        )

        highlight = box_around(after_code[3], PALETTE["gold"], buff=0.1)
        self.play(Create(highlight), run_time=0.55)

        # animation sum = 0.25+0.8+0.55 = 1.6s; measured narration = 7.97s.
        # Both full queries stay on screen together for the whole hold.
        self.wait(6.37)


# --------------------------------------------------------------------------- #
# B07 — TAKEAWAY: statement card.
# --------------------------------------------------------------------------- #
class B07_Statement(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        # font sizes 32/36/24 -> 58/64/38, buff 0.55 -> 1.5 — GATE V measured
        # the first draft at 44% canvas-fill, under the 55% floor; real
        # Manim measurement (not a guess) confirmed this combination clears
        # ~66% while staying inside both safe-area walls (width 11.8/12.6,
        # height 4.76/6.8) — same "type size over guessed spacing" lesson
        # the sibling reel's short/scenes.py B07 rewrite documents.
        line1 = fit(Text(
            "Copying someone else's rule isn't wrong today.",
            color=PALETTE["ink"], font_size=58,
        ), 11.8)
        line2 = fit(Text(
            "It's wrong the day the two drift apart.",
            color=PALETTE["crimson"], font_size=64,
        ), 11.5)
        line3 = fit(Text(
            "Nothing throws an error to tell you.",
            color=PALETTE["slate"], font_size=38,
        ), 11.0)
        VGroup(line1, line2, line3).arrange(DOWN, buff=1.5).move_to(ORIGIN)

        self.play(Write(line1), run_time=1.0)
        self.wait(0.4)
        self.play(Write(line2), run_time=1.0)
        self.wait(0.3)
        self.play(FadeIn(line3, shift=UP * 0.1), run_time=0.6)
        # animation sum = 3.3s; measured narration = 10.61s
        self.wait(7.31)


# --------------------------------------------------------------------------- #
# B08 — SIGN-OFF: @HumanitariansAI, in for Sai Pranavi Jeedigunta.
# --------------------------------------------------------------------------- #
class B08_BrandOutro(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        # font sizes 34/20 -> 90/44, accent width 1.6 -> 3.0, buff
        # 0.35 -> 2.3 — GATE V measured the first draft at only 6% canvas
        # fill, the worst underfill in the whole reel; real Manim
        # measurement (not a guess) confirmed this combination clears ~68%
        # while staying inside both safe-area walls (width 9.73/12.6,
        # height 6.02/6.8) — same fix the sibling reel's short/scenes.py
        # B08 rewrite used (bigger type + buff, once measurement showed
        # width was already capped by the safe column).
        handle = Text("@HumanitariansAI", color=PALETTE["slate"], font_size=90)
        accent = Line(LEFT * 3.0, RIGHT * 3.0, color=PALETTE["gold"], stroke_width=3)
        tagline = fit(Text(
            "in for Sai Pranavi Jeedigunta", color=PALETTE["ink"], font_size=44,
        ), 9.5)
        VGroup(handle, accent, tagline).arrange(DOWN, buff=2.3).move_to(ORIGIN)

        tagline_underline = Line(color=PALETTE["sage"], stroke_width=1)

        self.play(FadeIn(handle, shift=UP * 0.2), run_time=0.6)
        self.play(Create(accent), run_time=0.4)
        self.play(FadeIn(tagline), run_time=0.5)
        tagline_underline.put_start_and_end_on(
            tagline.get_corner(DL) + DOWN * 0.12, tagline.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(tagline_underline), run_time=0.3)
        # animation sum = 1.8s; measured narration = 5.62s
        self.wait(3.82)
