# -*- coding: utf-8 -*-
"""Generate GATE F paperwork (SHOTLIST.md + PROMPTS.md) from a reel's beat sheet.

WHY THIS IS GENERATED, NOT TYPED

`bash art final` now runs GATE F (`runtime/scripts/build_safety.py`
`require_paperwork`), which blocks a final compile unless FACTCHECK.md,
SHOTLIST.md and PROMPTS.md all exist and are non-empty. A hand-typed shotlist
would restate the beat sheet and then drift from it the first time a beat is
re-rendered. Deriving it means the paperwork cannot disagree with what actually
shipped.

WHAT PROMPTS.md SAYS FOR THIS SERIES

Nothing to generate. Every beat is a native Remotion recreation — REBUILD LAW,
no screenshot is composited into any frame and there are no pantry slots. The
file records that explicitly, plus the captures used as reference only, because
"empty" and "deliberately empty" are different things and GATE F cannot tell
them apart.

Usage:
    python make_paperwork.py midjourney-part-6
    python make_paperwork.py --all
"""
import io, json, os, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))


def load(reel):
    p = os.path.join(HERE, reel, 'beat_sheet.json')
    return json.load(io.open(p, encoding='utf-8'))


def fmt_props(props, indent=9):
    """Render the props a reviewer needs, skipping boilerplate."""
    skip = {'paper', 'folderLabel', 'modelLabel', 'effortLabel', 'topic',
            'cues', 'kicker'}
    out = []
    for k, v in props.items():
        if k in skip:
            continue
        if isinstance(v, str):
            s = v if len(v) <= 88 else v[:85] + '…'
            out.append('%s="%s"' % (k, s))
        elif isinstance(v, bool):
            out.append('%s=%s' % (k, 'true' if v else 'false'))
        elif isinstance(v, list):
            if v and isinstance(v[0], list):
                out.append('%s=[%d card(s)]' % (k, len(v)))
            else:
                joined = ' · '.join(str(z) for z in v)
                s = joined if len(joined) <= 96 else joined[:93] + '…'
                out.append('%s=[%s]' % (k, s))
        else:
            out.append('%s=%s' % (k, v))
    pad = ' ' * indent
    body = ('\n' + pad).join(out)
    return body or '(defaults)'


def shotlist(reel, sheet):
    md = sheet['metadata']
    tot = sum(b.get('actual_duration_s') or 0 for b in sheet['beats'])
    L = []
    L.append('# SHOTLIST — %s' % reel)
    L.append('# Typed work order per beat. GENERATED from beat_sheet.json by')
    L.append('# make_paperwork.py — do not hand-edit; it will be overwritten.')
    L.append('#')
    L.append('# %s · %d beats · %.1fs (%d:%02d) · audio LOCKED'
             % (md.get('title', reel), len(sheet['beats']), tot,
                tot // 60, tot % 60))
    L.append('# Generated %s' % datetime.date.today().isoformat())
    L.append('')
    L.append('Every beat is `source: own (Remotion)`. There are no pantry')
    L.append('slots, no archive plates and no slates: this series rebuilds all')
    L.append('product UI as native scenes (REBUILD LAW). See PROMPTS.md.')
    L.append('')

    last_act = None
    for b in sheet['beats']:
        act = b.get('act', '')
        if act != last_act:
            L.append('')
            L.append('## %s' % act.upper())
            L.append('')
            last_act = act
        rem = b['shot'].get('remotion', {})
        dur = b.get('actual_duration_s')
        L.append('%s · %s · %s' % (
            b['beat_id'], rem.get('pattern', '?'),
            ('%.2fs' % dur) if dur else 'PENDING AUDIO'))
        L.append('  source: own (Remotion)')
        L.append('  action: render %s → media/%s.mp4'
                 % (rem.get('pattern', '?'), b['beat_id']))
        L.append('  props: %s' % fmt_props(rem.get('props', {})))
        cues = rem.get('props', {}).get('cues')
        if cues:
            L.append('  cues (MEASURED from mp3/words.json): %s'
                     % ' · '.join('%s=%.3f' % (k, v)
                                  for k, v in sorted(cues.items())))
        shows = b['shot'].get('show') or []
        if shows:
            L.append('  show: %s'
                     % ' → '.join('%s @%s' % (s['event'], s['at'])
                                  for s in shows))
        rendered = rem.get('rendered', {})
        L.append('  status: %s' % ('RENDERED %s' % rendered.get('at', '')
                                   if rendered.get('at') else 'RENDERABLE'))
        L.append('')
    return '\n'.join(L) + '\n'


def prompts(reel, sheet):
    md = sheet['metadata']
    L = []
    L.append('# PROMPTS — %s' % reel)
    L.append('# GENERATED by make_paperwork.py — do not hand-edit.')
    L.append('')
    L.append('## Zero generation prompts, deliberately')
    L.append('')
    L.append('**There are no open pantry slots in this reel, so there is')
    L.append('nothing to generate.** GATE F cannot distinguish "empty because')
    L.append('nobody wrote it" from "empty because there is nothing to write",')
    L.append('so this file states which one it is.')
    L.append('')
    L.append('Every one of the %d beats is `source: own (Remotion)` — a native'
             % len(sheet['beats']))
    L.append('scene compiled from `beat_sheet.json`. No beat sources an image,')
    L.append('a plate, or a stock asset. No beat is a slate.')
    L.append('')
    # The screenshot folder and the spec differ per series. Derived, not
    # hardcoded: an earlier version told the three Suno reels to look at
    # Midjourney's captures.
    tool = 'Midjourney' if 'midjourney' in reel else 'Suno'
    L.append('## REBUILD LAW')
    L.append('')
    L.append('Product UI in this series is **recreated**, never screenshotted.')
    L.append('The captures in `../%s Screenshots/` are reference for' % tool)
    L.append('the author and are read first-hand before a beat is written, but')
    L.append('**no capture is composited into any frame**. Element-by-element')
    L.append('ground truth lives in `../%s-UI-SPEC.md`; every on-screen'
             % tool.upper())
    L.append('claim and its source is in this reel\'s `FACTCHECK.md`.')
    L.append('')
    L.append('Imagery inside recreated windows — feed tiles, moodboard')
    L.append('previews, profile mosaics, the Editor canvas — is **seeded')
    L.append('deterministic abstract art** generated in-scene. It stands in for')
    L.append('a picture without claiming to be one Midjourney produced.')
    L.append('')
    L.append('## Voice')
    L.append('')
    L.append('Kokoro `%s`, local and free. Narration lives in')
    L.append('`beat_sheet.json`; mp3s in `mp3/`. Durations are GROUND TRUTH —')
    L.append('`durationInFrames` follows the audio, never the reverse.')
    L.append('')
    L.append('Phonetic spellings in narration are deliberate for Kokoro G2P')
    L.append('and must not be "corrected": `Rohaan` = Row-Haan.')
        out = '\n'.join(L) + '\n'
    return out.replace("Kokoro `%s`", "Kokoro `%s`" % md.get('voice', 'af_bella'))


def do(reel):
    sheet = load(reel)
    for name, gen in (('SHOTLIST.md', shotlist), ('PROMPTS.md', prompts)):
        p = os.path.join(HERE, reel, name)
        io.open(p, 'w', encoding='utf-8').write(gen(reel, sheet))
        print('  %-14s %6d bytes' % (name, os.path.getsize(p)))


def main():
    args = sys.argv[1:]
    if args == ['--all']:
        reels = sorted(d for d in os.listdir(HERE)
                       if os.path.isfile(os.path.join(HERE, d, 'beat_sheet.json')))
    else:
        reels = args
    if not reels:
        raise SystemExit(__doc__)
    for r in reels:
        print(r)
        do(r)


if __name__ == '__main__':
    main()
