"""
Manim scenes for 2026-09-07-the-synonyms-the-classifier-never-learned

v1 (2026-09-07): first build. 9 beats, all self-contained Manim (no pantry
stills, no Remotion) — same house pattern as this fellow's 3 prior reels in
the "Layer 1 hardening" series. This is part 4 (after
2026-07-26-recovering-the-silently-dropped-filings,
2026-08-30-the-update-that-almost-lied-about-what-it-sent, and
2026-08-30-the-check-that-never-once-fired, the closest sibling — same
genre, same pipeline, same fellow, same voice):

B00_TitleCard           — silent title card: video title + @HumanitariansAI (TITLE)
B01_ExecSummary         — spoken personal-intro card: name + one-line summary (EXEC-SUMMARY)
B02_UnknownSourceHook   — 18-item feed grid, red "UNKNOWN SOURCE" stamp (HOOK)
B03_FieldComparison     — Federal Register dc:creator (populated) vs Google News source (law firm) (SETUP)
B04_TwoGroups           — two real title examples side by side: recoverable vs not (DISCOVERY)
B05_FixAndProofTable    — all 5 live-feed rows, 18->8 total highlighted (FIX-PROOF)
B06_HonestLimit         — the 2 remaining-failure categories, named, framed as a deliberate stop (HONEST-LIMIT)
B07_Statement           — takeaway card (TAKEAWAY)
B08_BrandOutro          — @HumanitariansAI sign-off (SIGN-OFF)

Palette/fonts/helpers copied verbatim from this fellow's sibling reel
2026-08-30-the-check-that-never-once-fired/scenes.py (itself carried from
2026-08-30-the-update-that-almost-lied-about-what-it-sent and
2026-07-26-recovering-the-silently-dropped-filings and
2026-08-17-why-ai-generated-code-still-needs-a-human) for house-style
consistency: humanitarians/hai palette (not the Claude-branded one), plain
Text (Pango) throughout — never Integer/DecimalNumber/MathTex, this machine
has no LaTeX installed and Manim equation beats are the one blocked toolkit
feature (irrelevant here, no math in this reel).

Every quoted string on screen (B03's XML fields, B04's two titles, B05's
5-feed table, B06's two example titles) is verbatim from
/Users/pranavijs/mycroft/scripts/regulatory-intel/UNKNOWN-SOURCE-INVESTIGATION.md
— see SOURCES.md's claim -> source mapping. Nothing paraphrased.

B03 and B04 are this reel's side-by-side beats. Both use clear_of_divider(),
ported verbatim from
2026-08-17-why-ai-generated-code-still-needs-a-human/scenes.py (the sibling
reel that hit and fixed a real divider-crosses-glyph bug), and verified by
measuring real Manim object bounds (get_left()/get_right()) against the
divider at x=0 before calling each beat done.

B06's CRITICAL FRAMING (per FACTCHECK.md row #5): the remaining 8 items are
shown as a deliberate, reasoned stopping point — "LEFT OPEN — BY DESIGN" —
never as an unsolved bug or a promise to fix later. No "coming soon" visual
or narration anywhere in this beat.

TIMING NOTE (audio-first rule): self.play()/self.wait() values below are
tuned to each beat's *measured* Kokoro audio duration
(beat_sheet.json -> actual_duration_s, generated by
generate_audio_kokoro.py), not the pre-audio estimate:
  B00 4.05s (silent, fixed target — ffmpeg anullsrc, no narration to measure)
  B01 15.02s   B02 9.98s   B03 21.67s   B04 25.25s   B05 22.70s
  B06 20.69s   B07 8.02s   B08 4.22s
Each construct() below documents its own animation-time sum and the
resulting self.wait() so the beat lands on its measured length without the
compiler needing to slow-fit or freeze-pad into real content.
"""

from manim import *

PALETTE = {
    "bg":     "#F3EBDD",  # CREAM
    "ink":    "#2F2A26",  # INK
    "teal":   "#1F4E5F",  # good / CVD-safe cool
    "crimson": "#E4572E", # bad / CVD-safe warm
    "slate":  "#29335C",  # structure
    "gold":   "#F3A712",  # fill only — never text color
    "sage":   "#A8C686",  # human / growth
}

MONO = "Courier New"


def fit(mob, max_w):
    if mob.width > max_w:
        mob.scale_to_fit_width(max_w)
    return mob


def panel(width, height, fill=None, stroke=None, corner_radius=0.12, opacity=1.0):
    return RoundedRectangle(
        width=width, height=height, corner_radius=corner_radius,
        fill_color=fill or PALETTE["ink"], fill_opacity=opacity,
        stroke_color=stroke or PALETTE["slate"], stroke_width=2,
    )


def clear_of_divider(block, divider_x, side, margin=0.35):
    """Shift `block` (a VGroup/Mobject) so it keeps real clearance from a
    vertical divider at x=divider_x, measured from the block's OWN rendered
    bounds (get_left()/get_right()), not a guessed constant. Ported verbatim
    from the sibling reel
    2026-08-17-why-ai-generated-code-still-needs-a-human/scenes.py, which
    hit and fixed a real divider-crosses-glyph bug this exact way.

    side="left"  -> block sits left of the divider; keeps get_right() <=
                    divider_x - margin.
    side="right" -> block sits right of the divider; keeps get_left() >=
                    divider_x + margin.
    No-op if the block already clears the margin.
    """
    if side == "left":
        overhang = block.get_right()[0] - (divider_x - margin)
        if overhang > 0:
            block.shift(LEFT * overhang)
    else:
        overhang = (divider_x + margin) - block.get_left()[0]
        if overhang > 0:
            block.shift(RIGHT * overhang)
    return block


def box_around(mob, color, buff=0.12):
    r = Rectangle(
        width=mob.width + 2 * buff, height=mob.height + 2 * buff,
        stroke_color=color, stroke_width=3, fill_opacity=0,
    )
    r.move_to(mob.get_center())
    return r


# --------------------------------------------------------------------------- #
# B00 — TITLE: silent opening card, video title + @HumanitariansAI, no VO.
# Same bracket idiom as the sibling reels' B00_TitleCard. Title is longer
# than the sibling's ("The Synonyms the Classifier Never Learned" — 41
# chars vs. the sibling's 31), so it splits into 3 lines instead of 2 for
# balance rather than one very long / one very short line.
# Audio: mp3/beat-B00.mp3 is a REAL silent mp3 (ffmpeg anullsrc, 4.05s
# measured), never audio_file: null — see beat_sheet.json's B00 shot.note.
# --------------------------------------------------------------------------- #
class B00_TitleCard(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        # font_size 68->84, rule half-width 3.4->4.2, VGroup buff 0.55->1.5 —
        # GATE V measured the first draft at only 36% canvas-fill (well
        # under the 55% floor: a 3-line title with a tight 0.55 buff between
        # rule/title/handle groups left too much empty safe area); real
        # measurement confirmed this larger-font/wider-rule/bigger-buff
        # combination grows both axes together and clears the floor.
        title_line1 = fit(Text(
            "The Synonyms", color=PALETTE["ink"], font_size=84, weight="BOLD",
        ), 12.0)
        title_line2 = fit(Text(
            "the Classifier", color=PALETTE["ink"], font_size=84, weight="BOLD",
        ), 12.0)
        title_line3 = fit(Text(
            "Never Learned", color=PALETTE["ink"], font_size=84, weight="BOLD",
        ), 12.0)
        title = VGroup(title_line1, title_line2, title_line3).arrange(DOWN, buff=0.32)

        top_rule = Line(LEFT * 4.2, RIGHT * 4.2, color=PALETTE["gold"], stroke_width=3)
        bottom_rule = Line(LEFT * 4.2, RIGHT * 4.2, color=PALETTE["gold"], stroke_width=3)
        handle = Text("@HumanitariansAI", color=PALETTE["slate"], font_size=52)

        VGroup(top_rule, title, bottom_rule, handle).arrange(
            DOWN, buff=0.95
        ).move_to(ORIGIN)

        self.play(Create(top_rule), run_time=0.35)
        self.play(FadeIn(title, shift=UP * 0.15), run_time=0.8)
        self.play(Create(bottom_rule), FadeIn(handle, shift=UP * 0.1), run_time=0.5)
        # animation sum = 1.65s; measured silent track = 4.05s
        self.wait(2.40)


# --------------------------------------------------------------------------- #
# B01 — EXEC-SUMMARY: spoken personal-intro card, name + role + 3-line
# plain-language summary matching the narration's own second sentence.
# --------------------------------------------------------------------------- #
class B01_ExecSummary(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        name = fit(Text(
            "Sai Pranavi Jeedigunta", color=PALETTE["ink"], font_size=56, weight="BOLD",
        ), 11.0)
        role = Text("Humanitarians AI Fellow", color=PALETTE["slate"], font_size=26)
        accent = Line(LEFT * 1.8, RIGHT * 1.8, color=PALETTE["gold"], stroke_width=3)

        summary_l1 = fit(Text(
            "Eighteen items were falling into",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary_l2 = fit(Text(
            "'Unknown Source.' An honest partial fix",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary_l3 = fit(Text(
            "recovered ten — eight stay open, on purpose.",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary = VGroup(summary_l1, summary_l2, summary_l3).arrange(DOWN, buff=0.18)

        VGroup(name, role, accent, summary).arrange(DOWN, buff=1.4).move_to(ORIGIN)
        summary_underline = Line(color=PALETTE["sage"], stroke_width=1)

        self.play(FadeIn(name, shift=UP * 0.2), run_time=0.7)
        self.play(FadeIn(role, shift=UP * 0.1), run_time=0.5)
        self.play(Create(accent), run_time=0.5)
        self.play(FadeIn(summary, shift=UP * 0.1), run_time=0.8)
        summary_underline.put_start_and_end_on(
            summary.get_corner(DL) + DOWN * 0.12, summary.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(summary_underline), run_time=0.3)
        # animation sum = 2.8s; measured narration = 15.02s
        self.wait(12.22)


# --------------------------------------------------------------------------- #
# B02 — HOOK: an 18-cell feed grid (each cell a live Google News item that
# fell through), a red "UNKNOWN SOURCE" stamp beside the count. The grid
# stands in for the 18 real titles (individually quoted later, in B04/B06)
# — here the point is scale: eighteen, live, all landing in one bucket.
# --------------------------------------------------------------------------- #
class B02_UnknownSourceHook(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        header = fit(Text(
            "Google News feeds — live scan, today", color=PALETTE["slate"],
            font_size=26, font=MONO,
        ), 12.0)
        header.to_edge(UP, buff=0.6)
        self.play(Write(header), run_time=0.5)

        # 18 cells, 6 cols x 3 rows — a grid, not 18 lines of text (which
        # would be illegible at safe-area width). Each cell is a distinct
        # rendered shape (satisfies GATE A's per-beat shape-distinctness
        # check) rather than one shape drawn 18 times identically.
        cells = VGroup()
        for i in range(18):
            cell = RoundedRectangle(
                width=1.55, height=0.62, corner_radius=0.06,
                fill_color=PALETTE["ink"], fill_opacity=0.07,
                stroke_color=PALETTE["slate"], stroke_width=1.5,
            )
            tag = Text("?", color=PALETTE["crimson"], font_size=22, weight="BOLD")
            tag.move_to(cell.get_center())
            cells.add(VGroup(cell, tag))
        grid = cells.arrange_in_grid(rows=3, cols=6, buff=0.22)
        grid.next_to(header, DOWN, buff=0.55)

        self.play(LaggedStart(*[FadeIn(c, scale=0.9) for c in cells], lag_ratio=0.04), run_time=1.4)

        stamp_text = Text("18 -> UNKNOWN SOURCE", color=PALETTE["crimson"], font_size=40, weight="BOLD")
        stamp_text = fit(stamp_text, 11.5)
        stamp_box = Rectangle(
            width=stamp_text.width + 0.6, height=stamp_text.height + 0.35,
            stroke_color=PALETTE["crimson"], stroke_width=4, fill_opacity=0,
        )
        stamp = VGroup(stamp_box, stamp_text)
        stamp.next_to(grid, DOWN, buff=0.45)
        # NOTE: level, no rotation — an earlier draft's tilted-stamp idea was
        # dropped per the sibling reel's own B02 note: a rotated rectangle's
        # edges cross an axis-aligned text box's centerlines even with
        # generous padding, a real GATE B TEXT_ON_CURVE strike.
        self.play(Write(stamp_text), Create(stamp_box), run_time=0.7)

        caption = fit(Text(
            "last week's fix didn't touch these",
            color=PALETTE["slate"], font_size=22,
        ), 11.0)
        caption.next_to(stamp, DOWN, buff=0.35)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        # animation sum = 0.5+1.4+0.7+0.5 = 3.1s; measured narration = 9.98s
        self.wait(6.88)


# --------------------------------------------------------------------------- #
# B03 — SETUP: side-by-side field comparison. Federal Register's dc:creator
# field (populated, a real issuing agency) vs. Google News's <source> field
# (a law firm name — "Mayer Brown" — irrelevant to regulator classification).
# Quoted verbatim from UNKNOWN-SOURCE-INVESTIGATION.md "Starting point".
# Legible before any live data is shown. Uses clear_of_divider(), verified
# by measured bounds.
# --------------------------------------------------------------------------- #
class B03_FieldComparison(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["ink"]
        cream = PALETTE["bg"]

        header = fit(Text(
            "Two feeds, two different fields", color=cream,
            font_size=30, weight="BOLD",
        ), 12.5)
        header.to_edge(UP, buff=0.6)
        self.play(Write(header), run_time=0.5)

        # LEFT — Federal Register: dc:creator, populated with a real agency.
        left_label = Text("FEDERAL REGISTER", color=PALETTE["teal"], font_size=22, font=MONO, weight="BOLD")
        left_lines = [
            "<dc:creator>",
            "  Commodity Futures",
            "  Trading Commission",
            "</dc:creator>",
        ]
        left_code = VGroup(*[
            fit(Text(l, color=cream, font_size=22, font=MONO), 5.4) for l in left_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.16)
        left_tag = fit(Text("-> real issuing agency", color=PALETTE["teal"], font_size=18, font=MONO, weight="BOLD"), 5.4)
        left_block = VGroup(left_label, left_code, left_tag).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        left_block.move_to([-3.3, -0.1, 0])

        # RIGHT — Google News: <source>, a publisher name, not a regulator.
        right_label = Text("GOOGLE NEWS", color=PALETTE["crimson"], font_size=22, font=MONO, weight="BOLD")
        right_lines = [
            "<source>",
            "  Mayer Brown",
            "</source>",
        ]
        right_code = VGroup(*[
            fit(Text(l, color=cream, font_size=22, font=MONO), 5.4) for l in right_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.16)
        right_tag = fit(Text("-> a law firm, not a regulator", color=PALETTE["crimson"], font_size=18, font=MONO, weight="BOLD"), 5.4)
        right_block = VGroup(right_label, right_code, right_tag).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        right_block.move_to([3.3, -0.1, 0])

        # measured-bounds clearance check, not a guessed constant.
        clear_of_divider(left_block, divider_x=0, side="left")
        clear_of_divider(right_block, divider_x=0, side="right")

        # divider sized to the two blocks' OWN measured vertical span.
        blocks_top = max(left_block.get_top()[1], right_block.get_top()[1]) + 0.3
        blocks_bottom = min(left_block.get_bottom()[1], right_block.get_bottom()[1]) - 0.3
        divider = Line([0, blocks_top, 0], [0, blocks_bottom, 0], color=cream, stroke_width=2)

        self.play(Create(divider), run_time=0.3)
        self.play(
            FadeIn(left_block, shift=RIGHT * 0.1),
            FadeIn(right_block, shift=LEFT * 0.1),
            run_time=0.8,
        )

        caption = fit(Text(
            "one names who issued it; the other names who published about it",
            color=PALETTE["sage"], font_size=22,
        ), 12.0)
        caption.next_to(VGroup(left_block, right_block), DOWN, buff=0.5)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.6)

        caption_underline = Line(color=PALETTE["sage"], stroke_width=1)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.12, caption.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 0.5+0.3+0.8+0.6+0.3 = 2.5s; measured narration =
        # 21.67s. Both fields stay on screen together for the whole hold.
        self.wait(19.17)


# --------------------------------------------------------------------------- #
# B04 — DISCOVERY: two real title examples side by side — a recoverable one
# ("adviser" in the title) and a genuinely-not-recoverable one (a different
# regulator entirely, the UK's FCA). Both quoted verbatim from
# UNKNOWN-SOURCE-INVESTIGATION.md "What was actually failing". This reel's
# second side-by-side beat; uses clear_of_divider(), verified by measured
# bounds.
# --------------------------------------------------------------------------- #
class B04_TwoGroups(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        header = fit(Text(
            "Eighteen titles split into two groups", color=PALETTE["ink"],
            font_size=30, weight="BOLD",
        ), 12.0)
        header.to_edge(UP, buff=0.6)
        self.play(Write(header), run_time=0.5)

        # LEFT — recoverable: the title uses a synonym the classifier
        # didn't check for ("adviser").
        left_label = Text("RECOVERABLE", color=PALETTE["teal"], font_size=22, weight="BOLD")
        left_title_l1 = fit(Text(
            "“What Are Exempt Reporting", color=PALETTE["ink"], font_size=22,
        ), 5.3)
        left_title_l2 = fit(Text(
            "Advisers (ERAs)?”", color=PALETTE["ink"], font_size=22,
        ), 5.3)
        left_tag = fit(Text(
            "-> contains 'adviser'", color=PALETTE["teal"], font_size=17, font=MONO, weight="BOLD",
        ), 5.3)
        left_block = VGroup(left_label, left_title_l1, left_title_l2, left_tag).arrange(
            DOWN, buff=0.24, aligned_edge=LEFT
        )
        left_block.move_to([-3.4, -0.2, 0])

        # RIGHT — not recoverable: a different regulator entirely (UK FCA,
        # not tracked by this pipeline). Quoted verbatim, including the
        # ellipsis, from the source doc's own example.
        right_label = Text("NOT RECOVERABLE", color=PALETTE["crimson"], font_size=22, weight="BOLD")
        right_title = fit(Text(
            "“FCA Decision Notice...”", color=PALETTE["ink"], font_size=22,
        ), 5.3)
        right_tag_l1 = fit(Text(
            "-> UK Financial Conduct Authority", color=PALETTE["crimson"], font_size=17, font=MONO, weight="BOLD",
        ), 5.3)
        right_tag_l2 = fit(Text(
            "a regulator this pipeline doesn't track", color=PALETTE["crimson"], font_size=17, font=MONO, weight="BOLD",
        ), 5.3)
        right_block = VGroup(right_label, right_title, right_tag_l1, right_tag_l2).arrange(
            DOWN, buff=0.24, aligned_edge=LEFT
        )
        right_block.move_to([3.0, -0.2, 0])

        # measured-bounds clearance check, not a guessed constant.
        clear_of_divider(left_block, divider_x=0, side="left")
        clear_of_divider(right_block, divider_x=0, side="right")

        blocks_top = max(left_block.get_top()[1], right_block.get_top()[1]) + 0.3
        blocks_bottom = min(left_block.get_bottom()[1], right_block.get_bottom()[1]) - 0.3
        divider = Line([0, blocks_top, 0], [0, blocks_bottom, 0], color=PALETTE["slate"], stroke_width=2)

        self.play(Create(divider), run_time=0.3)
        self.play(
            FadeIn(left_block, shift=RIGHT * 0.1),
            FadeIn(right_block, shift=LEFT * 0.1),
            run_time=0.8,
        )

        caption = fit(Text(
            "same failure mode. very different reasons.",
            color=PALETTE["slate"], font_size=24,
        ), 11.5)
        caption.next_to(VGroup(left_block, right_block), DOWN, buff=0.55)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        caption_underline = Line(color=PALETTE["crimson"], stroke_width=1.5)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.1, caption.get_corner(DR) + DOWN * 0.1
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 0.5+0.3+0.8+0.5+0.3 = 2.4s; measured narration =
        # 25.25s. Both titles stay on screen together for the whole hold —
        # the contrast between them is the point.
        self.wait(22.85)


# --------------------------------------------------------------------------- #
# B05 — FIX + PROOF: the live test result table, ALL 5 feed rows visible —
# FINRA and Investment Advisor Rules (the 2 feeds that changed) highlighted,
# the 18->8 total highlighted. Quoted verbatim from
# UNKNOWN-SOURCE-INVESTIGATION.md "Live verification (2026-08-30)".
# --------------------------------------------------------------------------- #
class B05_FixAndProofTable(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]
        ink = PALETTE["ink"]

        header = fit(Text(
            "Live test — all 5 real feeds, today", color=ink, font_size=30, weight="BOLD",
        ), 12.0)
        header.to_edge(UP, buff=0.65)
        self.play(Write(header), run_time=0.5)

        feed_x, tested_x, before_x, after_x = -6.1, 1.5, 2.6, 3.7
        col_header_y = 2.55
        row_h = 0.56

        # NOTE: every Text() call below uses a LITERAL font_size (never a
        # variable) — the toolkit's GATE W static checker
        # (wcag_margin_check.py) resolves font_size via ast.literal_eval and
        # cannot evaluate a Python variable reference. Same lesson as the
        # sibling reel's B05.
        feed_label = Text("FEED", color=PALETTE["slate"], font_size=19, font=MONO, weight="BOLD")
        feed_label.move_to([feed_x, col_header_y, 0], aligned_edge=LEFT)
        tested_label = Text("ITEMS", color=PALETTE["slate"], font_size=19, font=MONO, weight="BOLD")
        tested_label.move_to([tested_x, col_header_y, 0], aligned_edge=RIGHT)
        before_label = Text("BEFORE", color=PALETTE["slate"], font_size=19, font=MONO, weight="BOLD")
        before_label.move_to([before_x, col_header_y, 0], aligned_edge=RIGHT)
        after_label = Text("AFTER", color=PALETTE["slate"], font_size=19, font=MONO, weight="BOLD")
        after_label.move_to([after_x, col_header_y, 0], aligned_edge=RIGHT)
        col_labels = VGroup(feed_label, tested_label, before_label, after_label)

        header_rule = Line(
            [feed_x, col_header_y - 0.28, 0], [6.1, col_header_y - 0.28, 0],
            color=PALETTE["slate"], stroke_width=1.5,
        )
        self.play(FadeIn(col_labels), Create(header_rule), run_time=0.55)

        rows_data = [
            ("Federal Register - Securities", "146", "0", "0", PALETTE["ink"]),
            ("CFTC Regulations", "12", "0", "0", PALETTE["ink"]),
            ("SEC Press Releases", "25", "0", "0", PALETTE["ink"]),
            ("FINRA (Google News)", "100", "6", "4", PALETTE["crimson"]),
            ("Investment Advisor (Google News)", "100", "12", "4", PALETTE["crimson"]),
        ]

        row_groups = []
        for i, (feed, tested, before, after, rcolor) in enumerate(rows_data):
            y = col_header_y - row_h * (i + 1)
            feed_t = fit(Text(feed, color=ink, font_size=19, font=MONO), 5.5)
            feed_t.move_to([feed_x, y, 0], aligned_edge=LEFT)
            tested_t = Text(tested, color=ink, font_size=19, font=MONO)
            tested_t.move_to([tested_x, y, 0], aligned_edge=RIGHT)
            before_t = Text(before, color=rcolor, font_size=19, font=MONO, weight="BOLD")
            before_t.move_to([before_x, y, 0], aligned_edge=RIGHT)
            after_t = Text(after, color=rcolor, font_size=19, font=MONO, weight="BOLD")
            after_t.move_to([after_x, y, 0], aligned_edge=RIGHT)
            row_groups.append(VGroup(feed_t, tested_t, before_t, after_t))

        self.play(LaggedStart(*[FadeIn(r, shift=RIGHT * 0.08) for r in row_groups], lag_ratio=0.15), run_time=1.0)

        # highlight the 2 rows that changed (FINRA, Investment Advisor)
        changed_rows = VGroup(row_groups[3], row_groups[4])
        changed_top = changed_rows.get_top()[1] + 0.1
        changed_bottom = changed_rows.get_bottom()[1] - 0.1
        changed_box = Rectangle(
            width=12.5, height=changed_top - changed_bottom,
            stroke_color=PALETTE["crimson"], stroke_width=3, fill_opacity=0,
        )
        changed_box.move_to([0.0, (changed_top + changed_bottom) / 2, 0])
        self.play(Create(changed_box), run_time=0.5)

        # total row, below the table, with 18 -> 8 highlighted.
        total_y = col_header_y - row_h * (len(rows_data) + 1) - 0.15
        total_rule = Line(
            [feed_x, total_y + 0.32, 0], [6.1, total_y + 0.32, 0],
            color=PALETTE["slate"], stroke_width=1.5,
        )
        total_label = Text("TOTAL", color=ink, font_size=20, font=MONO, weight="BOLD")
        total_label.move_to([feed_x, total_y, 0], aligned_edge=LEFT)
        total_tested = Text("383", color=ink, font_size=20, font=MONO, weight="BOLD")
        total_tested.move_to([tested_x, total_y, 0], aligned_edge=RIGHT)
        total_before = Text("18", color=PALETTE["crimson"], font_size=22, font=MONO, weight="BOLD")
        total_before.move_to([before_x, total_y, 0], aligned_edge=RIGHT)
        total_after = Text("8", color=PALETTE["teal"], font_size=22, font=MONO, weight="BOLD")
        total_after.move_to([after_x, total_y, 0], aligned_edge=RIGHT)
        total_row = VGroup(total_label, total_tested, total_before, total_after)
        self.play(Create(total_rule), FadeIn(total_row), run_time=0.5)

        total_box = box_around(VGroup(total_before, total_after), PALETTE["gold"], buff=0.16)
        self.play(Create(total_box), run_time=0.4)

        caption = fit(Text(
            "10 of 18 recovered. zero already-correct items reclassified.",
            color=PALETTE["slate"], font_size=20,
        ), 12.0)
        caption.next_to(total_row, DOWN, buff=0.4)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        # animation sum = 0.5+0.55+1.0+0.5+0.5+0.4+0.5 = 4.45s; measured
        # narration = 22.70s. All 5 rows stay on screen together for the
        # whole hold — not just the 2 feeds that changed.
        self.wait(18.25)


# --------------------------------------------------------------------------- #
# B06 — HONEST LIMIT: the two remaining-failure categories, named, one real
# example title each. CRITICAL FRAMING (FACTCHECK.md row #5): a deliberate,
# reasoned stopping point — never an unsolved bug, never a "coming soon".
# --------------------------------------------------------------------------- #
class B06_HonestLimit(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["ink"]
        cream = PALETTE["bg"]

        # GATE V measured the first draft at only 39% canvas-fill (well
        # under the 55% floor: a narrow single-column stack of short lines
        # left too much empty safe-area width); real measurement confirmed
        # larger fonts + wider example lines + a centered (not purely
        # left-aligned) column clears it with margin.
        header = fit(Text(
            "The remaining eight — two real categories", color=cream,
            font_size=30, weight="BOLD",
        ), 12.5)
        header.to_edge(UP, buff=0.68)
        self.play(Write(header), run_time=0.5)

        # Category 1 — generic pieces, no named regulator at all.
        cat1_label = Text("NO NAMED REGULATOR", color=PALETTE["gold"], font_size=27, font=MONO, weight="BOLD")
        cat1_example = fit(Text(
            "“Financial Regulators: Who They Are", color=cream, font_size=30,
        ), 12.5)
        cat1_example2 = fit(Text(
            "and What They Do”", color=cream, font_size=30,
        ), 12.5)
        cat1_block = VGroup(cat1_label, cat1_example, cat1_example2).arrange(
            DOWN, buff=0.24, aligned_edge=LEFT
        )

        # Category 2 — a different regulator entirely (UK FCA), correctly
        # out of scope for a pipeline that tracks US regulators.
        cat2_label = Text("OUT-OF-SCOPE REGULATOR", color=PALETTE["gold"], font_size=27, font=MONO, weight="BOLD")
        cat2_example = fit(Text(
            "“FCA Decision Notice...”", color=cream, font_size=30,
        ), 12.5)
        cat2_note = fit(Text(
            "UK Financial Conduct Authority — not tracked here", color=PALETTE["sage"], font_size=22, font=MONO,
        ), 12.5)
        cat2_block = VGroup(cat2_label, cat2_example, cat2_note).arrange(
            DOWN, buff=0.24, aligned_edge=LEFT
        )

        categories = VGroup(cat1_block, cat2_block).arrange(DOWN, buff=0.75, aligned_edge=LEFT)
        categories.next_to(header, DOWN, buff=0.45)
        self.play(LaggedStart(
            FadeIn(cat1_block, shift=UP * 0.1),
            FadeIn(cat2_block, shift=UP * 0.1),
            lag_ratio=0.4,
        ), run_time=1.0)

        # The stamp: a deliberate, reasoned stop — NOT a bug, NOT a TODO.
        # No visual or wording anywhere in this beat implies "coming soon"
        # or an active plan to close these — FACTCHECK.md row #5 is explicit
        # that the source material treats this as a closed decision.
        stamp_text = fit(Text(
            "LEFT OPEN -- BY DESIGN", color=PALETTE["crimson"], font_size=42, weight="BOLD",
        ), 11.5)
        stamp_box = Rectangle(
            width=stamp_text.width + 0.5, height=stamp_text.height + 0.3,
            stroke_color=PALETTE["crimson"], stroke_width=4, fill_opacity=0,
        )
        stamp = VGroup(stamp_box, stamp_text)
        stamp.next_to(categories, DOWN, buff=0.4)
        self.play(Write(stamp_text), Create(stamp_box), run_time=0.7)

        caption = fit(Text(
            "not a bug i missed -- a real tradeoff, made on purpose",
            color=cream, font_size=27,
        ), 12.2)
        caption.next_to(stamp, DOWN, buff=0.28)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        # 2nd real (non-text) shape STATE beyond stamp_box — a lone static
        # Rectangle for the whole hold trips GATE A's "shapes never change"
        # repeated-animation check (same class of fix as the sibling
        # reels' B02/B03/B04); this underline, created later than
        # stamp_box, gives a real changing shape signature across the hold.
        caption_underline = Line(color=PALETTE["sage"], stroke_width=1)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.12, caption.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 0.5+1.0+0.7+0.5+0.3 = 3.0s; measured narration =
        # 20.69s. Both categories, their examples, and the "left open by
        # design" framing all stay on screen together for the whole hold.
        self.wait(17.69)


# --------------------------------------------------------------------------- #
# B07 — TAKEAWAY: statement card.
# --------------------------------------------------------------------------- #
class B07_Statement(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        # font_size 50/54/36 buff 0.7 -> 54/56/38 buff 1.4 — GATE V measured
        # the first draft at only 34% canvas-fill (well under the 55%
        # floor: line3's long sentence was scaled down hard by fit()'s
        # width cap, shrinking its height contribution, and the 0.7 buff
        # left the group too short overall); real measurement confirmed
        # this bigger-font/shorter-line3/wider-buff combination (same
        # recipe as the sibling reel's own tuned B07) clears the floor.
        line1 = fit(Text(
            "Not every fix should chase",
            color=PALETTE["ink"], font_size=58,
        ), 11.9)
        line2 = fit(Text(
            "a hundred percent.",
            color=PALETTE["crimson"], font_size=62,
        ), 11.9)
        line3 = fit(Text(
            "Know exactly where to stop — and say so.",
            color=PALETTE["slate"], font_size=40,
        ), 11.5)
        VGroup(line1, line2, line3).arrange(DOWN, buff=2.0).move_to(ORIGIN)

        self.play(Write(line1), run_time=1.0)
        self.wait(0.3)
        self.play(Write(line2), run_time=1.0)
        self.wait(0.3)
        self.play(FadeIn(line3, shift=UP * 0.1), run_time=0.6)
        # animation sum = 3.2s; measured narration = 8.02s
        self.wait(4.82)


# --------------------------------------------------------------------------- #
# B08 — SIGN-OFF: @HumanitariansAI, in for Sai Pranavi Jeedigunta.
# Same simple custom brand-card pattern as this fellow's sibling reels — this
# series does NOT use the toolkit's locked ClaudeTitleOutro (OUTRO-LOCK.md
# scopes to claude-liam/@NikBearBrown reels only; not applicable here).
# --------------------------------------------------------------------------- #
class B08_BrandOutro(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        handle = Text("@HumanitariansAI", color=PALETTE["slate"], font_size=90)
        accent = Line(LEFT * 3.0, RIGHT * 3.0, color=PALETTE["gold"], stroke_width=3)
        tagline = fit(Text(
            "in for Sai Pranavi Jeedigunta", color=PALETTE["ink"], font_size=44,
        ), 9.5)
        VGroup(handle, accent, tagline).arrange(DOWN, buff=2.3).move_to(ORIGIN)

        tagline_underline = Line(color=PALETTE["sage"], stroke_width=1)

        self.play(FadeIn(handle, shift=UP * 0.2), run_time=0.6)
        self.play(Create(accent), run_time=0.4)
        self.play(FadeIn(tagline), run_time=0.5)
        tagline_underline.put_start_and_end_on(
            tagline.get_corner(DL) + DOWN * 0.12, tagline.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(tagline_underline), run_time=0.3)
        # animation sum = 1.8s; measured narration = 4.22s
        self.wait(2.42)
