# -*- coding: utf-8 -*-
"""Authoring script for beat_sheet.json. Deterministic; rerun to regenerate."""
import json
import pathlib

CODE = '''# transform.py - generated by Claude, then reviewed line by line
from decimal import Decimal
import pandas as pd

def transform(df: pd.DataFrame) -> pd.DataFrame:
    # created_at: source ships ISO strings, target wants timestamptz
    df["created_at"] = pd.to_datetime(df["created_at"], utc=True)

    # amount: float -> Decimal. money never rides a float
    df["amount"] = df["amount"].map(lambda v: Decimal(str(v)))

    # customer_id: nullable upstream, NOT NULL downstream.
    # do not drop the row - quarantine it, keep the count honest
    df["_quarantine"] = df["customer_id"].isna()
    return df'''

HANDOFF_PROMPT = ("Here is my pipeline's source schema and my target warehouse schema. "
                  "Map every column, and for each mismatch tell me the failure it causes "
                  "in production and the assertion that would catch it.")

meta = {
    "title": "ETL, Simplified",
    "slug": "ai-data-engineering-etl",
    "topic": "DATA ENGINEERING · ETL WITH AI",
    "register": "Teardown",
    "engine": "kokoro",
    "voice_kokoro": "am_onyx",
    "palette": "claude",
    "style_preset": "claude",
    "style": "ai-explainer",
    "aspect_ratio": "16:9",
    "typography": {"serif": "Tiempos/EB Garamond", "ui": "system sans", "mono": "SF Mono"},
    "audience": "Data engineers and analytics engineers deciding where AI actually helps in ETL work.",
    "persona_override": (
        "Narrator identifies as Mohammed Hussain (own build, not a channel), matching the prior "
        "onprem-rag-chatbot and mycroft-credit-rating builds in this book. The nbb IN-FOR-BEAR LAW "
        "line ('...this is Liam, in for Bear') and the @NikBearBrown channel identity are DROPPED. "
        "The user specified the cold-open line verbatim: 'Hi, I am Hussain and this video is about "
        "[summary of the topic]' - B00 opens on exactly that. folderLabel and the outro handle read "
        "'Mohammed Hussain'. No corner LOGO-LAW mark, because there is no channel."),
    "note": (
        "ai-explainer spine: B00 cold open (ClaudeComposerAsk, ask lands answered) - B01 PROBLEM "
        "(the glue tax) - B02 ASK micro-beat - B03 RESULT (the schema diff) - B04 CODE (the "
        "actual generated transform) - B05 JUDGMENT (helps vs cannot) - B06 RISK (silent failure) "
        "- B07 VERDICT artifact - B08 HANDOFF - B09 title outro. GATE P SHORTENING: the reviewer "
        "signed PASS with a cut - a standalone E/T/L mechanism beat (EtlStages) was dropped to "
        "bring the reel under 2:00, and its one load-bearing line ('extract and load are easy, "
        "the transform in the middle is where the weeks go') was folded into B01. The EtlStages "
        "composition stays registered in Root.tsx as a reusable illustration; it is simply not "
        "consumed by this cut. ILLUSTRATE LAW: the Claude UI appears only at B00/B02/B04/B07/B08/"
        "B09; B01, B03, B05 and B06 are native concept illustrations. DOUBLE-CHECK: no vendor "
        "benchmarks, no "
        "model version numbers, no invented adoption statistics - every claim is a mechanism claim "
        "checkable from the type systems involved (float -> decimal rounding, nullable -> NOT NULL, "
        "ISO string -> timestamptz). The 12-match / 3-flag split in B04 is a WORKED ILLUSTRATIVE "
        "EXAMPLE, captioned as such on screen, not a measurement of a real migration."),
    "aspect_pair": "916/beat_sheet.json is the native-portrait sibling cut (reflowed, never cropped)",
}


def rem(pattern, props):
    return {"type": "GRAPHIC", "source": "remotion", "motion": "fade",
            "remotion": {"pattern": pattern, "props": props}}


def beat(bid, act, note, narration, dur, shot, show=None, visual_intent=None):
    b = {"beat_id": bid, "act": act, "role_note": note, "narration_text": narration}
    if visual_intent:
        b["visual_intent"] = visual_intent
    b["shot"] = dict(shot, show=show) if show else shot
    b["estimated_duration_s"] = dur
    b["audio_file"] = "mp3/beat-%s.mp3" % bid
    return b


beats = [
    beat("B00", "INTRO",
         "COLD OPEN LAW - Claude UI, the ask lands answered. User-specified opening line.",
         "Hi, I am Hussain, and this video is about how AI is changing data engineering — moving "
         "data from one pipeline into another, and why ETL is finally getting simpler. Not because "
         "a model builds your warehouse. Because the boring ninety percent stops being handwritten.",
         14,
         rem("ClaudeComposerAsk", {
             "command": "here are two schemas — source postgres, target warehouse. map every column, flag the mismatches you cannot resolve, and do not guess.",
             "topic": "DATA ENGINEERING · ETL WITH AI",
             "segment": "ETL, Simplified",
             "greeting": "Salaam, Hussain",
             "runningText": "reading both schemas…",
             "output": [
                 "15 source columns · 15 target columns",
                 "12 map cleanly by name and type",
                 "3 flagged: type widening, precision, nullability",
                 "0 resolved — those are judgment calls, not lookups",
             ],
             "folderLabel": "Mohammed Hussain",
             "modelLabel": "Opus 5",
             "effortLabel": "High",
         }),
         show=[
             {"at": "0.00", "event": "cream page; topic eyebrow and the serif segment title 'ETL, Simplified' settle in"},
             {"at": "0.10", "event": "spark + 'Salaam, Hussain' fades up over the composer"},
             {"at": "0.15", "event": "the ask types itself into the composer card, character by character"},
             {"at": "0.55", "event": "the send button arms terracotta the instant typing completes"},
             {"at": "0.62", "event": "running indicator 'reading both schemas...' appears"},
             {"at": "0.70", "event": "four output lines land one at a time - the ask arrives already answered"},
         ]),

    beat("B01", "PROBLEM",
         "stakes - no composer. Carries the E/T/L point folded in from the beat cut at GATE P.",
         "Every pipeline has the same shape: source, destination, and a mountain of glue in "
         "between. Rename this column. Cast that timestamp. Guard the null the vendor swears never "
         "happens. Extract and load are easy — the transform in the middle is where the weeks go.",
         16,
         rem("EtlGlueTax", {
             "sourceLabel": "SOURCE",
             "sourceSub": "postgres · orders",
             "destLabel": "WAREHOUSE",
             "destSub": "snowflake · fct_orders",
             "chores": ["rename the columns", "cast the timestamps", "guard the nulls",
                        "de-duplicate", "retry and backfill", "reconcile the totals"],
             "verdict": "extract and load are easy · the middle is the job",
             "sparkLine": "The glue is the job.",
         }),
         visual_intent=("SOURCE and WAREHOUSE sit at the two ends. Between them glue-code strips stack "
                        "in, one per chore, until the stack dwarfs both endpoints."),
         show=[
             {"at": "0.00", "event": "SOURCE node draws left, WAREHOUSE node draws right, a thin pipe between them"},
             {"at": "0.18", "event": "on 'mountain of glue', the first glue strip drops into the middle of the pipe"},
             {"at": "0.30", "event": "'rename this column' - strip 2 stacks on"},
             {"at": "0.42", "event": "'cast that timestamp' - strip 3"},
             {"at": "0.54", "event": "'handle the null' - strip 4; the stack is now taller than either endpoint"},
             {"at": "0.68", "event": "the remaining strips land; the pile dwarfs both endpoints"},
             {"at": "0.86", "event": "on 'the middle is where the weeks go', a terracotta rule draws under the verdict"},
         ]),

    beat("B02", "ASK",
         "ASK-to-RESULT LAW - the ask micro-beat that precedes the generated result in B03",
         "So here is the ask I actually give Claude. Not “build my pipeline.” Two schemas, and one "
         "instruction: map the columns, flag every mismatch you cannot resolve, and do not guess.",
         11,
         rem("ClaudeComposerAsk", {
             "command": "/schema-diff source=orders.sql target=fct_orders.sql — map every column. for each mismatch, name the production failure it causes. do not guess a resolution.",
             "topic": "ASK → RESULT",
             "segment": "The Ask",
             "greeting": "The ask.",
             "runningText": "diffing 15 columns…",
             "output": ["12 exact matches", "3 flagged for a human"],
             "folderLabel": "Mohammed Hussain",
             "modelLabel": "Opus 5",
             "effortLabel": "High",
             "placeholder": "Type / for skills",
         }),
         show=[
             {"at": "0.05", "event": "'The ask.' sits in the greeting slot above the composer"},
             {"at": "0.12", "event": "the /schema-diff token types in terracotta, then the rest of the instruction in ink"},
             {"at": "0.66", "event": "send arms; 'diffing 15 columns...' appears"},
             {"at": "0.82", "event": "two result lines land - 12 matched, 3 flagged"},
         ]),

    beat("B03", "RESULT",
         "the generated result of B02's ask - REBUILD LAW: a native animated diff, never a screenshot",
         "Twelve columns line up. Three do not. Created-at is a string going into a timestamp. "
         "Amount is a float going into a decimal — a rounding bug waiting for month-end. "
         "Customer-id is nullable on one side, not-null on the other. Claude found all three; it "
         "decided none of them.",
         18,
         rem("EtlSchemaMapping", {
             "sourceTitle": "source · orders",
             "targetTitle": "target · fct_orders",
             "matched": 12,
             "rows": [
                 {"src": "order_id      bigint", "dst": "order_id      bigint", "status": "ok"},
                 {"src": "created_at    text", "dst": "created_at    timestamptz",
                  "status": "flag", "flag": "ISO string → timestamp"},
                 {"src": "amount        float8", "dst": "amount        numeric(12,2)",
                  "status": "flag", "flag": "rounds at month-end"},
                 {"src": "customer_id   int NULL", "dst": "customer_id   int NOT NULL",
                  "status": "flag", "flag": "nulls have nowhere to go"},
                 {"src": "status        text", "dst": "status        text", "status": "ok"},
             ],
             "footnote": "Worked illustrative example — not a measurement of a real migration.",
             "verdict": "3 flagged · 0 resolved",
             "sparkLine": "Found, not decided.",
         }),
         visual_intent=("Two column lists face each other. Matching rows connect with quiet ink lines; "
                        "the three mismatches connect in terracotta and unfurl a flag naming the failure."),
         show=[
             {"at": "0.02", "event": "two schema panels slide in facing each other"},
             {"at": "0.10", "event": "'twelve columns line up' - a 12x tally ticks up and the matched rows link in ink"},
             {"at": "0.26", "event": "'three do not' - the three mismatch rows pulse terracotta"},
             {"at": "0.36", "event": "created_at row: the flag unfurls 'ISO string to timestamp'"},
             {"at": "0.50", "event": "amount row: the flag unfurls 'rounds at month-end'"},
             {"at": "0.64", "event": "customer_id row: the flag unfurls 'nulls have nowhere to go'"},
             {"at": "0.86", "event": "on 'it decided none of them', the counter lands on '3 flagged / 0 resolved'"},
         ]),

    beat("B04", "CODE",
         "ACTUAL-CODE LAW - the real generated transform, trimmed to the lines that teach",
         "And this is what it wrote. One rule per flag. Parse the date. Move money off the float. "
         "Make the null explicit instead of silently dropping the row. Read it like a diff, not "
         "like an answer.",
         14,
         rem("ClaudeCodeBeat", {
             "title": "transform.py",
             "code": CODE,
             "sparkLine": "Read it like a diff.",
         }),
         show=[
             {"at": "0.02", "event": "the code card rises onto the cream page"},
             {"at": "0.10", "event": "lines reveal top-down, one per beat of the sentence"},
             {"at": "0.32", "event": "'parse the date' lands as the to_datetime line appears"},
             {"at": "0.50", "event": "'money off the float' lands as the Decimal line appears"},
             {"at": "0.68", "event": "'make the null explicit' lands as the quarantine lines appear"},
             {"at": "0.88", "event": "the spark line 'Read it like a diff.' settles bottom-left"},
         ]),

    beat("B05", "JUDGMENT",
         "the Teardown split - what it is good at versus what it cannot own",
         "It is genuinely good at mapping schemas, boilerplate, tests, and two a.m. stack "
         "traces. It cannot tell you what the number means, what the business promised, or what "
         "downstream was guaranteed. It writes the pipeline; it does not own it.",
         16,
         rem("EtlWhereAiHelps", {
             "leftTitle": "AI is genuinely good at",
             "left": ["mapping schemas", "writing the boilerplate", "generating the tests",
                      "reading a 2 a.m. stack trace"],
             "rightTitle": "It cannot do for you",
             "right": ["what the number means", "what the business promised",
                       "what downstream was guaranteed"],
             "verdict": "it writes the pipeline · it does not own it",
             "sparkLine": "Glue, not judgment.",
         }),
         visual_intent=("A divider draws down the middle. Left items check in one at a time; right "
                        "items arrive as open rings that never fill."),
         show=[
             {"at": "0.05", "event": "a hairline divider draws down the centre of the frame"},
             {"at": "0.12", "event": "the left heading appears; items check in on their spoken phrase"},
             {"at": "0.18", "event": "'mapping schemas' checks"},
             {"at": "0.26", "event": "'writing the boilerplate' checks"},
             {"at": "0.34", "event": "'generating the tests' checks"},
             {"at": "0.42", "event": "'a 2 a.m. stack trace' checks"},
             {"at": "0.56", "event": "the right heading appears; its items arrive as hollow rings and never fill"},
             {"at": "0.90", "event": "the terracotta verdict rule lands: 'it writes the pipeline / it does not own it'"},
         ]),

    beat("B06", "RISK",
         "the failure mode the speed creates - volume green, values wrong",
         "The pipeline runs clean — green check, row counts "
         "match, nobody gets paged — while a bad cast quietly rounds every amount the wrong way. A "
         "pipeline that runs is not one that is right.",
         15,
         rem("EtlSilentFailure", {
             "pipeLabel": "nightly load · fct_orders",
             "countLabel": "rows loaded",
             "countTarget": 48210,
             "countVerdict": "counts match · no page fired",
             "driftLabel": "sum(amount) vs source",
             "driftVerdict": "quietly drifting · no alarm exists for this",
             "punchline": "runs ≠ right",
             "sparkLine": "Volume is not truth.",
         }),
         visual_intent=("Rows stream through the pipe, the row counter races to its target and locks "
                        "green. Underneath, a second track quietly diverges in terracotta and never alarms."),
         show=[
             {"at": "0.06", "event": "rows begin streaming left to right through the pipe"},
             {"at": "0.20", "event": "'runs clean' - the row counter races up toward its target"},
             {"at": "0.32", "event": "'row counts match' - the counter locks and a check stamps beside it"},
             {"at": "0.48", "event": "'a bad cast' - a second track appears below: value drift, in terracotta"},
             {"at": "0.62", "event": "the drift bar creeps away from the source line; no alarm ever fires"},
             {"at": "0.84", "event": "'not a pipeline that is right' - the punchline stamps across both tracks"},
         ]),

    beat("B07", "SUMMARY",
         "verdict recap as the Claude artifact page",
         "So, the verdict. AI collapses the glue, not the judgment. It flags the mismatches; it "
         "never resolves them. It makes code review the most valuable skill on the team — "
         "writing just got free, reading did not.",
         15,
         rem("ClaudeVerdictArtifact", {
             "artifactTitle": "Verdict · AI in the ETL loop",
             "artifactHeading": "It collapses the glue, not the judgment",
             "artifactLines": [
                 "The boring 90% — mapping, boilerplate, tests, docs — stops being handwritten.",
                 "It flags every mismatch it can see. It never decides what to do about one.",
                 "Row count is not correctness: assert on values, not on volume.",
                 "Writing code got free. Reading it did not — review is the bottleneck now.",
             ],
         }),
         show=[
             {"at": "0.03", "event": "the artifact card springs onto the stage"},
             {"at": "0.12", "event": "the heading sets: 'It collapses the glue, not the judgment'"},
             {"at": "0.30", "event": "line 1 lands on 'collapses the glue'"},
             {"at": "0.50", "event": "line 2 lands on 'it flags the mismatches'"},
             {"at": "0.68", "event": "line 3 lands"},
             {"at": "0.86", "event": "line 4 lands on 'reading did not'"},
         ]),

    beat("B08", "NEXT STEPS",
         "HANDOFF LAW - the suggested prompt is typed, read aloud verbatim, then discussed",
         "Your turn. Paste this into Claude: here is my source schema and my target schema — map "
         "every column, and for each mismatch, tell me the failure it causes in production and the "
         "assertion that would catch it. You are not asking for the mapping — you are asking "
         "for the test.",
         18,
         rem("ClaudeComposerAsk", {
             "command": HANDOFF_PROMPT,
             "topic": "YOUR TURN",
             "segment": "Run It On Your Own Pipeline",
             "greeting": "Your turn.",
             "runningText": "paste this into Claude…",
             "output": ["ask for the assertion, not just the mapping",
                        "run it on a pipeline you already trust"],
             "folderLabel": "Mohammed Hussain",
             "modelLabel": "Opus 5",
             "effortLabel": "High",
         }),
         show=[
             {"at": "0.03", "event": "'Your turn.' replaces the persona greeting - the one viewer-addressed cue"},
             {"at": "0.10", "event": "the prompt types itself in full while the narration reads it aloud verbatim"},
             {"at": "0.62", "event": "send arms; 'paste this into Claude...' appears"},
             {"at": "0.76", "event": "on 'you are asking for the test', the two guidance lines land below"},
         ]),

    beat("B09", "OUTRO",
         "OUTRO LAW - restate the title, poster serif, terracotta period",
         "ETL, simplified. The glue, not the judgment. I'm Hussain — thanks for watching.",
         8,
         rem("ClaudeTitleOutro", {
             "title": "ETL, Simplified.",
             "handle": "Mohammed Hussain",
             "subline": "AI in data engineering — it collapses the glue, never the judgment.",
         }),
         show=[
             {"at": "0.00", "event": "cream page; the title sets poster-large in serif with a terracotta period"},
             {"at": "0.30", "event": "the handle settles beneath it"},
             {"at": "0.55", "event": "the subline fades in last"},
         ]),
]

meta["total_estimated_duration_seconds"] = sum(b["estimated_duration_s"] for b in beats)

# AUDIO IS THE MASTER CLOCK, so a re-run of this authoring script must never
# throw away a measurement. Carry forward `actual_duration_s` (and the compiler's
# build stamp) for every beat whose narration text is BYTE-IDENTICAL to what is
# already on disk. A beat whose words changed loses its measurement on purpose —
# its mp3 has to be regenerated anyway.
out = pathlib.Path("beat_sheet.json")
if out.exists():
    prev = {b["beat_id"]: b for b in json.loads(out.read_text(encoding="utf-8"))["beats"]}
    kept = []
    for b in beats:
        old = prev.get(b["beat_id"])
        if old and old.get("narration_text") == b["narration_text"]:
            for field in ("actual_duration_s", "build"):
                if field in old:
                    b[field] = old[field]
                    if field == "actual_duration_s":
                        kept.append(b["beat_id"])
    if kept:
        print("carried forward measured audio for:", " ".join(kept))

sheet = {"metadata": meta, "beats": beats}
out.write_text(json.dumps(sheet, indent=1, ensure_ascii=False), encoding="utf-8")

words = sum(len(b["narration_text"].split()) for b in beats)
print("beats:", len(beats))
print("estimated total:", meta["total_estimated_duration_seconds"], "s")
print("narration words:", words, "-> ~%.0fs at 200 wpm" % (words / 200 * 60))
for b in beats:
    print("  %s %-11s %3d words" % (b["beat_id"], b["act"], len(b["narration_text"].split())))
