"""scenes.py - Manim scenes for simulating-the-universe.

*The Universe You Can Afford.* - ai-explainer, claude-hai, Ep. 07.

PALETTE (Claude fidelity, per skills/make/ai-explainer/SKILL.md)
  cream  #F2F0E9  ground
  ink    #3D3929  all body text
  soft   #6E6A57  secondary text / citations      (4.7:1 on cream)
  ghost  #B9B4A0  STROKES AND FILLS ONLY - never text (2.0:1, fails WCAG)
  acc    #D97757  terracotta - the ONE accent, as a MARK: rule, ring, fill, chip
  accT   #A44A32  the darkened accent for accented TEXT (4.7:1 on cream)

COLOUR CONTRACT FOR THIS REEL
  Terracotta marks THE CHEAP ANSWER, every single time: the Zeldovich curve,
  the Zeldovich panel, the approximation's error, the arrow that cannot leave
  the training box. Ink marks the expensive truth. The mapping never flips, so
  the viewer learns it once at B05 and reads every later plate for free.

THIS FILE IS ASPECT-AWARE - IT RENDERS BOTH CUTS
  The reel ships in 16:9 (3840x2160) and 9:16 (2160x3840). Manim keeps
  frame_height = 8.0 in both, so the VERTICAL band plan is identical either
  way; only the horizontal extent changes - x +-6.15 landscape, x +-1.80
  portrait. Every scene reads PORTRAIT and either lays its elements side by
  side or stacks them. Portrait is NOT a crop: at 4.5 units wide against 14.22
  with the same height it has LESS usable area, so portrait compositions carry
  fewer elements, larger. That is a deliberate reduction.

LAYOUT BAND PLAN (every scene obeys it - this is what keeps the gates green)
                        landscape      portrait
  title                   +3.02          +3.14
  hairline                +2.66          +2.84
  the figure       +2.40 .. -1.90   +2.62 .. -2.02
  the closing line        -2.50          -2.42   (terracotta rule 0.28 below)
  the citation            -3.20          -2.95
  the wordmark bug        -3.12          -3.28   (right-anchored, LOGO LAW)

PLATES
  Every plate is generated by assets/gen_cosmos.py, which ACTUALLY RUNS both
  calculations this episode is about - a Zeldovich displacement and a
  particle-mesh N-body solve, in 2D at 512^2. So the comparison on screen is a
  measured result. It is also a TOY: right shape, wrong scale. Beats that show
  a plate say so.

GATE NOTES (learned the expensive way on Eps. 03-06)
  - import numpy as np explicitly: GATE A's stub does not re-export it.
  - Never build a Line from a Text's get_left(); under the stub a Text has no
    width and the coordinates land off-frame. Use _underline() / _strike().
  - A strike-through must set _qc_intentional or GATE B calls it text-on-curve.
  - ImageMobject is not a VMobject: group it with Group, never VGroup.
  - Check BOTH aspects. Ep. 06's worst defect was a P() call with its
    landscape/portrait values transposed: harmless at 14.22 units wide, and an
    edge-bleed blocker at 4.5.
  - Pace the scene to the narration (see Paced). compile.py fills a beat by
    SLOWING the clip, and a 3x stretch is visible slow-motion that GATE V,
    which samples still frames, can never see.
"""
from manim import *
import numpy as np
import glob
import os
from pathlib import Path

# ── EB Garamond, registered from the toolkit's bundled fonts ─────────────────
SERIF = None
try:
    import manimpango
    _homes = [os.environ.get("ART_HOME") or "",
              r"E:/NEU/Jobs/Humanitarians_AI/brutalist.art"]
    for _h in _homes:
        if not _h:
            continue
        for _f in glob.glob(os.path.join(_h, "runtime", "fonts", "EB_Garamond",
                                         "static", "*.ttf")):
            manimpango.register_font(_f)
    if "EB Garamond" in manimpango.list_fonts():
        SERIF = "EB Garamond"
except Exception:
    SERIF = None

HERE = Path(__file__).resolve().parent
PLOTS = HERE / "assets" / "plots"

# ── Palette ──────────────────────────────────────────────────────────────────
BG    = ManimColor("#F2F0E9")
INK   = ManimColor("#3D3929")
SOFT  = ManimColor("#6E6A57")
GHOST = ManimColor("#B9B4A0")
ACC   = ManimColor("#D97757")
ACCT  = ManimColor("#A44A32")
CARD  = ManimColor("#FFFFFF")
RULE  = ManimColor("#D9D4C4")

# ── The aspect switch ────────────────────────────────────────────────────────
# Manim CE takes pixel dimensions from `-r W,H` but does NOT recompute
# frame_width, so a portrait render would otherwise keep the 16:9 default of
# 14.22 units and lay every scene out at a third of its intended size. Keep
# frame_height at 8.0 and derive frame_width from the real pixel aspect. This
# is the same fix runtime/manim/animated_graphics.py applies; it is repeated
# here because these scenes deliberately do not import that module.
try:
    _pw, _ph = config.pixel_width, config.pixel_height
    if _pw and _ph and abs(config.frame_width
                           - config.frame_height * _pw / _ph) > 0.01:
        config.frame_width = config.frame_height * (_pw / _ph)
except Exception:
    pass

PORTRAIT = float(config.frame_width) < float(config.frame_height)


def P(landscape, portrait):
    """Pick a value per aspect. Reads as a table at the call site."""
    return portrait if PORTRAIT else landscape


X_MAX = P(6.15, 1.80)
Y_MAX = 3.30
TITLE_Y, HAIR_Y = P(3.02, 3.14), P(2.66, 2.84)
FIG_TOP, FIG_BOT = P(2.40, 2.62), P(-1.90, -2.02)
CLOSE_Y = P(-2.50, -2.42)
CITE_Y, BUG_Y = P(-3.20, -2.95), P(-3.12, -3.28)
TITLE_W = P(11.4, 3.42)
CLOSE_W = P(8.8, 3.44)
CITE_W = P(8.4, 3.44)
FIG_MID = (FIG_TOP + FIG_BOT) / 2


# ── Type helpers ─────────────────────────────────────────────────────────────
def _t(txt, size=26, color=None, weight=None):
    kw = {"font_size": size, "color": color if color is not None else INK}
    if SERIF:
        kw["font"] = SERIF
    if weight:
        kw["weight"] = weight
    return Text(txt, **kw)


def _fit(m, max_w, at=None):
    if m.width > max_w:
        m.scale(max_w / m.width)
    if at is not None:
        m.move_to(at)
    return m


def _chip(txt, size=20, fill=ACC, fg=CARD, max_w=None):
    label = _t(txt, size=size, color=fg)
    if max_w and label.width > max_w - 0.46:
        label.scale((max_w - 0.46) / label.width)
    box = RoundedRectangle(width=label.width + 0.46, height=label.height + 0.30,
                           corner_radius=0.12, color=fill, fill_color=fill,
                           fill_opacity=1.0, stroke_width=0)
    label.move_to(box.get_center())
    return VGroup(box, label)


def _quiet_chip(txt, size=20, max_w=None):
    label = _t(txt, size=size, color=INK)
    if max_w and label.width > max_w - 0.46:
        label.scale((max_w - 0.46) / label.width)
    box = RoundedRectangle(width=label.width + 0.46, height=label.height + 0.28,
                           corner_radius=0.12, color=GHOST, fill_color=CARD,
                           fill_opacity=1.0, stroke_width=1.6)
    label.move_to(box.get_center())
    return VGroup(box, label)


def _card(w, h, at, radius=0.16, stroke=GHOST, sw=1.8):
    return RoundedRectangle(width=w, height=h, corner_radius=radius,
                            color=stroke, stroke_width=sw,
                            fill_color=CARD, fill_opacity=1.0).move_to(at)


def _underline(m, color=ACC, sw=4, buff=0.14, pad=0.10):
    ln = Line(LEFT, RIGHT, color=color, stroke_width=sw)
    ln.set_width(max(float(m.width) + pad * 2, 0.4))
    ln.next_to(m, DOWN, buff=buff)
    return ln


def _strike(m, color=ACC, sw=4, pad=0.16):
    """Struck-through rule. `_qc_intentional` exempts it from GATE B's
    TEXT-ON-CURVE rule, which is what that hook exists for."""
    ln = Line(LEFT, RIGHT, color=color, stroke_width=sw)
    ln.set_width(max(float(m.width) + pad * 2, 0.4))
    ln.move_to(m.get_center())
    ln._qc_intentional = True
    return ln


def chrome(scene, title, cite=None):
    head = _fit(_t(title, size=P(36, 30), weight="BOLD"), TITLE_W, [0, TITLE_Y, 0])
    hair = Line([-(X_MAX - 0.10), HAIR_Y, 0], [X_MAX - 0.10, HAIR_Y, 0],
                color=RULE, stroke_width=2.4)
    bug = _t("@HumanitariansAI", size=P(19, 17), color=SOFT)
    bug.move_to([0, BUG_Y, 0]).align_to([X_MAX, 0, 0], RIGHT)
    scene.play(FadeIn(head, shift=DOWN * 0.12), Create(hair), FadeIn(bug),
               run_time=0.8)
    group = VGroup(head, hair, bug)
    if cite:
        c = _fit(_t(cite, size=P(17, 14), color=SOFT), CITE_W)
        if PORTRAIT:
            c.move_to([0, CITE_Y, 0])
        else:
            c.move_to([0, CITE_Y, 0]).align_to([-X_MAX, 0, 0], LEFT)
        scene.play(FadeIn(c), run_time=0.4)
        group.add(c)
    return group


def closer(scene, text, cx=None, size=None):
    cx = P(-0.6, 0.0) if cx is None else cx
    line = _fit(_t(text, size=size or P(31, 26), color=ACCT, weight="BOLD"),
                CLOSE_W, [cx, CLOSE_Y, 0])
    under = _underline(line, buff=0.16)
    scene.play(FadeIn(line, shift=UP * 0.10), run_time=0.75)
    scene.play(Create(under), run_time=0.4)
    return VGroup(line, under)


# ── Plate helpers ────────────────────────────────────────────────────────────
def _plate(name, w, at, frame=True, opacity=1.0):
    """A synthetic terrain plate, framed like a figure in a paper.

    Returns a `Group`: ImageMobject is not a VMobject. Falls back to a blank
    plate if the asset is missing so a scene can never fail to render.
    """
    path = PLOTS / name
    parts = []
    hh = w * (860.0 / 1280.0)
    try:
        img = ImageMobject(str(path))
        img.width = w
        img.move_to(at)
        if opacity < 1.0:
            img.set_opacity(opacity)
        hh = float(img.height)
        parts.append(img)
    except Exception:
        parts.append(Rectangle(width=w, height=hh, color=CARD, fill_color=CARD,
                               fill_opacity=1, stroke_width=0).move_to(at))
    if frame:
        parts.append(Rectangle(width=w, height=hh, color=GHOST, stroke_width=1.6,
                               fill_opacity=0).move_to(at))
    return Group(*parts)


def _plate_h(name, w):
    """The height a plate of width w will occupy, without building it."""
    try:
        from PIL import Image as _I
        iw, ih = _I.open(PLOTS / name).size
        return w * ih / iw
    except Exception:
        return w * 860.0 / 1280.0


def _cap(txt, target, size=None, buff=0.16):
    """A caption under a plate. Every plate that could be mistaken for a NASA
    image gets one — that is a SOURCES.md promise, not a nicety."""
    c = _t(txt, size=size or P(16, 14), color=SOFT)
    c.next_to(target, DOWN, buff=buff)
    return c


def _bar(value, full_w, h, at, fill=ACC, track=True):
    """A horizontal proportion bar, left-anchored at `at`."""
    g = VGroup()
    if track:
        t = Rectangle(width=full_w, height=h, color=GHOST, stroke_width=1.4,
                      fill_color=CARD, fill_opacity=1.0)
        t.move_to([at[0] + full_w / 2, at[1], 0])
        g.add(t)
    w = max(full_w * float(value), 0.02)
    b = Rectangle(width=w, height=h, color=fill, fill_color=fill,
                  fill_opacity=1.0, stroke_width=0)
    b.move_to([at[0] + w / 2, at[1], 0])
    g.add(b)
    return g


def _rover(at, r=0.13):
    """The rover mark: the one thing on screen that has to commit."""
    return Dot(point=at, radius=r, color=ACCT)


def _arrow(a, b, color=None, sw=4.2, tip=0.20):
    return Arrow(start=a, end=b, color=color or GHOST, stroke_width=sw,
                 max_tip_length_to_length_ratio=tip, buff=0.06)


# ── Pacing: the scene fits the narration, not the other way round ────────────
# compile.py fills a beat by SLOWING the clip to length. These scenes originally
# ran 8-12 s against 22-34 s beats, so the compiler stretched them up to 3.3x —
# visible slow-motion, and it flagged three beats for replacement. The fix is not
# to shorten the narration (the human signed it) but to pace the picture to it:
# every reveal takes longer (RT) and rests afterwards (HOLD), and the tail pads
# to the measured duration. The compiler's fit factor then lands at ~1.0.
#
# RT/HOLD are per scene because the beats are not the same length. They are set
# to UNDERSHOOT slightly; hold_to_beat() absorbs the remainder, which is also why
# the same numbers work in portrait, where some scenes carry fewer elements.
def _beat_seconds():
    try:
        import json
        d = json.loads((HERE / "beat_sheet.json").read_text(encoding="utf-8"))
        return {b["beat_id"]: float(b.get("actual_duration_s") or 0)
                for b in d.get("beats", [])}
    except Exception:
        return {}


BEAT_SECONDS = _beat_seconds()


class Paced(Scene):
    """A Scene that paces itself to its beat's measured narration."""

    BEAT = None
    RT = 1.0        # run_time multiplier
    HOLD = 0.0      # rest after each reveal
    _raw = False

    def play(self, *args, **kwargs):
        if self._raw:                      # re-entry from Scene.wait()
            return Scene.play(self, *args, **kwargs)
        kwargs["run_time"] = float(kwargs.get("run_time", 1.0)) * self.RT
        Scene.play(self, *args, **kwargs)
        if self.HOLD:
            self.wait(self.HOLD)

    def wait(self, duration=1.0, **kwargs):
        prev = self._raw
        self._raw = True
        try:
            Scene.wait(self, duration, **kwargs)
        finally:
            self._raw = prev

    def hold_to_beat(self, floor=0.35):
        """Hold the finished composition until the narration is done."""
        target = BEAT_SECONDS.get(self.BEAT or "", 0.0)
        now = float(getattr(getattr(self, "renderer", None), "time", 0.0) or 0.0)
        self.wait(max(floor, target - now) if target else floor)




# ═════════════════════════════════════════════════════════════════════════════
#  B01 — PRESENTER
# ═════════════════════════════════════════════════════════════════════════════
class B01_Presenter(Paced):
    BEAT, RT, HOLD = "B01", 0.907, 0.0

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "AI in Astronomy & Space Science  ·  Ep. 07",
               cite="brutalist.art  ·  ai-explainer  ·  Pragmatist register")

        name_at = P([-3.30, 1.30, 0], [0, 1.92, 0])
        name = _fit(_t("Om Mali", size=P(98, 66), weight="BOLD"),
                    P(5.6, 3.30), name_at)
        self.play(Write(name), run_time=1.1)
        self.play(Create(_underline(name, sw=P(7, 5), buff=P(0.22, 0.16), pad=0.12)),
                  run_time=0.6)

        role = _fit(_t("Humanitarians AI  ·  presenter", size=P(29, 22), color=SOFT),
                    P(5.6, 3.30))
        role.move_to([name_at[0], name_at[1] - P(1.40, 0.86), 0])
        self.play(FadeIn(role, shift=UP * 0.1), run_time=0.5)

        pw, ph = P(5.6, 3.52), P(3.60, 2.30)
        pc = P([3.20, 0.45, 0], [0, -0.80, 0])
        self.play(Create(_card(pw, ph, pc)), run_time=0.7)

        r1 = _fit(_t("six episodes", size=P(28, 22)), pw - 0.7)
        r1.move_to([pc[0], pc[1] + ph * 0.31, 0])
        r1b = _fit(_t("AI looks at the data", size=P(24, 19), color=SOFT), pw - 0.7)
        r1b.move_to([pc[0], pc[1] + ph * 0.13, 0])
        self.play(FadeIn(r1), FadeIn(r1b), run_time=0.5)
        self.play(Create(_strike(r1b, pad=0.10)), run_time=0.45)

        self.play(Create(Line([pc[0] - pw * 0.42, pc[1] - ph * 0.02, 0],
                              [pc[0] + pw * 0.42, pc[1] - ph * 0.02, 0],
                              color=RULE, stroke_width=2)), run_time=0.3)

        r2 = _fit(_t("this one", size=P(30, 24), color=ACCT, weight="BOLD"), pw - 0.7)
        r2.move_to([pc[0], pc[1] - ph * 0.18, 0])
        r2b = _fit(_t("AI replaces the physics", size=P(26, 21), color=ACCT), pw - 0.7)
        r2b.move_to([pc[0], pc[1] - ph * 0.36, 0])
        self.play(FadeIn(r2, shift=UP * 0.08), run_time=0.5)
        self.play(FadeIn(r2b), run_time=0.45)

        closer(self, "Ep. 07  ·  there is nothing to look at.", size=P(28, 23))
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B02 — EXECUTIVE SUMMARY
# ═════════════════════════════════════════════════════════════════════════════
class B02_OneBreath(Paced):
    BEAT, RT, HOLD = "B02", 1.508, 0.0

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "The whole idea, in one breath",
               cite="2D particle-mesh run made for this episode  ·  512 squared")

        pw = P(3.55, 2.20)
        pat = P([-3.55, 0.35, 0], [0, 1.42, 0])
        plate = _plate("nbody.png", pw, pat)
        self.play(FadeIn(plate), run_time=0.8)
        self.play(FadeIn(_cap("a simulated universe — 2D toy, not a survey", plate)),
                  run_time=0.35)

        stage = P([3.00, 0.35, 0], [0, -1.10, 0])
        sw = P(5.8, 3.40)

        s1 = _fit(_t("no experiment", size=P(44, 33), weight="BOLD"), sw,
                  [stage[0], stage[1] + 0.55, 0])
        s1b = _fit(_t("is possible", size=P(34, 26), color=SOFT), sw,
                   [stage[0], stage[1] - 0.18, 0])
        self.play(FadeIn(s1, shift=UP * 0.12), run_time=0.7)
        self.play(FadeIn(s1b), run_time=0.5)
        self.wait(0.5)
        self.play(FadeOut(s1), FadeOut(s1b), run_time=0.4)

        s2 = _fit(_t("so you simulate it", size=P(40, 30), weight="BOLD"), sw,
                  [stage[0], stage[1] + 0.55, 0])
        s2b = _fit(_t("thousands of times", size=P(34, 26), color=SOFT), sw,
                   [stage[0], stage[1] - 0.18, 0])
        self.play(FadeIn(s2, shift=UP * 0.12), run_time=0.6)
        self.play(FadeIn(s2b), run_time=0.5)
        self.wait(0.5)
        self.play(FadeOut(s2), FadeOut(s2b), run_time=0.4)

        s3 = _fit(_t("nobody can afford that", size=P(38, 27), color=ACCT,
                     weight="BOLD"), sw, [stage[0], stage[1] + 0.30, 0])
        self.play(FadeIn(s3, shift=UP * 0.12), run_time=0.6)

        closer(self, "so a network learns the answer instead")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B03 — THE PARAMETER SPACE
# ═════════════════════════════════════════════════════════════════════════════
class B03_ParameterSpace(Paced):
    BEAT, RT, HOLD = "B03", 1.55, 0.11

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "You are not checking one universe",
               cite="Quijote suite: Villaescusa-Navarro et al. 2020")

        bw, bh = P(4.90, 3.20), P(3.30, 2.35)
        bc = P([-3.20, 0.40, 0], [0, 1.30, 0])
        box = Rectangle(width=bw, height=bh, color=GHOST, stroke_width=2.0,
                        fill_color=CARD, fill_opacity=1.0).move_to(bc)
        self.play(Create(box), run_time=0.7)

        if not PORTRAIT:
            xa = _t("one parameter", size=19, color=SOFT)
            xa.move_to([bc[0], bc[1] - bh / 2 - 0.26, 0])
            ya = _t("another", size=19, color=SOFT).rotate(PI / 2)
            ya.move_to([bc[0] - bw / 2 - 0.26, bc[1], 0])
            self.play(FadeIn(xa), FadeIn(ya), run_time=0.4)

        # one dot per cosmology — a Latin-hypercube-ish scatter, seeded
        rng = np.random.default_rng(24)
        dots = VGroup()
        for _ in range(150):
            u, v = rng.random(), rng.random()
            dots.add(Dot(point=[bc[0] + (u - 0.5) * bw * 0.90,
                                bc[1] + (v - 0.5) * bh * 0.90, 0],
                         radius=P(0.038, 0.030), color=INK))
        self.play(LaggedStart(*[FadeIn(d) for d in dots], lag_ratio=0.004),
                  run_time=1.3)

        col_x = P(3.55, 0.0)
        row_w = P(4.60, 3.44)
        ys = P([1.70, 0.80, -0.10], [-0.42, -1.06, -1.70])
        for txt, sub, y in (("44,100", "N-body simulations", ys[0]),
                            ("7,000", "cosmologies", ys[1]),
                            ("8.5 trillion", "particles", ys[2])):
            big = _fit(_t(txt, size=P(40, 30), weight="BOLD"), row_w,
                       [col_x, y + P(0.20, 0.16), 0])
            sml = _fit(_t(sub, size=P(22, 17), color=SOFT), row_w,
                       [col_x, y - P(0.26, 0.20), 0])
            self.play(FadeIn(big, shift=UP * 0.08), run_time=0.45)
            self.play(FadeIn(sml), run_time=0.3)

        if not PORTRAIT:
            chip = _chip("built as training data", size=23, max_w=4.60)
            chip.move_to([col_x, -1.15, 0])
            self.play(FadeIn(chip, shift=UP * 0.08), run_time=0.5)

        closer(self, "you are searching a parameter space")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B04 — THE COST
# ═════════════════════════════════════════════════════════════════════════════
class B04_NoShortcut(Paced):
    BEAT, RT, HOLD = "B04", 1.55, 0.081

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "Gravity has no shortcut",
               cite="the loop every N-body code runs  ·  2D toy, 512 squared")

        pw = P(3.30, 1.55)
        pat = P([-3.75, 0.40, 0], [0, 1.78, 0])
        plate = _plate("ic.png", pw, pat)
        self.play(FadeIn(plate), run_time=0.7)
        self.play(FadeIn(_cap("the starting field", plate)), run_time=0.35)

        cc = P([3.05, 0.45, 0], [0, -0.55, 0])
        R = P(1.42, 0.88)
        RING = R * 0.55
        ring = Circle(radius=RING, color=GHOST, stroke_width=2.2).move_to(cc)
        self.play(Create(ring), run_time=0.6)

        labels = ("deposit", "solve", "kick", "drift")
        angles = (PI / 2, 0.0, -PI / 2, PI)
        nodes = []
        for lab, ang in zip(labels, angles):
            at = [cc[0] + R * np.cos(ang), cc[1] + R * np.sin(ang), 0]
            ch = _quiet_chip(lab, size=P(22, 17))
            ch.move_to(at)
            nodes.append(ch)
            self.play(FadeIn(ch, scale=0.9), run_time=0.38)

        arc = Arc(arc_center=cc, radius=RING, start_angle=PI / 2,
                  angle=-TAU * 0.80, color=ACC, stroke_width=P(5, 4))
        self.play(Create(arc), run_time=0.8)

        chip = _chip("hundreds of steps", size=P(23, 18), max_w=P(4.4, 3.4))
        chip.move_to([cc[0], cc[1] - R - P(0.78, 0.36), 0])
        self.play(FadeIn(chip, shift=UP * 0.08), run_time=0.5)

        closer(self, "every particle pulls every other")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B05 — THE CHEAP GUESS
# ═════════════════════════════════════════════════════════════════════════════
class B05_Zeldovich(Paced):
    BEAT, RT, HOLD = "B05", 1.55, 0.159

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "The cheap answer: one move, then stop",
               cite="Zel'dovich 1970  ·  the displacement is computed, not drawn")

        # the schematic: a particle, one straight move, and no second thought
        sy = P(1.75, 2.40)
        x0, x1 = P(-4.60, -1.20), P(-1.90, 1.20)
        a = Dot(point=[x0, sy, 0], radius=P(0.10, 0.08), color=GHOST)
        b = Dot(point=[x1, sy, 0], radius=P(0.11, 0.09), color=ACCT)
        self.play(FadeIn(a), run_time=0.3)
        self.play(GrowArrow(_arrow([x0 + 0.16, sy, 0], [x1 - 0.16, sy, 0], color=ACC)),
                  run_time=0.7)
        self.play(FadeIn(b), run_time=0.3)
        lab = _fit(_t("one straight move, in one step", size=P(23, 18), color=SOFT),
                   P(5.0, 3.30))
        lab.move_to([(x0 + x1) / 2, sy - P(0.46, 0.38), 0])
        self.play(FadeIn(lab), run_time=0.4)

        pw = P(3.35, 2.30)
        pat = P([-3.35, -0.55, 0], [0, 0.42, 0])
        plate = _plate("zeldovich.png", pw, pat, frame=False)
        self.play(FadeIn(plate), run_time=0.8)
        ph = _plate_h("zeldovich.png", pw)
        self.play(Create(Rectangle(width=pw, height=ph, color=ACC,
                                   stroke_width=P(5, 4), fill_opacity=0).move_to(pat)),
                  run_time=0.5)

        col_x = P(3.10, 0.0)
        cw = P(4.90, 3.44)
        cys = P([-0.05, -1.05], [-1.10, -1.78])
        c1 = _quiet_chip("right while it is smooth", size=P(23, 18), max_w=cw)
        c1.move_to([col_x, cys[0], 0])
        self.play(FadeIn(c1), run_time=0.45)
        c2 = _chip("wrong once it collapses", size=P(23, 18), max_w=cw)
        c2.move_to([col_x, cys[1], 0])
        self.play(FadeIn(c2, shift=UP * 0.08), run_time=0.5)

        closer(self, "exact, right up until it matters")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B06 — THE CORRECTION
# ═════════════════════════════════════════════════════════════════════════════
class B06_TheCorrection(Paced):
    BEAT, RT, HOLD = "B06", 1.339, 0.0

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "Learn the difference, not the law",
               cite="the residual is measured: N-body minus Zel'dovich, same seed")

        if PORTRAIT:
            pw = 1.52
            za, na = [-0.86, 1.78, 0], [0.86, 1.78, 0]
        else:
            pw = 2.15
            za, na = [-4.55, 1.10, 0], [-1.55, 1.10, 0]

        z = _plate("zeldovich.png", pw, za, frame=False)
        self.play(FadeIn(z), run_time=0.6)
        ph = _plate_h("zeldovich.png", pw)
        self.play(Create(Rectangle(width=pw, height=ph, color=ACC, stroke_width=4,
                                   fill_opacity=0).move_to(za)), run_time=0.35)
        zl = _t("cheap guess", size=P(20, 15), color=ACCT)
        zl.move_to([za[0], za[1] - ph / 2 - P(0.30, 0.24), 0])
        self.play(FadeIn(zl), run_time=0.3)

        n = _plate("nbody.png", pw, na)
        self.play(FadeIn(n), run_time=0.6)
        nl = _t("the real thing", size=P(20, 15), color=SOFT)
        nl.move_to([na[0], na[1] - ph / 2 - P(0.30, 0.24), 0])
        self.play(FadeIn(nl), run_time=0.3)

        minus = _t("−", size=P(46, 34), color=INK)
        minus.move_to([(za[0] + na[0]) / 2, za[1], 0])
        self.play(FadeIn(minus), run_time=0.3)

        if PORTRAIT:
            rat, rw = [0, -0.62, 0], 2.10
            self.play(GrowArrow(_arrow([0, 0.72, 0], [0, 0.36, 0])), run_time=0.4)
        else:
            rat, rw = [1.95, 1.10, 0], 2.15
            self.play(GrowArrow(_arrow([-0.32, 1.10, 0], [0.70, 1.10, 0])), run_time=0.4)
        r = _plate("residual.png", rw, rat)
        self.play(FadeIn(r), run_time=0.7)
        rh = _plate_h("residual.png", rw)
        rl = _fit(_t("where the cheap guess is wrong", size=P(20, 15), color=SOFT),
                  P(3.0, 3.30))
        rl.move_to([rat[0], rat[1] - rh / 2 - P(0.30, 0.24), 0])
        self.play(FadeIn(rl), run_time=0.3)

        if not PORTRAIT:
            net = VGroup()
            cx = 4.85
            for li, (nn, dy) in enumerate(((3, 0.62), (4, 0.48), (2, 0.78))):
                for k in range(nn):
                    net.add(Dot(point=[cx + (li - 1) * 0.62,
                                       1.10 + (k - (nn - 1) / 2) * dy, 0],
                                radius=0.065, color=INK))
            self.play(LaggedStart(*[FadeIn(d) for d in net], lag_ratio=0.05),
                      run_time=0.7)
            nt = _fit(_t("learn this", size=23, color=ACCT, weight="BOLD"), 2.4,
                      [cx, -0.30, 0])
            self.play(FadeIn(nt, shift=UP * 0.08), run_time=0.45)

        closer(self, "it never computes a force")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B07 — THE RESULT
# ═════════════════════════════════════════════════════════════════════════════
class B07_Result(Paced):
    BEAT, RT, HOLD = "B07", 1.55, 0.157

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "Five percent, for a thousandth of the cost",
               cite="~5% and 1/1000: Learning the Universe, arXiv:2502.13242 (2025)")

        pw = P(6.30, 3.40)
        pat = P([-2.45, 0.50, 0], [0, 1.55, 0])
        plate = _plate("power.png", pw, pat)
        self.play(FadeIn(plate), run_time=0.9)
        ph = _plate_h("power.png", pw)

        xa = _fit(_t("smaller scales  →", size=P(20, 16), color=SOFT), P(4.0, 3.0))
        xa.move_to([pat[0], pat[1] - ph / 2 - P(0.30, 0.24), 0])
        self.play(FadeIn(xa), run_time=0.4)
        if not PORTRAIT:
            ya = _t("power", size=20, color=SOFT).rotate(PI / 2)
            ya.move_to([pat[0] - pw / 2 - 0.30, pat[1], 0])
            self.play(FadeIn(ya), run_time=0.35)

        col_x = P(4.35, 0.0)
        cw = P(3.30, 3.44)
        lys = P([1.90, 1.30], [-0.15, -0.72])
        for txt, colour, y in (("N-body", INK, lys[0]), ("Zel'dovich", ACCT, lys[1])):
            sw = Line(LEFT, RIGHT, color=colour, stroke_width=P(7, 6)).set_width(0.55)
            lb = _t(txt, size=P(23, 18), color=colour)
            g = VGroup(sw, lb).arrange(RIGHT, buff=0.20).move_to([col_x, y, 0])
            self.play(FadeIn(g), run_time=0.4)

        n1 = _fit(_t("within ~5%", size=P(38, 28), color=ACCT, weight="BOLD"), cw,
                  [col_x, P(0.28, -1.40), 0])
        self.play(FadeIn(n1, shift=UP * 0.10), run_time=0.5)
        self.play(Create(_underline(n1, buff=0.12)), run_time=0.35)
        n2 = _fit(_t("a thousandth of the time", size=P(24, 19), color=SOFT), cw,
                  [col_x, P(-0.52, -1.86), 0])
        self.play(FadeIn(n2), run_time=0.45)

        if not PORTRAIT:
            note = _fit(_t("on the statistics cosmologists actually use", size=21,
                           color=SOFT), 3.30)
            note.move_to([col_x, -1.30, 0])
            self.play(FadeIn(note), run_time=0.45)

        closer(self, "the shortcut is not a small one")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B08 — THE DESIGN TELL
# ═════════════════════════════════════════════════════════════════════════════
class B08_DesignTell(Paced):
    BEAT, RT, HOLD = "B08", 1.46, 0.0

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "The design tell",
               cite="an emulator is a learned map, not a solver")

        cw, ch = P(6.30, 3.30), P(3.60, 2.90)
        cc = P([-1.95, 0.40, 0], [0, 0.85, 0])
        self.play(Create(_card(cw, ch, cc)), run_time=0.7)

        head = _fit(_t("WHAT THE MODEL LEARNED", size=P(25, 20), color=ACCT,
                       weight="BOLD"), cw - 0.8, [cc[0], cc[1] + ch * 0.36, 0])
        self.play(FadeIn(head), run_time=0.45)
        self.play(Create(Line([cc[0] - cw * 0.40, cc[1] + ch * 0.24, 0],
                              [cc[0] + cw * 0.40, cc[1] + ch * 0.24, 0],
                              color=RULE, stroke_width=2)), run_time=0.3)

        r1 = _fit(_t("the law of gravity", size=P(28, 22)), cw - 1.0,
                  [cc[0], cc[1] + ch * 0.06, 0])
        self.play(FadeIn(r1), run_time=0.45)
        self.play(Create(_strike(r1, pad=0.12)), run_time=0.45)

        r2 = _fit(_t("the map from start to finish", size=P(28, 22), color=ACCT,
                     weight="BOLD"), cw - 1.0, [cc[0], cc[1] - ch * 0.16, 0])
        self.play(FadeIn(r2, shift=UP * 0.08), run_time=0.5)

        bound = Rectangle(width=min(r2.width + 0.44, cw - 0.6),
                          height=r2.height + 0.36, color=ACC,
                          stroke_width=P(4, 3), fill_opacity=0).move_to(r2)
        self.play(Create(bound), run_time=0.5)
        bl = _fit(_t("...for the universes it was shown", size=P(21, 17), color=SOFT),
                  cw - 0.9, [cc[0], cc[1] - ch * 0.36, 0])
        self.play(FadeIn(bl), run_time=0.4)

        if not PORTRAIT:
            pw = 2.20
            pat = [4.30, 0.55, 0]
            self.play(FadeIn(_plate("nbody.png", pw, pat)), run_time=0.6)
            ph = _plate_h("nbody.png", pw)
            self.play(Create(Rectangle(width=pw + 0.34, height=ph + 0.34,
                                       color=GHOST, stroke_width=2.2,
                                       fill_opacity=0).move_to(pat)), run_time=0.4)
            tl = _fit(_t("the training set", size=21, color=SOFT), 3.0,
                      [pat[0], pat[1] - ph / 2 - 0.46, 0])
            self.play(FadeIn(tl), run_time=0.35)

        closer(self, "compression, not physics")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B09 — WHERE IT FAILS
# ═════════════════════════════════════════════════════════════════════════════
class B09_WhereItBreaks(Paced):
    BEAT, RT, HOLD = "B09", 1.55, 0.218

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "The error sits where the galaxies are",
               cite="halo-interior errors: arXiv:2502.13242  ·  percentages measured here")

        pw = P(7.10, 3.50)
        pat = P([-2.05, 0.68, 0], [0, 1.70, 0])
        plate = _plate("halo_zoom.png", pw, pat)
        self.play(FadeIn(plate), run_time=0.9)
        ph = _plate_h("halo_zoom.png", pw)

        # the two panels inside the plate, labelled where they actually sit
        qx = pw * 0.245
        la = _t("N-body", size=P(22, 17), color=SOFT)
        la.move_to([pat[0] - qx, pat[1] - ph / 2 - P(0.30, 0.24), 0])
        lb = _t("Zel'dovich", size=P(22, 17), color=ACCT)
        lb.move_to([pat[0] + qx, pat[1] - ph / 2 - P(0.30, 0.24), 0])
        self.play(FadeIn(la), FadeIn(lb), run_time=0.4)

        ring = Circle(radius=P(0.42, 0.30), color=ACC, stroke_width=P(5, 4))
        ring.move_to([pat[0] + qx, pat[1], 0])
        self.play(Create(ring), run_time=0.6)

        note = _fit(_t("the core it fails to build", size=P(23, 18), color=ACCT),
                    P(5.0, 3.44))
        note.move_to(P([-2.05, -1.92, 0], [0, 0.32, 0]))
        self.play(FadeIn(note), run_time=0.45)

        col_x = P(4.40, 0.0)
        cw = P(3.30, 3.44)
        ys = P([1.55, 0.30], [-0.55, -1.45])
        for val, lab, y in (("4%", "on large scales", ys[0]),
                            ("58%", "on small ones", ys[1])):
            big = _fit(_t(val, size=P(46, 34), weight="BOLD"), cw,
                       [col_x, y + P(0.24, 0.20), 0])
            sml = _fit(_t(lab, size=P(21, 17), color=SOFT), cw,
                       [col_x, y - P(0.32, 0.26), 0])
            self.play(FadeIn(big, shift=UP * 0.08), run_time=0.45)
            self.play(FadeIn(sml), run_time=0.3)

        if not PORTRAIT:
            tag = _fit(_t("the cheap guess, measured in this reel's own run",
                          size=20, color=SOFT), 3.60)
            tag.move_to([col_x, -0.75, 0])
            self.play(FadeIn(tag), run_time=0.4)

        closer(self, "and haloes are where galaxies live")
        self.hold_to_beat()


# ═════════════════════════════════════════════════════════════════════════════
#  B10 — THE DEEPER LIMIT
# ═════════════════════════════════════════════════════════════════════════════
class B10_TheBox(Paced):
    BEAT, RT, HOLD = "B10", 1.458, 0.0

    def construct(self):
        self.camera.background_color = BG
        chrome(self, "It cannot leave the box",
               cite="the training set is N-body output — the cost is already paid")

        bw, bh = P(5.60, 3.30), P(3.30, 2.45)
        bc = P([-2.55, 0.45, 0], [0, 1.25, 0])
        box = Rectangle(width=bw, height=bh, color=INK, stroke_width=P(3.0, 2.6),
                        fill_color=CARD, fill_opacity=1.0).move_to(bc)
        self.play(Create(box), run_time=0.7)
        bl = _fit(_t("the cosmologies it was trained on", size=P(22, 17), color=SOFT),
                  bw + 0.4)
        bl.move_to([bc[0], bc[1] + bh / 2 + P(0.30, 0.20), 0])
        self.play(FadeIn(bl), run_time=0.4)

        # The chip is built FIRST so the dot field can be cleared around it.
        # An opaque chip is not enough: GATE B sees the geometry underneath, and
        # the doctrine is to clear a hole in the texture (Ep. 03's lesson).
        em = _chip("the emulator", size=P(23, 18), max_w=P(3.4, 2.6))
        em.move_to([bc[0], bc[1] - bh * 0.06, 0])
        hx = float(em.width) / 2 + P(0.26, 0.20)
        hy = float(em.height) / 2 + P(0.20, 0.16)

        rng = np.random.default_rng(91)
        dots = VGroup()
        while len(dots) < 90:
            u, v = rng.random(), rng.random()
            px = bc[0] + (u - 0.5) * bw * 0.86
            py = bc[1] + (v - 0.5) * bh * 0.80
            if abs(px - em.get_center()[0]) < hx and abs(py - em.get_center()[1]) < hy:
                continue                      # inside the chip's keep-out box
            dots.add(Dot(point=[px, py, 0], radius=P(0.040, 0.032), color=GHOST))
        self.play(LaggedStart(*[FadeIn(d, shift=DOWN * 0.12) for d in dots],
                              lag_ratio=0.008), run_time=1.1)

        self.play(FadeIn(em, scale=0.92), run_time=0.5)

        if PORTRAIT:
            a0 = [0, bc[1] - bh / 2 - 0.30, 0]
            a1 = [0, bc[1] - bh / 2 - 1.30, 0]
        else:
            a0 = [bc[0] + bw / 2 + 0.20, bc[1], 0]
            a1 = [bc[0] + bw / 2 + 2.10, bc[1], 0]
        arr = _arrow(a0, a1, color=ACC, sw=P(6, 5))
        self.play(GrowArrow(arr), run_time=0.7)
        mid = [(a0[0] + a1[0]) / 2, (a0[1] + a1[1]) / 2, 0]
        r = P(0.28, 0.22)
        cross = VGroup(
            Line([mid[0] - r, mid[1] - r, 0], [mid[0] + r, mid[1] + r, 0],
                 color=ACCT, stroke_width=P(7, 6)),
            Line([mid[0] - r, mid[1] + r, 0], [mid[0] + r, mid[1] - r, 0],
                 color=ACCT, stroke_width=P(7, 6)))
        for ln in cross:
            ln._qc_intentional = True
        self.play(Create(cross), run_time=0.5)

        out = _fit(_t("a cosmology it never saw", size=P(22, 17), color=ACCT),
                   P(3.20, 3.20))
        out.move_to(P([a1[0] + 0.10, bc[1] - 0.80, 0], [0, a1[1] - 0.44, 0]))
        self.play(FadeIn(out), run_time=0.45)

        closer(self, "a compression of what you already paid for")
        self.hold_to_beat()
