import React from 'react';
import {AbsoluteFill,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {z} from 'zod';
import {CLAUDE,CLAUDE_FONT} from '../tokens/claude';

const kinds=['transition','claims','question','temporal','dag','estimator','bootstrap','diagnostics','stockout','evidence','scale','pipeline','integration','outcome'] as const;
export const causalCoutureWeek6VerticalSchema=z.object({kind:z.enum(kinds)});
export type CausalCoutureWeek6VerticalProps=z.infer<typeof causalCoutureWeek6VerticalSchema>;
const serif=CLAUDE_FONT.serif,sans=CLAUDE_FONT.ui,mono=CLAUDE_FONT.mono,wash='#FFF5F0',muted='#F4F3EB';
const titles:Record<typeof kinds[number],string>={transition:'From Decision Intelligence to Causal Intelligence',claims:'Three Different Kinds of Evidence',question:'The First Causal Question',temporal:'Constructing the Temporal Dataset',dag:'The First Causal DAG',estimator:'Adjusted Observational Estimation',bootstrap:'Adding Uncertainty',diagnostics:'Placebo and Treatment Variation Diagnostics',stockout:'Stockouts and Suppressed Demand',evidence:'Evidence Summary and Robustness',scale:'Business-Scale Interpretation',pipeline:'The Unified Phase 5 Pipeline',integration:'API and Frontend Integration',outcome:'Testing, Boundaries, and the Week 6 Outcome'};
const Card:React.FC<{children:React.ReactNode;accent?:boolean;outline?:boolean;dim?:boolean;small?:boolean;status?:string}>=({children,accent,outline,dim,small,status})=><div style={{minHeight:small?92:132,padding:small?'16px 18px':'24px 22px',borderRadius:20,border:`2px ${outline?'dashed':'solid'} ${accent?CLAUDE.SPARK:CLAUDE.BORDER}`,background:accent?wash:dim?muted:CLAUDE.CARD,boxShadow:'0 10px 28px rgba(61,57,41,.075)',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:9,textAlign:'center',fontFamily:sans,fontSize:small?24:31,fontWeight:650,lineHeight:1.18,color:CLAUDE.INK,whiteSpace:'pre-line'}}>{status&&<div style={{fontFamily:mono,fontSize:15,letterSpacing:1.3,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{status}</div>}{children}</div>;
const V:React.FC<{children:React.ReactNode;gap?:number}>=({children,gap=16})=><div style={{display:'grid',gap,width:'100%'}}>{children}</div>;
const Arrow=()=> <div style={{fontFamily:sans,fontSize:44,color:CLAUDE.SPARK,textAlign:'center',lineHeight:1}}>↓</div>;
const Key:React.FC<{children:React.ReactNode}>=({children})=><div style={{display:'inline-flex',alignSelf:'center',padding:'9px 16px',border:`1px solid ${CLAUDE.SPARK}`,borderRadius:999,background:wash,fontFamily:mono,fontSize:16,letterSpacing:1.1,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{children}</div>;
const Flow:React.FC<{items:string[];accentAt?:number}>=({items,accentAt=items.length-1})=><V gap={10}>{items.map((x,i)=><React.Fragment key={x}><Card small accent={i===accentAt}>{x}</Card>{i<items.length-1&&<Arrow/>}</React.Fragment>)}</V>;
const Body:React.FC<CausalCoutureWeek6VerticalProps>=({kind})=>{switch(kind){
case'transition':return <V><Card small>Observed Signals</Card><Arrow/><Card small>Trends · Alerts · Recommendations</Card><Arrow/><Card small>Scenario Simulation</Card><Arrow/><Card accent status="Next analytical layer">Causal Intelligence</Card><Card outline status="Boundary">Foundation for rigorous analysis · not proof of causality</Card></V>;
case'claims':return <V><Card accent status="Historical description">Observed Signal</Card><Arrow/><Card status="User-defined hypothetical">Scenario Simulation<br/><span style={{fontSize:22}}>Not a forecast</span></Card><Arrow/><Card outline status="Estimate under assumptions">Estimated Causal Effect</Card></V>;
case'question':return <V><Card accent status="First implemented causal question"><span style={{fontFamily:serif,fontSize:34}}>What is the causal effect of social engagement on subsequent product sales?</span></Card><Arrow/><Card>engagement_rate_t</Card><div style={{fontSize:28,textAlign:'center',fontFamily:mono,color:CLAUDE.SPARK}}>same SKU · next day</div><Card>units_sold_next_day</Card><Key>Canonical grain: date × SKU</Key></V>;
case'temporal':return <V><Flow items={['Current & Prior Signals','Inventory + Validity Fields','Check the actual next date','Temporal Causal Dataset']}/><Card accent>t → t + 1 calendar day only</Card><Card dim>Gaps between dates are not treated as next-day outcomes.</Card></V>;
case'dag':return <V><Card accent status="Causal question">Engagement at t</Card><Arrow/><Card status="Outcome">Sales at t + 1</Card><div style={{fontFamily:mono,fontSize:17,textAlign:'center',color:CLAUDE.INK_SOFT}}>Confounding considerations</div><V gap={10}>{['Prior Sales','Prior Engagement','Inventory Availability','SKU Effects','Time Effects'].map(x=><Card key={x} small>{x}</Card>)}</V><Card outline status="Mediator caution">Web behavior may occur after engagement and before purchase. Not automatically adjusted.</Card></V>;
case'estimator':return <V><V gap={10}>{['Current Engagement','Prior Sales','Prior Engagement','Inventory, when available','SKU Fixed Effects','Day-of-Week Effects'].map(x=><Card key={x} small>{x}</Card>)}</V><Arrow/><Card accent status="Implemented estimator">Linear Regression<br/><span style={{fontSize:23}}>Observational estimate</span></Card><Card dim>Inventory-constrained observations may be excluded from primary estimation.</Card></V>;
case'bootstrap':return <V><Flow items={['Resample observations','Re-estimate model','Repeat process','Report uncertainty']}/><Card outline status="Reported outputs">Mean · median · standard error · percentile interval</Card><div style={{fontFamily:mono,fontSize:16,textAlign:'center',color:CLAUDE.INK_SOFT}}>FIRST-STAGE DIAGNOSTIC · NO VALUES SHOWN</div></V>;
case'diagnostics':return <V><Card accent status="Placebo diagnostic">Shuffle treatment<br/><span style={{fontSize:21}}>Not proof of identification</span></Card><Arrow/><Card status="Variation diagnostic">Range · distribution · unique values<br/><span style={{fontSize:21}}>Not formal positivity proof</span></Card><Arrow/><Card outline>Diagnostic comparison guides more scrutiny or reassurance.</Card></V>;
case'stockout':return <V><Card accent status="Retail-specific diagnostic"><span style={{fontFamily:serif,fontSize:35}}>Low observed sales ≠ necessarily low demand</span></Card><V gap={10}>{['Normal Inventory','Low Stock','Inventory Pressure','Complete Stockout'].map(x=><Card key={x} small status="Condition">{x}</Card>)}</V><Card outline>Identifies suppressed-demand risk; does not recover latent demand.</Card></V>;
case'evidence':return <V><V gap={10}>{['Minimal adjustment','Inventory-adjusted','SKU-adjusted','Preferred'].map(x=><Card key={x} small status="Specification">{x}</Card>)}</V><Arrow/><Card accent status="Robustness question">Directionally stable or specification-sensitive?</Card><Arrow/><Card outline status="Evidence summary">Stronger · Moderate · Weak · Insufficient support<br/><span style={{fontSize:20}}>Not probability of causality</span></Card></V>;
case'scale':return <V><Key>Business-scale interpretation</Key><Card>Engagement rate</Card><Arrow/><Card accent>+10 percentage points<br/><span style={{fontSize:22}}>Estimated sales effect</span></Card><Card dim>Scale changes interpretation, not observational status.</Card></V>;
case'pipeline':return <V><Flow items={['Unified Retail Dataset','Temporal Causal Dataset','Adjusted Effect Estimation','Bootstrap Uncertainty']}/><Arrow/><Flow items={['Placebo Test','Treatment Variation / Overlap','Stockout Diagnostics','Robustness']}/><Arrow/><Flow items={['Evidence Summary','Causal Intelligence Response']}/></V>;
case'integration':return <V><Card>Unified Retail Dataset</Card><Arrow/><Card accent status="FastAPI route">GET /phase5/causal-intelligence</Card><Arrow/><Card>Frontend Causal Intelligence</Card><V gap={10}>{['Effect & direction','Uncertainty interval','Evidence & placebo','Stockout & robustness'].map(x=><Card key={x} small status="Presented output">{x}</Card>)}</V></V>;
case'outcome':return <V><Card accent status="Tested">Backend reload · Swagger · Endpoint</Card><Card status="Preserved">Phase 1–4 functionality</Card><Card outline status="Boundary">Not completed causal inference</Card><Card accent status="Week 6 outcome"><span style={{fontFamily:serif,fontSize:35}}>Working first causal-analysis architecture</span><span>Foundation of Causal Intelligence</span></Card><Card dim>Observed signal ≠ scenario simulation ≠ estimated causal effect</Card><div style={{display:'flex',justifyContent:'center',gap:18,fontFamily:sans,fontSize:24}}><span>Ushasvi Rachel</span><span style={{color:CLAUDE.SPARK}}>·</span><span>Humanitarians.ai</span></div></V>;
}}
export const CausalCoutureWeek6Vertical:React.FC<CausalCoutureWeek6VerticalProps>=({kind})=>{const frame=useCurrentFrame();const{fps}=useVideoConfig();const entered=spring({frame,fps,config:{damping:24,stiffness:105,mass:.9}});const progress=interpolate(frame,[0,110],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:CLAUDE.PAGE,color:CLAUDE.INK}}><div style={{position:'absolute',left:'5%',top:220,fontFamily:sans,fontSize:26,letterSpacing:3,fontWeight:750,color:CLAUDE.INK_SOFT,textTransform:'uppercase'}}>Causal Couture</div><div style={{position:'absolute',left:'5%',right:'5%',top:315,height:5,background:CLAUDE.BORDER}}><div style={{height:'100%',width:`${progress*100}%`,background:CLAUDE.SPARK}}/></div><div style={{position:'absolute',left:'5%',right:'5%',top:385,fontFamily:serif,fontSize:68,fontWeight:700,lineHeight:1.04}}>{titles[kind]}</div><div style={{position:'absolute',left:'5%',right:'5%',top:700,bottom:390,display:'flex',alignItems:'center',justifyContent:'center',opacity:entered,transform:`translateY(${(1-entered)*22}px)`,overflow:'hidden'}}><div style={{width:'100%',maxHeight:'100%',overflow:'hidden'}}><Body kind={kind}/></div></div><div style={{position:'absolute',left:'5%',right:'5%',bottom:220,display:'flex',justifyContent:'space-between',fontFamily:sans,fontSize:26,color:CLAUDE.INK_SOFT}}><span>Ushasvi Rachel</span><span>Humanitarians.ai</span></div></AbsoluteFill>};
