import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {z} from 'zod';
import {CLAUDE, CLAUDE_FONT} from '../tokens/claude';
import {SAFE} from '../tokens/layout';

const kinds=['transition','claims','question','temporal','dag','estimator','bootstrap','diagnostics','stockout','evidence','scale','pipeline','integration','outcome'] as const;
export const causalCoutureWeek6Schema=z.object({kind:z.enum(kinds)});
export type CausalCoutureWeek6Props=z.infer<typeof causalCoutureWeek6Schema>;
const serif=CLAUDE_FONT.serif,sans=CLAUDE_FONT.ui,mono=CLAUDE_FONT.mono,wash='#FFF5F0',muted='#F4F3EB';
const titles:Record<typeof kinds[number],string>={transition:'From Decision Intelligence to Causal Intelligence',claims:'Three Different Kinds of Evidence',question:'The First Causal Question',temporal:'Constructing the Temporal Dataset',dag:'The First Causal DAG',estimator:'Adjusted Observational Estimation',bootstrap:'Adding Uncertainty',diagnostics:'Placebo and Treatment Variation Diagnostics',stockout:'Stockouts and Suppressed Demand',evidence:'Evidence Summary and Robustness',scale:'Business-Scale Interpretation',pipeline:'The Unified Phase 5 Pipeline',integration:'API and Frontend Integration',outcome:'Testing, Boundaries, and the Week 6 Outcome'};
const Card:React.FC<{children:React.ReactNode;accent?:boolean;outline?:boolean;dim?:boolean;small?:boolean;status?:string}>=({children,accent,outline,dim,small,status})=><div style={{minHeight:small?84:116,padding:small?'14px 16px':'22px 25px',borderRadius:18,border:`2px ${outline?'dashed':'solid'} ${accent?CLAUDE.SPARK:CLAUDE.BORDER}`,background:accent?wash:dim?muted:CLAUDE.CARD,boxShadow:'0 9px 28px rgba(61,57,41,.075)',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:8,textAlign:'center',fontFamily:sans,fontSize:small?19:27,fontWeight:650,lineHeight:1.18,color:CLAUDE.INK,whiteSpace:'pre-line'}}>{status&&<div style={{fontFamily:mono,fontSize:13,letterSpacing:1.3,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{status}</div>}{children}</div>;
const Arrow=()=> <div style={{fontFamily:sans,fontSize:38,color:CLAUDE.SPARK,textAlign:'center'}}>→</div>;
const Key:React.FC<{children:React.ReactNode}>=({children})=><div style={{display:'inline-flex',padding:'8px 15px',border:`1px solid ${CLAUDE.SPARK}`,borderRadius:999,background:wash,fontFamily:mono,fontSize:14,letterSpacing:1.2,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{children}</div>;
const Flow:React.FC<{items:string[];accentAt?:number}>=({items,accentAt=items.length-1})=><div style={{display:'flex',alignItems:'center',gap:9,width:'100%'}}>{items.map((x,i)=><React.Fragment key={x}><div style={{flex:1}}><Card small accent={i===accentAt}>{x}</Card></div>{i<items.length-1&&<Arrow/>}</React.Fragment>)}</div>;
const Stack:React.FC<{items:string[];accentAt?:number}>=({items,accentAt=0})=><div style={{display:'grid',gap:13,width:'100%'}}>{items.map((x,i)=><Card key={x} small accent={i===accentAt}>{x}</Card>)}</div>;
const Body:React.FC<CausalCoutureWeek6Props>=({kind})=>{switch(kind){
case'transition':return <div style={{display:'grid',gap:22}}><Flow items={['Observed Signals','Trends · Alerts · Recommendations','Scenario Simulation','Causal Intelligence']} accentAt={3}/><Card outline status="Foundation, not proof">Technical and methodological groundwork for more rigorous causal analysis</Card></div>;
case'claims':return <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:17}}><Card accent status="Historical description">Observed Signal</Card><Card status="User-defined hypothetical">Scenario Simulation<br/><span style={{fontSize:20}}>Not a forecast</span></Card><Card outline status="Estimate under assumptions">Estimated Causal Effect</Card></div>;
case'question':return <div style={{display:'grid',gap:24}}><Card accent status="First implemented causal question"><span style={{fontFamily:serif,fontSize:34}}>What is the causal effect of social engagement on subsequent product sales?</span></Card><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:20,alignItems:'center'}}><Card>engagement_rate_t</Card><Arrow/><Card>units_sold_next_day</Card></div><Key>Canonical grain: date × SKU</Key></div>;
case'temporal':return <div style={{display:'grid',gap:19}}><Flow items={['Current & Prior Signals','Inventory + Validity Fields','Exact Date Check','Temporal Causal Dataset']} accentAt={3}/><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:18,alignItems:'center'}}><Card accent>t</Card><Arrow/><Card accent>t + 1 calendar day only</Card></div><Card dim>Gaps between dates are not treated as next-day outcomes.</Card></div>;
case'dag':return <div style={{display:'grid',gridTemplateColumns:'1fr 1.1fr 1fr',gap:19,alignItems:'center'}}><Stack items={['Prior Sales','Prior Engagement','Inventory Availability','SKU Effects','Time Effects']} /><div style={{display:'grid',gap:14}}><Card accent status="Causal question">Engagement at t</Card><div style={{textAlign:'center',fontSize:34,color:CLAUDE.SPARK}}>↓</div><Card status="Outcome">Sales at t + 1</Card></div><Card outline status="Mediator caution">Web behavior may occur after engagement and before purchase.<br/><span style={{fontSize:19}}>Not automatically adjusted.</span></Card></div>;
case'estimator':return <div style={{display:'grid',gap:18}}><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:18,alignItems:'center'}}><Stack items={['Current Engagement','Prior Sales','Prior Engagement','Inventory, when available','SKU Fixed Effects','Day-of-Week Effects']} /><Arrow/><Card accent status="Implemented estimator">Linear Regression<br/><span style={{fontSize:21}}>Observational estimate</span></Card></div><Card dim>Inventory-constrained observations may be excluded from primary estimation.</Card></div>;
case'bootstrap':return <div style={{display:'grid',gap:20}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:13}}>{['Resample','Re-estimate','Repeat','Report uncertainty'].map((x,i)=><Card key={x} small accent={i===3} status="Bootstrap step">{x}</Card>)}</div><Card outline status="Reported outputs">Mean · median · standard error · percentile interval</Card><div style={{fontFamily:mono,fontSize:14,textAlign:'center',color:CLAUDE.INK_SOFT}}>FIRST-STAGE DIAGNOSTIC · NO VALUES SHOWN</div></div>;
case'diagnostics':return <div style={{display:'grid',gap:18}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}><Card accent status="Placebo diagnostic">Shuffle treatment<br/><span style={{fontSize:19}}>Not proof of identification</span></Card><Card status="Variation diagnostic">Range · distribution · unique values<br/><span style={{fontSize:19}}>Not formal positivity proof</span></Card></div><Flow items={['Original treatment','Diagnostic comparison','More scrutiny or reassurance']} accentAt={2}/></div>;
case'stockout':return <div style={{display:'grid',gap:20}}><Card accent status="Retail-specific diagnostic"><span style={{fontFamily:serif,fontSize:35}}>Low observed sales ≠ necessarily low demand</span></Card><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:13}}>{['Normal Inventory','Low Stock','Inventory Pressure','Complete Stockout'].map((x,i)=><Card key={x} small status="Condition">{x}</Card>)}</div><Card outline>Identifies suppressed-demand risk; does not recover latent demand.</Card></div>;
case'evidence':return <div style={{display:'grid',gap:18}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:13}}>{['Minimal','Inventory-adjusted','SKU-adjusted','Preferred'].map((x,i)=><Card key={x} small status="Specification">{x}</Card>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:18,alignItems:'center'}}><Card accent status="Robustness question">Directionally stable<br/>or specification-sensitive?</Card><Arrow/><Card outline status="Evidence summary">Stronger · Moderate<br/>Weak · Insufficient support<br/><span style={{fontSize:18}}>Not probability of causality</span></Card></div></div>;
case'scale':return <div style={{display:'grid',gap:22}}><Key>Business-scale interpretation</Key><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:20,alignItems:'center'}}><Card>Engagement rate</Card><Arrow/><Card accent>+10 percentage points<br/><span style={{fontSize:20}}>Estimated sales effect</span></Card></div><Card dim>Scale changes interpretation, not the observational status of the estimate.</Card></div>;
case'pipeline':return <div style={{display:'grid',gap:11}}><Flow items={['Unified Retail Dataset','Temporal Causal Dataset','Adjusted Effect Estimation','Bootstrap Uncertainty']} /><Flow items={['Placebo Test','Treatment Variation / Overlap','Stockout Diagnostics','Robustness']} /><Flow items={['Evidence Summary','Causal Intelligence Response']} accentAt={1}/></div>;
case'integration':return <div style={{display:'grid',gap:18}}><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr .12fr 1fr',gap:15,alignItems:'center'}}><Card>Unified Dataset</Card><Arrow/><Card accent status="FastAPI route">GET /phase5/causal-intelligence</Card><Arrow/><Card>Frontend Causal Intelligence</Card></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{['Effect & direction','Uncertainty interval','Evidence & placebo','Stockout & robustness'].map(x=><Card key={x} small status="Presented output">{x}</Card>)}</div></div>;
case'outcome':return <div style={{display:'grid',gap:20}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:14}}><Card accent status="Tested">Backend reload<br/>Swagger<br/>Endpoint</Card><Card status="Preserved">Phase 1–4<br/>functionality</Card><Card outline status="Boundary">Not completed causal inference</Card></div><Card accent status="Week 6 outcome"><span style={{fontFamily:serif,fontSize:36}}>Working first causal-analysis architecture</span><span>Foundation of Causal Intelligence</span></Card><div style={{fontFamily:serif,fontSize:31,textAlign:'center'}}>Observed signal ≠ scenario simulation ≠ estimated causal effect</div><div style={{display:'flex',justifyContent:'center',gap:26,fontFamily:sans,fontSize:24}}><span>Ushasvi Rachel</span><span style={{color:CLAUDE.SPARK}}>·</span><span>Humanitarians.ai</span></div></div>;
}}
export const CausalCoutureWeek6:React.FC<CausalCoutureWeek6Props>=({kind})=>{const frame=useCurrentFrame();const{fps}=useVideoConfig();const entered=spring({frame,fps,config:{damping:24,stiffness:105,mass:.9}});const progress=interpolate(frame,[0,110],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:CLAUDE.PAGE,color:CLAUDE.INK}}><div style={{position:'absolute',left:SAFE.x,top:SAFE.y,fontFamily:sans,fontSize:17,letterSpacing:3,fontWeight:750,color:CLAUDE.INK_SOFT,textTransform:'uppercase'}}>Causal Couture</div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,top:118,height:3,background:CLAUDE.BORDER}}><div style={{height:'100%',width:`${progress*100}%`,background:CLAUDE.SPARK}}/></div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,top:156,fontFamily:serif,fontSize:58,fontWeight:700,lineHeight:1.05}}>{titles[kind]}</div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,top:275,bottom:135,display:'flex',alignItems:'center',justifyContent:'center',opacity:entered,transform:`translateY(${(1-entered)*24}px)`}}><div style={{width:'100%'}}><Body kind={kind}/></div></div><div style={{position:'absolute',left:SAFE.x,right:SAFE.x,bottom:62,display:'flex',justifyContent:'space-between',fontFamily:sans,fontSize:20,color:CLAUDE.INK_SOFT}}><span>Ushasvi Rachel</span><span>Humanitarians.ai</span></div></AbsoluteFill>};
