import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {z} from 'zod';
import {CLAUDE, CLAUDE_FONT} from '../tokens/claude';
import {SAFE} from '../tokens/layout';

const kinds=['opening','definition','useful','causal-leap','boundary','business','seasonality','promotion','external','confounding','four-tasks','description-association','causal-forecast','recommendation','language','takeaway'] as const;
export const correlationCausationSchema=z.object({kind:z.enum(kinds)});
export type CorrelationCausationProps=z.infer<typeof correlationCausationSchema>;
const serif=CLAUDE_FONT.serif,sans=CLAUDE_FONT.ui,mono=CLAUDE_FONT.mono,wash='#FFF5F0',muted='#F3F1E8',navy='#315D70';
const titles:Record<typeof kinds[number],string>={opening:'Two Lines. One Tempting Story.',definition:'What Correlation Means',useful:'Correlation Is Useful', 'causal-leap':'The Causal Leap',boundary:'Association Is Not Causation',business:'A Simple Business Example',seasonality:'Alternative Explanation: Seasonality',promotion:'Promotions and Pricing',external:'Launches, Events, and Hidden Factors',confounding:'The Confounding Structure','four-tasks':'Four Different Analytical Questions','description-association':'Description and Association','causal-forecast':'Causal Inference and Forecasting',recommendation:'From Signal to Recommendation',language:'Match the Language to the Evidence',takeaway:'Correlation Finds Patterns. Causation Needs More.'};
const Card:React.FC<{children:React.ReactNode;accent?:boolean;dim?:boolean;outline?:boolean;small?:boolean;status?:string;align?:'center'|'left'}>=({children,accent,dim,outline,small,status,align='center'})=><div style={{minHeight:small?92:126,padding:small?'16px 18px':'24px 28px',borderRadius:20,border:`${outline?'3px dashed':'3px solid'} ${accent?CLAUDE.SPARK:CLAUDE.BORDER}`,background:accent?wash:dim?muted:CLAUDE.CARD,boxShadow:'0 10px 30px rgba(61,57,41,.08)',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:align==='left'?'flex-start':'center',gap:9,textAlign:align,fontFamily:sans,fontSize:small?22:29,fontWeight:650,lineHeight:1.16,color:CLAUDE.INK,whiteSpace:'pre-line'}}>{status&&<div style={{fontFamily:mono,fontSize:15,letterSpacing:1.4,color:accent?CLAUDE.SPARK:navy,textTransform:'uppercase'}}>{status}</div>}{children}</div>;
const Arrow:React.FC<{dotted?:boolean}>=({dotted})=><div style={{fontFamily:sans,fontSize:46,color:dotted?navy:CLAUDE.SPARK,textAlign:'center',lineHeight:1}}>{dotted?'⇢':'→'}</div>;
const Key:React.FC<{children:React.ReactNode}>=({children})=><div style={{display:'inline-flex',padding:'9px 15px',border:`2px solid ${CLAUDE.SPARK}`,borderRadius:999,background:wash,fontFamily:mono,fontSize:16,letterSpacing:1.25,color:CLAUDE.SPARK,textTransform:'uppercase'}}>{children}</div>;
const MiniChart:React.FC<{label:string;direction?:'up'|'down'|'flat';color?:string}>=({label,direction='up',color=CLAUDE.SPARK})=><div style={{border:`3px solid ${CLAUDE.BORDER}`,borderRadius:20,background:CLAUDE.CARD,padding:20,display:'grid',gap:13}}><div style={{fontFamily:sans,fontSize:24,fontWeight:700}}>{label}</div><svg viewBox="0 0 420 150" style={{width:'100%',height:150}}><line x1="20" y1="130" x2="400" y2="130" stroke={CLAUDE.BORDER} strokeWidth="3"/><line x1="20" y1="15" x2="20" y2="130" stroke={CLAUDE.BORDER} strokeWidth="3"/><path d={direction==='up'?'M25 118 C100 110, 125 88, 185 92 S290 52, 395 24':direction==='down'?'M25 25 C100 32, 140 70, 200 64 S300 104, 395 120':'M25 74 C110 70, 155 78, 220 73 S320 76, 395 72'} fill="none" stroke={color} strokeWidth="8" strokeLinecap="round"/></svg><div style={{fontFamily:mono,fontSize:15,color:CLAUDE.INK_SOFT}}>ILLUSTRATIVE TRACE · NO NUMERICAL CLAIM</div></div>;
const Node:React.FC<{children:React.ReactNode;accent?:boolean;dim?:boolean}>=({children,accent,dim})=><div style={{padding:'20px 23px',borderRadius:18,border:`3px solid ${accent?CLAUDE.SPARK:CLAUDE.BORDER}`,background:accent?wash:dim?muted:CLAUDE.CARD,fontFamily:sans,fontSize:25,fontWeight:700,textAlign:'center',boxShadow:'0 8px 24px rgba(61,57,41,.07)'}}>{children}</div>;
const VStack:React.FC<{children:React.ReactNode;gap?:number}>=({children,gap=18})=><div style={{display:'grid',gap,width:'100%'}}>{children}</div>;
const VerticalBody:React.FC<CorrelationCausationProps>=({kind})=>{switch(kind){
case'opening':return <VStack><MiniChart label="Engagement"/><MiniChart label="Sales" color={navy}/><Node accent>Engagement ↑</Node><Arrow dotted/><Node>Sales ↑</Node><div style={{fontFamily:serif,fontSize:34,fontWeight:700,textAlign:'center'}}>Did engagement cause the increase in sales?</div></VStack>;
case'definition':return <VStack><Key>Statistical relationship</Key><MiniChart label="Move Together"/><MiniChart label="Move Oppositely" direction="down" color={navy}/><MiniChart label="Another Consistent Pattern" direction="flat"/></VStack>;
case'useful':return <VStack><Card accent status="Correlation can">Reveal Patterns</Card><Card status="Correlation can">Flag Unusual Relationships</Card><Card status="Correlation can">Generate Better Questions</Card><Card outline>Beginning of Analysis<br/>Not Automatically the End</Card></VStack>;
case'causal-leap':return <VStack><Node accent>Engagement Increased</Node><Arrow dotted/><Node>Sales Increased</Node><Card status="Supported observation">Increased Together</Card><Card outline status="Additional causal claim">Changing Engagement Produced the Sales Change</Card></VStack>;
case'boundary':return <VStack><Card accent status="Chart supports"><span style={{fontFamily:serif,fontSize:34}}>Observed Association</span><span>Variables display a relationship</span></Card><div style={{height:3,background:CLAUDE.SPARK}}/><Card dim status="Chart alone does not establish"><span style={{fontFamily:serif,fontSize:34}}>Causal Effect</span><span>One variable produced the other</span></Card></VStack>;
case'business':return <VStack><Key>Representative dashboard</Key><MiniChart label="Social Engagement"/><MiniChart label="Sales" color={navy}/><div style={{fontFamily:serif,fontSize:31,fontWeight:700,textAlign:'center'}}>The dashboard shows what moved—not why sales increased.</div></VStack>;
case'seasonality':return <VStack><Node accent>Seasonal or High-Demand Period</Node><div style={{fontSize:50,color:CLAUDE.SPARK,textAlign:'center'}}>↓　↓</div><Node>Engagement</Node><Node>Sales</Node><Key>Possible explanation · not verified</Key></VStack>;
case'promotion':return <VStack><Node accent>Promotion</Node><Node accent>Pricing Change</Node><div style={{fontSize:48,color:CLAUDE.SPARK,textAlign:'center'}}>↓　↓</div><Node>Attention / Engagement</Node><Node>Purchases / Sales</Node></VStack>;
case'external':return <VStack><Node accent>Product Launch</Node><Node>External Event</Node><Node dim>Other Hidden Factors</Node><div style={{fontSize:48,color:CLAUDE.SPARK,textAlign:'center'}}>↓　↓</div><Node>Customer Interest</Node><Node>Customer Spending</Node></VStack>;
case'confounding':return <VStack><Node accent>Third or Confounding Factor</Node><div style={{fontSize:54,color:CLAUDE.SPARK,textAlign:'center'}}>↙　↘</div><Node>Suspected Cause · Engagement</Node><Arrow dotted/><Node>Outcome · Sales</Node><div style={{fontFamily:serif,fontSize:28,textAlign:'center'}}>The direct causal link remains unproven.</div></VStack>;
case'four-tasks':return <VStack><Card accent align="left" status="Descriptive analytics">What happened?</Card><Card align="left" status="Correlation / association">What moved together?</Card><Card align="left" status="Causal inference">What effect would an intervention produce?</Card><Card align="left" status="Forecasting">What is likely to happen next?</Card></VStack>;
case'description-association':return <VStack><Card accent status="Descriptive analytics">What happened in the data?</Card><MiniChart label="Observed Business Conditions" direction="flat"/><Card status="Association">Which variables display a relationship?</Card><MiniChart label="Variable A"/><MiniChart label="Variable B" color={navy}/></VStack>;
case'causal-forecast':return <VStack><Card accent status="Causal inference">What effect would an intervention produce?</Card><Node>Intervention</Node><Arrow/><Node>Outcome</Node><Card status="Forecasting">What is likely to happen next?</Card><MiniChart label="Observed Data → Future Region"/></VStack>;
case'recommendation':return <VStack><Card>Observed Signal</Card><Card accent status="Evidence checkpoint">What Does the Evidence Support?</Card><Card>Business Recommendation</Card><Card small>Other explanations? · Uncertainty? · Calibrated claim?</Card></VStack>;
case'language':return <VStack><Card accent align="left" status="Supported association"><span style={{fontFamily:serif,fontSize:31}}>“Engagement and sales increased together.”</span></Card><Card outline align="left" status="Requires stronger evidence"><span style={{fontFamily:serif,fontSize:31}}>“Increasing engagement caused higher sales.”</span></Card></VStack>;
case'takeaway':return <VStack><Card accent status="Correlation"><span style={{fontFamily:serif,fontSize:35}}>Find Patterns</span><span>Generate better questions</span></Card><Card outline status="Causal claims"><span style={{fontFamily:serif,fontSize:35}}>Require Stronger Evidence</span><span>Design · assumptions · methodology</span></Card><div style={{fontFamily:serif,fontSize:35,fontWeight:700,textAlign:'center'}}>Movement together does not prove cause and effect.</div><div style={{textAlign:'center',fontFamily:sans,fontSize:27}}>Ushasvi Rachel · Humanitarians.ai</div></VStack>;
}}

const Body:React.FC<CorrelationCausationProps>=({kind})=>{switch(kind){
case'opening':return <div style={{display:'grid',gap:22}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}><MiniChart label="Engagement"/><MiniChart label="Sales" color={navy}/></div><div style={{display:'grid',gridTemplateColumns:'1fr .13fr 1fr',gap:18,alignItems:'center',width:'72%',margin:'0 auto'}}><Node accent>Engagement ↑</Node><Arrow dotted/><Node>Sales ↑</Node></div><div style={{fontFamily:serif,fontSize:36,fontWeight:700,textAlign:'center'}}>Did engagement cause the increase in sales?</div></div>;
case'definition':return <div style={{display:'grid',gap:22}}><div style={{textAlign:'center'}}><Key>Statistical relationship in available data</Key></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}><MiniChart label="Move Together"/><MiniChart label="Move Oppositely" direction="down" color={navy}/><MiniChart label="Another Consistent Pattern" direction="flat"/></div></div>;
case'useful':return <div style={{display:'grid',gap:25}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}><Card status="Correlation can">Reveal Patterns</Card><Card status="Correlation can">Flag Unusual Relationships</Card><Card status="Correlation can">Generate Better Questions</Card></div><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:20,alignItems:'center',width:'72%',margin:'0 auto'}}><Card accent>Beginning of Analysis</Card><Arrow/><Card outline>Not Automatically the End</Card></div></div>;
case'causal-leap':return <div style={{display:'grid',gap:28}}><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:20,alignItems:'center'}}><Node accent>Engagement Increased</Node><Arrow dotted/><Node>Sales Increased</Node></div><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:20,alignItems:'center'}}><Card status="Supported observation">Increased Together</Card><Arrow/><Card outline status="Additional causal claim">Changing Engagement Produced the Sales Change</Card></div></div>;
case'boundary':return <div style={{display:'grid',gridTemplateColumns:'1fr .08fr 1fr',gap:25,alignItems:'stretch'}}><Card accent status="Chart supports"><span style={{fontFamily:serif,fontSize:40}}>Observed Association</span><span>Two variables display a relationship</span></Card><div style={{display:'flex',justifyContent:'center'}}><div style={{width:4,background:CLAUDE.SPARK}}/></div><Card dim status="Chart alone does not establish"><span style={{fontFamily:serif,fontSize:40}}>Causal Effect</span><span>Changing one variable produced the other</span></Card></div>;
case'business':return <div style={{display:'grid',gap:18}}><div style={{display:'flex',justifyContent:'space-between'}}><Key>Representative analytical dashboard</Key><span style={{fontFamily:mono,fontSize:16,color:CLAUDE.INK_SOFT}}>NOT HISTORICAL COMPANY DATA</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}><MiniChart label="Social Engagement"/><MiniChart label="Sales" color={navy}/></div><div style={{fontFamily:serif,fontSize:35,fontWeight:700,textAlign:'center'}}>The dashboard shows what moved—not why sales increased.</div></div>;
case'seasonality':return <div style={{display:'grid',gap:30}}><div style={{width:'48%',margin:'0 auto'}}><Node accent>Seasonal or High-Demand Period</Node></div><div style={{fontSize:50,color:CLAUDE.SPARK,textAlign:'center'}}>↙　↘</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:26}}><Node>Engagement</Node><Node>Sales</Node></div><div style={{textAlign:'center'}}><Key>Possible common explanation · not verified here</Key></div></div>;
case'promotion':return <div style={{display:'grid',gap:22}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}><Node accent>Promotion</Node><Node accent>Pricing Change</Node></div><div style={{fontSize:48,color:CLAUDE.SPARK,textAlign:'center'}}>↙　↓　↓　↘</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:26}}><Node>Attention / Engagement</Node><Node>Purchases / Sales</Node></div><div style={{fontFamily:serif,fontSize:30,textAlign:'center'}}>Unconsidered factors can be misattributed to engagement.</div></div>;
case'external':return <div style={{display:'grid',gap:20}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}><Node accent>Product Launch</Node><Node>External Event</Node><Node dim>Other Hidden Factors</Node></div><div style={{fontSize:48,color:CLAUDE.SPARK,textAlign:'center'}}>↘　↓　↙</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:26}}><Node>Customer Interest</Node><Node>Customer Spending</Node></div></div>;
case'confounding':return <div style={{display:'grid',gap:18}}><div style={{width:'45%',margin:'0 auto'}}><Node accent>Third or Confounding Factor</Node></div><div style={{fontSize:54,color:CLAUDE.SPARK,textAlign:'center',lineHeight:1}}>↙　↘</div><div style={{display:'grid',gridTemplateColumns:'1fr .25fr 1fr',gap:18,alignItems:'center'}}><Node>Suspected Cause<br/><span style={{fontWeight:500}}>Engagement</span></Node><Arrow dotted/><Node>Outcome<br/><span style={{fontWeight:500}}>Sales</span></Node></div><div style={{fontFamily:serif,fontSize:31,textAlign:'center'}}>The third factor influences both variables; the direct causal link remains unproven.</div></div>;
case'four-tasks':return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}><Card accent align="left" status="Descriptive analytics">What happened in the data?</Card><Card align="left" status="Correlation / association">Which variables display a relationship?</Card><Card align="left" status="Causal inference">What effect would an intervention produce?</Card><Card align="left" status="Forecasting">What is likely to happen next?</Card></div>;
case'description-association':return <div style={{display:'grid',gridTemplateColumns:'1fr .08fr 1fr',gap:23,alignItems:'stretch'}}><div style={{display:'grid',gap:16}}><Card accent status="Descriptive analytics">What happened?</Card><MiniChart label="Observed Business Conditions" direction="flat"/></div><div style={{display:'flex',justifyContent:'center'}}><div style={{width:3,background:CLAUDE.BORDER}}/></div><div style={{display:'grid',gap:16}}><Card status="Association">What moved together?</Card><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:13}}><MiniChart label="Variable A"/><MiniChart label="Variable B" color={navy}/></div></div></div>;
case'causal-forecast':return <div style={{display:'grid',gridTemplateColumns:'1fr .08fr 1fr',gap:23,alignItems:'stretch'}}><div style={{display:'grid',gap:18}}><Card accent status="Causal inference">What effect would an intervention produce?</Card><div style={{display:'grid',gridTemplateColumns:'1fr .15fr 1fr',alignItems:'center',gap:10}}><Node>Intervention</Node><Arrow/><Node>Outcome</Node></div><Key>Assumptions + causal methods</Key></div><div style={{display:'flex',justifyContent:'center'}}><div style={{width:3,background:CLAUDE.SPARK}}/></div><div style={{display:'grid',gap:18}}><Card status="Forecasting">What is likely to happen next?</Card><MiniChart label="Observed Data → Future Region"/><Key>Prediction is not a causal claim</Key></div></div>;
case'recommendation':return <div style={{display:'grid',gap:24}}><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1.2fr .12fr 1fr',gap:16,alignItems:'center'}}><Card>Observed Signal</Card><Arrow/><Card accent status="Evidence checkpoint">What Does the Evidence Support?</Card><Arrow/><Card>Business Recommendation</Card></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18}}><Card small>Other Explanations?</Card><Card small>Remaining Uncertainty?</Card><Card small>Claim Calibrated?</Card></div></div>;
case'language':return <div style={{display:'grid',gap:22}}><Card accent align="left" status="Supported by the observed pattern"><span style={{fontFamily:serif,fontSize:34}}>“Engagement and sales increased together.”</span><span>Association claim</span></Card><Card outline align="left" status="Requires stronger methodology and evidence"><span style={{fontFamily:serif,fontSize:34}}>“Increasing engagement caused higher sales.”</span><span>Causal claim</span></Card></div>;
case'takeaway':return <div style={{display:'grid',gap:23}}><div style={{display:'grid',gridTemplateColumns:'1fr .12fr 1fr',gap:21,alignItems:'center'}}><Card accent status="Correlation"><span style={{fontFamily:serif,fontSize:38}}>Find Patterns</span><span>Generate better questions</span></Card><Arrow/><Card outline status="Causal claims"><span style={{fontFamily:serif,fontSize:38}}>Require Stronger Evidence</span><span>Design · assumptions · methodology</span></Card></div><div style={{fontFamily:serif,fontSize:42,fontWeight:700,textAlign:'center'}}>Movement together does not prove cause and effect<span style={{color:CLAUDE.SPARK}}>.</span></div><div style={{display:'flex',justifyContent:'center',gap:30,fontFamily:sans,fontSize:29}}><span>Ushasvi Rachel</span><span style={{color:CLAUDE.SPARK}}>·</span><span>Humanitarians.ai</span></div></div>;
}}
export const CorrelationCausationExplainer:React.FC<CorrelationCausationProps>=(props)=>{const frame=useCurrentFrame();const{fps,width,height}=useVideoConfig();const vertical=height>width;const pad=vertical?Math.round(width*.05):SAFE.x;const entered=spring({frame,fps,config:{damping:24,stiffness:105,mass:.9}});const progress=interpolate(frame,[0,110],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:CLAUDE.PAGE,color:CLAUDE.INK}}><div style={{position:'absolute',left:pad,top:vertical?220:SAFE.y,fontFamily:sans,fontSize:vertical?26:18,letterSpacing:3,fontWeight:750,color:CLAUDE.INK_SOFT,textTransform:'uppercase'}}>Humanitarians.ai · STEM / Data Science</div><div style={{position:'absolute',left:pad,right:pad,top:vertical?315:118,height:vertical?5:4,background:CLAUDE.BORDER}}><div style={{height:'100%',width:`${progress*100}%`,background:CLAUDE.SPARK}}/></div><div style={{position:'absolute',left:pad,right:pad,top:vertical?385:158,fontFamily:serif,fontSize:vertical?70:60,fontWeight:700,lineHeight:1.04}}>{titles[props.kind]}</div><div style={{position:'absolute',left:pad,right:pad,top:vertical?700:280,bottom:vertical?390:138,display:'flex',alignItems:'center',justifyContent:'center',opacity:entered,transform:`translateY(${(1-entered)*22}px)`,overflow:'hidden'}}><div style={{width:'100%',maxHeight:'100%'}}>{vertical?<VerticalBody {...props}/>:<Body {...props}/>}</div></div><div style={{position:'absolute',left:pad,right:pad,bottom:vertical?220:62,display:'flex',justifyContent:'space-between',fontFamily:sans,fontSize:vertical?26:21,color:CLAUDE.INK_SOFT}}><span>Ushasvi Rachel</span><span>Humanitarians.ai</span></div></AbsoluteFill>};
