"""
Manim scenes for 2026-08-30-the-check-that-never-once-fired

v1 (2026-08-30): first build. 9 beats, all self-contained Manim (no pantry
stills, no Remotion) — same house pattern as this fellow's 3 prior reels,
this one being part 2 of the "Layer 1 hardening" pair with the sibling
2026-08-30-the-update-that-almost-lied-about-what-it-sent:

B00_TitleCard             — silent title card: video title + @HumanitariansAI (TITLE)
B01_ExecSummary           — spoken personal-intro card: name + one-line summary (EXEC-SUMMARY)
B02_ZeroMatchesHook       — the CFTC heuristic condition + red "0 MATCHES" stamp (HOOK)
B03_ClassifierCondition   — the full federalregister.gov branch, quoted verbatim (SETUP)
B04_RealFilingVsCondition — real title/link vs. the two checks, both shown ABSENT (DISCOVERY)
B05_FiveFeedResultsTable  — all 5 live-feed rows, CFTC + zero-regression rows highlighted (PROOF)
B06_BeforeAfterClassifier — before/after identifySource() branch, dc:creator highlighted (FIX)
B07_Statement             — takeaway card (TAKEAWAY)
B08_BrandOutro            — @HumanitariansAI sign-off (SIGN-OFF)

Palette/fonts/helpers copied verbatim from this fellow's sibling reels
(2026-08-30-the-update-that-almost-lied-about-what-it-sent/scenes.py, which
itself carried them from 2026-07-26-recovering-the-silently-dropped-filings
and 2026-08-17-why-ai-generated-code-still-needs-a-human) for house-style
consistency: humanitarians/hai palette (not the Claude-branded one), plain
Text (Pango) throughout — never Integer/DecimalNumber/MathTex, this machine
has no LaTeX installed and Manim equation beats are the one blocked toolkit
feature (irrelevant here, no math in this reel).

Every code string quoted on screen (B02, B03, B04, B06) is verbatim from
/Users/pranavijs/mycroft/scripts/regulatory-intel/B2-VERIFICATION.md and the
pre-fix / post-fix workflow.dev.json JS (commit d59fbd5) — see SOURCES.md's
claim -> source mapping. B06's AFTER panel condenses the untouched SEC/FINRA
branches into one footer line (noted on screen as condensed) purely for
screen space; the dc:creator mechanism itself — the actual fix — is quoted
verbatim, nothing paraphrased there.

B04 is this reel's one side-by-side beat. Uses clear_of_divider(), ported
verbatim from 2026-08-17-why-ai-generated-code-still-needs-a-human/scenes.py
(the sibling reel that hit and fixed a real divider-crosses-glyph bug), and
verified by measuring real Manim object bounds (get_left()/get_right())
against the divider at x=0 before calling the beat done. B06 (before/after
code) also uses it as a second precaution even though its blocks are narrower.

TIMING NOTE (audio-first rule): self.play()/self.wait() values below are
tuned to each beat's *measured* Kokoro audio duration
(beat_sheet.json -> actual_duration_s, generated by
generate_audio_kokoro.py), not the pre-audio estimate:
  B00 4.05s (silent, fixed target — ffmpeg anullsrc, no narration to measure)
  B01 18.98s   B02 11.38s   B03 19.32s   B04 19.66s   B05 29.42s
  B06 13.94s   B07 10.56s   B08 6.26s
Each construct() below documents its own animation-time sum and the
resulting self.wait() so the beat lands on its measured length without the
compiler needing to slow-fit or freeze-pad into real content.
"""

from manim import *

PALETTE = {
    "bg":     "#F3EBDD",  # CREAM
    "ink":    "#2F2A26",  # INK
    "teal":   "#1F4E5F",  # good / CVD-safe cool
    "crimson": "#E4572E", # bad / CVD-safe warm
    "slate":  "#29335C",  # structure
    "gold":   "#F3A712",  # fill only — never text color
    "sage":   "#A8C686",  # human / growth
}

MONO = "Courier New"


def fit(mob, max_w):
    if mob.width > max_w:
        mob.scale_to_fit_width(max_w)
    return mob


def panel(width, height, fill=None, stroke=None, corner_radius=0.12, opacity=1.0):
    return RoundedRectangle(
        width=width, height=height, corner_radius=corner_radius,
        fill_color=fill or PALETTE["ink"], fill_opacity=opacity,
        stroke_color=stroke or PALETTE["slate"], stroke_width=2,
    )


def clear_of_divider(block, divider_x, side, margin=0.35):
    """Shift `block` (a VGroup/Mobject) so it keeps real clearance from a
    vertical divider at x=divider_x, measured from the block's OWN rendered
    bounds (get_left()/get_right()), not a guessed constant. Ported verbatim
    from the sibling reel
    2026-08-17-why-ai-generated-code-still-needs-a-human/scenes.py, which
    hit and fixed a real divider-crosses-glyph bug this exact way. Used here
    on this reel's side-by-side beats (B04, B06) rather than trusting a
    fit()-only max-width cap.

    side="left"  -> block sits left of the divider; keeps get_right() <=
                    divider_x - margin.
    side="right" -> block sits right of the divider; keeps get_left() >=
                    divider_x + margin.
    No-op if the block already clears the margin.
    """
    if side == "left":
        overhang = block.get_right()[0] - (divider_x - margin)
        if overhang > 0:
            block.shift(LEFT * overhang)
    else:
        overhang = (divider_x + margin) - block.get_left()[0]
        if overhang > 0:
            block.shift(RIGHT * overhang)
    return block


def box_around(mob, color, buff=0.12):
    r = Rectangle(
        width=mob.width + 2 * buff, height=mob.height + 2 * buff,
        stroke_color=color, stroke_width=3, fill_opacity=0,
    )
    r.move_to(mob.get_center())
    return r


# --------------------------------------------------------------------------- #
# B00 — TITLE: silent opening card, video title + @HumanitariansAI, no VO.
# Same bracket idiom as the sibling reels' B00_TitleCard.
# Audio: mp3/beat-B00.mp3 is a REAL silent mp3 (ffmpeg anullsrc, 4.05s
# measured), never audio_file: null — see beat_sheet.json's B00 shot.note.
# --------------------------------------------------------------------------- #
class B00_TitleCard(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        # font_size 54->66, rules 2.6->3.1, handle 38->44, buff 1.3->1.6 —
        # GATE V measured the first draft at only 36% canvas-fill (well
        # under the 55% floor: this title's two short lines are narrower
        # than the sibling reels' longer titles at the same font size);
        # real measurement confirmed this combination clears it with margin.
        # font_size 66->76, handle 44->52, rules 3.1->3.4, buff 1.35->1.45 —
        # GATE V's canvas-fill check measures the real rendered ink bounding
        # box against the safe area, and 66/1.35 only measured 45% (under
        # the 55% floor) even though 1.6 already meant the height was near
        # its own ceiling; real measurement confirmed this larger-font/
        # moderate-buff combination grows both axes together and clears the
        # floor while staying inside the safe height.
        title_line1 = fit(Text(
            "The Check That", color=PALETTE["ink"], font_size=76, weight="BOLD",
        ), 12.0)
        title_line2 = fit(Text(
            "Never Once Fired", color=PALETTE["ink"], font_size=76, weight="BOLD",
        ), 12.0)
        title = VGroup(title_line1, title_line2).arrange(DOWN, buff=0.3)

        top_rule = Line(LEFT * 3.4, RIGHT * 3.4, color=PALETTE["gold"], stroke_width=3)
        bottom_rule = Line(LEFT * 3.4, RIGHT * 3.4, color=PALETTE["gold"], stroke_width=3)
        handle = Text("@HumanitariansAI", color=PALETTE["slate"], font_size=52)

        VGroup(top_rule, title, bottom_rule, handle).arrange(
            DOWN, buff=1.45
        ).move_to(ORIGIN)

        self.play(Create(top_rule), run_time=0.35)
        self.play(FadeIn(title, shift=UP * 0.15), run_time=0.8)
        self.play(Create(bottom_rule), FadeIn(handle, shift=UP * 0.1), run_time=0.5)
        # animation sum = 1.65s; measured silent track = 4.05s
        self.wait(2.40)


# --------------------------------------------------------------------------- #
# B01 — EXEC-SUMMARY: spoken personal-intro card, name + role + 3-line
# plain-language summary matching the narration's own second sentence.
# --------------------------------------------------------------------------- #
class B01_ExecSummary(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        name = fit(Text(
            "Sai Pranavi Jeedigunta", color=PALETTE["ink"], font_size=56, weight="BOLD",
        ), 11.0)
        role = Text("Humanitarians AI Fellow", color=PALETTE["slate"], font_size=26)
        accent = Line(LEFT * 1.8, RIGHT * 1.8, color=PALETTE["gold"], stroke_width=3)

        summary_l1 = fit(Text(
            "A classifier written to catch CFTC filings that,",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary_l2 = fit(Text(
            "tested against real data, never once matched —",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary_l3 = fit(Text(
            "now reads the actual source instead of guessing.",
            color=PALETTE["ink"], font_size=30,
        ), 11.5)
        summary = VGroup(summary_l1, summary_l2, summary_l3).arrange(DOWN, buff=0.18)

        # buff=1.4 (not 1.15) — GATE V measured the tighter buff at 51%
        # canvas-fill, just under the 55% floor; real measurement confirmed
        # 1.4 clears it with margin, same lesson the sibling reels' B01
        # documents.
        VGroup(name, role, accent, summary).arrange(DOWN, buff=1.4).move_to(ORIGIN)
        summary_underline = Line(color=PALETTE["sage"], stroke_width=1)

        self.play(FadeIn(name, shift=UP * 0.2), run_time=0.7)
        self.play(FadeIn(role, shift=UP * 0.1), run_time=0.5)
        self.play(Create(accent), run_time=0.5)
        self.play(FadeIn(summary, shift=UP * 0.1), run_time=0.8)
        summary_underline.put_start_and_end_on(
            summary.get_corner(DL) + DOWN * 0.12, summary.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(summary_underline), run_time=0.3)
        # animation sum = 2.8s; measured narration = 18.74s
        self.wait(15.94)


# --------------------------------------------------------------------------- #
# B02 — HOOK: the classifier's CFTC-detection condition on screen, a red
# "0 MATCHES" stamp beside it. Condition quoted verbatim from
# B2-VERIFICATION.md "The bug" / workflow.dev.json pre-fix.
# --------------------------------------------------------------------------- #
class B02_ZeroMatchesHook(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        header = fit(Text(
            "identifySource() — the CFTC heuristic", color=PALETTE["slate"],
            font_size=24, font=MONO,
        ), 11.5)
        header.to_edge(UP, buff=0.7)
        self.play(Write(header), run_time=0.5)

        cond_lines = [
            "if (link.includes('commodity-futures')",
            "    || title.includes('cftc')) {",
            "  return 'CFTC Regulations';",
            "}",
        ]
        cond = VGroup(*[
            fit(Text(l, color=PALETTE["ink"], font_size=28, font=MONO), 9.5) for l in cond_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.18)
        cond.next_to(header, DOWN, buff=0.55)
        box = box_around(cond, PALETTE["teal"], buff=0.28)
        self.play(Create(box), FadeIn(cond), run_time=0.7)

        stamp_text = Text("0 MATCHES", color=PALETTE["crimson"], font_size=72, weight="BOLD")
        stamp_box = Rectangle(
            width=stamp_text.width + 0.6, height=stamp_text.height + 0.35,
            stroke_color=PALETTE["crimson"], stroke_width=5, fill_opacity=0,
        )
        stamp = VGroup(stamp_box, stamp_text)
        stamp.next_to(box, DOWN, buff=0.5)
        # NOTE: no rotation here — an earlier draft rotated the stamp for a
        # tilted-ink-stamp look, but GATE B's TEXT_ON_CURVE check (real,
        # not a false positive) correctly flagged that a rotated
        # rectangle's edges cross an axis-aligned text box's centerlines
        # even with generous padding. Kept level; still reads as a stamp
        # from the bold red text + surrounding box alone.
        self.play(Write(stamp_text), Create(stamp_box), run_time=0.65)

        caption = fit(Text(
            "tested against every live CFTC item pulled today",
            color=PALETTE["slate"], font_size=24,
        ), 11.5)
        caption.next_to(stamp, DOWN, buff=0.45)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        # 3rd distinct non-text shape, added later than `box`/`stamp_box` —
        # gives GATE A's "shapes never change" check a real changing shape
        # signature across the hold, same pattern the sibling reels use.
        caption_underline = Line(color=PALETTE["sage"], stroke_width=1)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.12, caption.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 0.5+0.7+0.65+0.5+0.3 = 2.65s; measured narration = 11.38s
        self.wait(8.73)


# --------------------------------------------------------------------------- #
# B03 — SETUP: the full federalregister.gov branch, quoted verbatim from
# B2-VERIFICATION.md "The bug" / workflow.dev.json pre-fix, the two checks
# and the default both highlighted. Legible before any live data is shown.
# --------------------------------------------------------------------------- #
class B03_ClassifierCondition(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["ink"]
        cream = PALETTE["bg"]

        header = fit(Text(
            "identifySource() — the Federal Register branch", color=cream,
            font_size=20, font=MONO,
        ), 12.5)
        header.to_edge(UP, buff=0.6)
        self.play(Write(header), run_time=0.5)

        lines = [
            "if (lowerLink.includes('federalregister.gov')) {",
            "  if (lowerLink.includes('commodity-futures')",
            "      || lowerTitle.includes('cftc')) {",
            "    return 'CFTC Regulations';",
            "  }",
            "  return 'Federal Register - Securities';",
            "}",
        ]
        # font_size 22->26, buff 0.26->0.32, header buff 0.55->0.7 — GATE V
        # measured the first draft at 49% canvas-fill, under the 55% floor;
        # real measurement confirmed this combination clears it with margin.
        code = VGroup(*[
            fit(Text(l, color=cream, font_size=26, font=MONO), 12.0) for l in lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.32)
        code.next_to(header, DOWN, buff=0.7)
        self.play(LaggedStart(*[FadeIn(l, shift=RIGHT * 0.1) for l in code], lag_ratio=0.12), run_time=1.0)

        # the two checks — link contains 'commodity-futures' OR title
        # contains 'cftc' — boxed together in teal.
        checks = VGroup(code[1], code[2])
        checks_box = box_around(checks, PALETTE["teal"], buff=0.14)
        self.play(Create(checks_box), run_time=0.5)
        # tag font_size 24->18, buff 0.3->0.2 — GATE B measured the bigger
        # tag's right edge at x=6.92, past the 6.3 safe wall (the code
        # block itself already runs close to the wall at this larger font
        # size); real measurement confirmed this combination clears it.
        checks_tag = fit(Text("the two checks", color=PALETTE["teal"], font_size=18, font=MONO, weight="BOLD"), 2.6)
        checks_tag.next_to(checks_box, RIGHT, buff=0.2)
        self.play(Write(checks_tag), run_time=0.5)

        # the default — everything else falls through to 'Securities'.
        default_box = box_around(code[5], PALETTE["crimson"], buff=0.14)
        self.play(Create(default_box), run_time=0.5)
        default_tag = fit(Text("the default", color=PALETTE["crimson"], font_size=18, font=MONO, weight="BOLD"), 2.6)
        default_tag.next_to(default_box, RIGHT, buff=0.2)
        self.play(Write(default_tag), run_time=0.5)

        # animation sum = 0.5+1.0+0.5+0.5+0.5+0.5 = 3.5s; measured narration = 19.32s.
        # Full branch stays on screen together for the whole hold.
        self.wait(15.82)


# --------------------------------------------------------------------------- #
# B04 — DISCOVERY: a real CFTC filing (title + link, pulled live) side by
# side with the two checks from B03, both shown ABSENT — the rule was
# checking for something that structurally can't appear. This reel's one
# side-by-side beat; uses clear_of_divider(), verified by measured bounds.
# --------------------------------------------------------------------------- #
class B04_RealFilingVsCondition(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        header = fit(Text(
            "A real CFTC filing, pulled live today", color=PALETTE["ink"],
            font_size=32, weight="BOLD",
        ), 12.0)
        header.to_edge(UP, buff=0.6)
        self.play(Write(header), run_time=0.5)

        # LEFT — the real filing
        left_label = Text("REAL FILING", color=PALETTE["teal"], font_size=22, weight="BOLD")
        left_title_l1 = fit(Text(
            "“Swap Execution Facility Order Book", color=PALETTE["ink"], font_size=22,
        ), 5.4)
        left_title_l2 = fit(Text(
            "Requirement for Permitted Transactions”", color=PALETTE["ink"], font_size=22,
        ), 5.4)
        left_link = fit(Text(
            "federalregister.gov/documents/2026/08/26/",
            color=PALETTE["slate"], font_size=15, font=MONO,
        ), 5.4)
        left_link2 = fit(Text(
            "2026-17416/swap-execution-facility-...",
            color=PALETTE["slate"], font_size=15, font=MONO,
        ), 5.4)
        left_block = VGroup(
            left_label, left_title_l1, left_title_l2, left_link, left_link2
        ).arrange(DOWN, buff=0.22, aligned_edge=LEFT)
        left_block.move_to([-3.4, -0.2, 0])

        # RIGHT — what the rule looks for, both absent. Each check sits
        # ABOVE its own "ABSENT" tag (stacked, not side by side) — an
        # earlier side-by-side draft (check + tag in one row) pushed the
        # tag past the safe-area right wall (measured off-frame at
        # x=7.17, past the 6.3 safe wall / 7.11 hard edge); stacking keeps
        # the whole block inside a narrow ~5.2-wide column instead.
        right_label = fit(Text("WHAT THE RULE LOOKS FOR", color=PALETTE["crimson"], font_size=22, weight="BOLD"), 5.2)
        check1 = fit(Text("'cftc' in title", color=PALETTE["ink"], font_size=22, font=MONO), 5.2)
        absent1 = Text("→ ABSENT", color=PALETTE["crimson"], font_size=20, weight="BOLD")
        row1 = VGroup(check1, absent1).arrange(DOWN, buff=0.12, aligned_edge=LEFT)
        check2 = fit(Text("'commodity-futures' in link", color=PALETTE["ink"], font_size=22, font=MONO), 5.2)
        absent2 = Text("→ ABSENT", color=PALETTE["crimson"], font_size=20, weight="BOLD")
        row2 = VGroup(check2, absent2).arrange(DOWN, buff=0.12, aligned_edge=LEFT)
        right_block = VGroup(right_label, row1, row2).arrange(DOWN, buff=0.4, aligned_edge=LEFT)
        right_block.move_to([3.0, -0.2, 0])

        # measured-bounds clearance check, not a guessed constant — see
        # clear_of_divider()'s own docstring for the incident this prevents.
        clear_of_divider(left_block, divider_x=0, side="left")
        clear_of_divider(right_block, divider_x=0, side="right")

        caption = fit(Text(
            "checking for something that structurally can't appear",
            color=PALETTE["slate"], font_size=24,
        ), 11.5)
        caption.next_to(VGroup(left_block, right_block), DOWN, buff=0.55)

        # divider sized to the two blocks' OWN measured vertical span (with
        # padding), not a fixed frame-spanning length — the exact class of
        # bug clear_of_divider()'s docstring documents; measuring the real
        # bounds keeps the divider clear of the caption line below too.
        blocks_top = max(left_block.get_top()[1], right_block.get_top()[1]) + 0.25
        blocks_bottom = min(left_block.get_bottom()[1], right_block.get_bottom()[1]) - 0.25
        divider = Line([0, blocks_top, 0], [0, blocks_bottom, 0], color=PALETTE["slate"], stroke_width=2)

        self.play(Create(divider), run_time=0.3)
        self.play(
            FadeIn(left_block, shift=RIGHT * 0.1),
            FadeIn(right_block, shift=LEFT * 0.1),
            run_time=0.7,
        )
        self.play(Write(absent1), run_time=0.4)
        self.play(Write(absent2), run_time=0.4)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.5)

        # 2nd real (non-text) shape STATE beyond the divider — a lone
        # static Line for the whole hold trips GATE A's "shapes never
        # change" repeated-animation check (same class of fix as the
        # sibling reels' B02/B03/B04).
        caption_underline = Line(color=PALETTE["crimson"], stroke_width=1.5)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.1, caption.get_corner(DR) + DOWN * 0.1
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 0.5+0.3+0.7+0.4+0.4+0.5+0.3 = 3.1s; measured
        # narration = 19.66s. Real filing and both absent checks stay on
        # screen together for the whole hold — legible simultaneously.
        self.wait(16.56)


# --------------------------------------------------------------------------- #
# B05 — PROOF: the live test result table, ALL 5 feed rows visible — CFTC
# 12/12 reclassified, the general securities term search 83/146 reclassified
# to real agencies, and SEC/FINRA/Investment-Advisor at 0 changed (already
# correct). CFTC row and the zero-regression rows highlighted.
# --------------------------------------------------------------------------- #
class B05_FiveFeedResultsTable(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]
        ink = PALETTE["ink"]

        header = fit(Text(
            "Live test — all 5 real feeds, today", color=ink, font_size=32, weight="BOLD",
        ), 12.0)
        # buff=0.7 (not 0.55) — GATE B measured the tighter buff's top edge
        # at y=3.45, past the 3.4 safe ceiling; real measurement confirmed
        # 0.7 clears it with margin.
        header.to_edge(UP, buff=0.7)
        self.play(Write(header), run_time=0.5)

        feed_x, tested_x, reclass_x, result_x = -6.1, 1.6, 3.05, 3.55
        col_header_y = 2.35
        row_h = 0.62

        # NOTE: every Text() call below uses a LITERAL font_size (never a
        # variable) — the toolkit's GATE W static checker (wcag_margin_check.py)
        # resolves font_size via ast.literal_eval and cannot evaluate a Python
        # variable reference; an earlier draft used a small `cell(..., size=size)`
        # helper whose `font_size=size` was always a Name node, which crashed
        # the checker (TypeError comparing str >= int). Real toolkit static-
        # analysis limitation, not a Manim bug — same class of thing the
        # sibling short's BUILD-LOG documents for static_scene_check.py's own
        # B05 false positive. Fixed here by inlining literal font sizes.
        feed_label = Text("FEED", color=PALETTE["slate"], font_size=20, font=MONO, weight="BOLD")
        feed_label.move_to([feed_x, col_header_y, 0], aligned_edge=LEFT)
        tested_label = Text("TESTED", color=PALETTE["slate"], font_size=20, font=MONO, weight="BOLD")
        tested_label.move_to([tested_x, col_header_y, 0], aligned_edge=RIGHT)
        reclass_label = Text("RECLASS.", color=PALETTE["slate"], font_size=20, font=MONO, weight="BOLD")
        reclass_label.move_to([reclass_x, col_header_y, 0], aligned_edge=RIGHT)
        result_label = Text("RESULT", color=PALETTE["slate"], font_size=20, font=MONO, weight="BOLD")
        result_label.move_to([result_x, col_header_y, 0], aligned_edge=LEFT)
        col_labels = VGroup(feed_label, tested_label, reclass_label, result_label)

        header_rule = Line(
            [feed_x, col_header_y - 0.32, 0], [6.1, col_header_y - 0.32, 0],
            color=PALETTE["slate"], stroke_width=1.5,
        )
        self.play(FadeIn(col_labels), Create(header_rule), run_time=0.6)

        rows_data = [
            ("Federal Register - Securities", "146", "83", PALETTE["crimson"],
             "→ real agency (FCC, EEOC, DOT)"),
            ("CFTC Regulations", "12", "12", PALETTE["crimson"],
             "→ was 0/12 caught before"),
            ("SEC Press Releases", "25", "0", PALETTE["teal"],
             "unchanged — already correct"),
            ("FINRA (Google News)", "100", "0", PALETTE["teal"],
             "unchanged — already correct"),
            ("Investment Advisor Rules", "100", "0", PALETTE["teal"],
             "unchanged — already correct"),
        ]

        row_groups = []
        for i, (feed, tested, reclass, rcolor, result) in enumerate(rows_data):
            y = col_header_y - row_h * (i + 1)
            feed_t = fit(Text(feed, color=ink, font_size=22, font=MONO), 5.3)
            feed_t.move_to([feed_x, y, 0], aligned_edge=LEFT)
            tested_t = Text(tested, color=ink, font_size=22, font=MONO)
            tested_t.move_to([tested_x, y, 0], aligned_edge=RIGHT)
            reclass_t = Text(reclass, color=rcolor, font_size=22, font=MONO, weight="BOLD")
            reclass_t.move_to([reclass_x, y, 0], aligned_edge=RIGHT)
            result_t = fit(Text(result, color=PALETTE["slate"], font_size=18), 2.5)
            result_t.move_to([result_x, y, 0], aligned_edge=LEFT)
            row_groups.append(VGroup(feed_t, tested_t, reclass_t, result_t))

        self.play(LaggedStart(*[FadeIn(r, shift=RIGHT * 0.08) for r in row_groups], lag_ratio=0.15), run_time=1.1)

        # highlight the CFTC row (index 1) — the hero proof: 0 -> 12/12
        cftc_row = row_groups[1]
        cftc_box = Rectangle(
            width=12.5, height=row_h - 0.08,
            stroke_color=PALETTE["gold"], stroke_width=3, fill_opacity=0,
        )
        cftc_box.move_to([0.0, cftc_row.get_center()[1], 0])
        self.play(Create(cftc_box), run_time=0.5)

        # highlight the 3 zero-regression rows (SEC, FINRA, Investment Advisor)
        zero_rows = VGroup(row_groups[2], row_groups[3], row_groups[4])
        zero_top = zero_rows.get_top()[1] + 0.12
        zero_bottom = zero_rows.get_bottom()[1] - 0.12
        zero_box = Rectangle(
            width=12.5, height=zero_top - zero_bottom,
            stroke_color=PALETTE["teal"], stroke_width=3, fill_opacity=0,
        )
        zero_box.move_to([0.0, (zero_top + zero_bottom) / 2, 0])
        self.play(Create(zero_box), run_time=0.5)

        caption_l1 = fit(Text(
            "CFTC: every one now caught. SEC / FINRA / Investment Advisor:",
            color=PALETTE["slate"], font_size=22,
        ), 12.0)
        caption_l2 = fit(Text(
            "zero regressions on what already worked.",
            color=PALETTE["slate"], font_size=22,
        ), 12.0)
        caption = VGroup(caption_l1, caption_l2).arrange(DOWN, buff=0.14)
        caption.next_to(zero_box, DOWN, buff=0.4)
        self.play(FadeIn(caption, shift=UP * 0.1), run_time=0.6)

        caption_underline = Line(color=PALETTE["sage"], stroke_width=1)
        caption_underline.put_start_and_end_on(
            caption.get_corner(DL) + DOWN * 0.12, caption.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(caption_underline), run_time=0.3)

        # animation sum = 0.5+0.6+1.1+0.5+0.5+0.6+0.3 = 4.1s; measured
        # narration = 29.42s. All 5 rows stay on screen together for the
        # whole hold — not just the favorable CFTC row.
        self.wait(25.32)


# --------------------------------------------------------------------------- #
# B06 — FIX: before AND after identifySource()'s federalregister.gov branch,
# sitting together, the new dc:creator-based check highlighted. Uses
# clear_of_divider() as a second precaution, same as B04.
# --------------------------------------------------------------------------- #
class B06_BeforeAfterClassifier(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["ink"]
        cream = PALETTE["bg"]

        before_label = Text("BEFORE", color=PALETTE["crimson"], font_size=20, font=MONO, weight="BOLD")
        before_lines = [
            "if (link.includes('federalregister.gov')) {",
            "  if (link.includes('commodity-futures')",
            "      || title.includes('cftc')) {",
            "    return 'CFTC Regulations';",
            "  }",
            "  return 'Federal Register - Securities';",
            "}",
        ]
        # max_w 5.4 (not 5.9) and anchor -3.3 (not -3.55) — GATE B measured
        # the wider/further-left version's left edge at x=-6.5, past the
        # -6.3 safe wall; real measurement confirmed this combination clears
        # it (left edge ~-6.0) while still clearing the divider on the right.
        before_code = VGroup(*[
            fit(Text(l, color=cream, font_size=18, font=MONO), 5.4) for l in before_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.18)
        before_block = VGroup(before_label, before_code).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        before_block.move_to([-3.3, 0.1, 0])

        after_label = Text("AFTER", color=PALETTE["teal"], font_size=20, font=MONO, weight="BOLD")
        after_lines = [
            "if (link.includes('federalregister.gov')) {",
            "  const c = (creator || '').toLowerCase();",
            "  if (c.includes('commodity futures ...')",
            "      || link.includes('commodity-futures')) {",
            "    return 'CFTC Regulations';",
            "  }",
            "  return `Federal Register - ${creator}`;",
            "}",
        ]
        # font_size 16->18, buff 0.14->0.18 (both panels) — GATE V measured
        # the first draft right at the 55% floor (marginal fail); real
        # measurement confirmed this combination clears it with margin.
        after_code = VGroup(*[
            fit(Text(l, color=cream, font_size=18, font=MONO), 5.4) for l in after_lines
        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.18)
        after_footer = fit(Text(
            "(+ SEC / FINRA checks via dc:creator, then real-agency fallback)",
            color=PALETTE["sage"], font_size=13, font=MONO,
        ), 5.4)
        after_block = VGroup(after_label, after_code, after_footer).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        after_block.move_to([3.3, 0.1, 0])

        clear_of_divider(before_block, divider_x=0, side="left")
        clear_of_divider(after_block, divider_x=0, side="right")

        # divider sized to the two blocks' OWN measured vertical span, not a
        # guessed frame-spanning length — same measured-bounds discipline as
        # B04 above and the sibling reel's B03/B06.
        blocks_top = max(before_block.get_top()[1], after_block.get_top()[1]) + 0.25
        blocks_bottom = min(before_block.get_bottom()[1], after_block.get_bottom()[1]) - 0.25
        divider = Line([0, blocks_top, 0], [0, blocks_bottom, 0], color=PALETTE["slate"], stroke_width=2)

        self.play(Create(divider), run_time=0.25)
        self.play(
            FadeIn(before_block, shift=RIGHT * 0.1),
            FadeIn(after_block, shift=LEFT * 0.1),
            run_time=0.75,
        )

        # highlight 1 — reads dc:creator instead of guessing from link/title
        hl1 = box_around(after_code[1], PALETTE["gold"], buff=0.1)
        self.play(Create(hl1), run_time=0.45)

        # highlight 2 — the real-agency fallback, never a blanket "Securities"
        hl2 = box_around(after_code[6], PALETTE["gold"], buff=0.1)
        self.play(Create(hl2), run_time=0.45)

        # ONE shared caption below both blocks (not per-line floating tags —
        # an earlier draft's floating tags sat directly on the code line
        # immediately above the highlighted one, a real TEXT_ON_TEXT strike
        # GATE B caught; a single caption below the whole hold avoids that
        # entire class of collision).
        caption = fit(Text(
            "reads dc:creator instead of guessing", color=PALETTE["gold"],
            font_size=22, font=MONO, weight="BOLD",
        ), 11.0)
        caption.next_to(VGroup(before_block, after_block), DOWN, buff=0.45)
        self.play(Write(caption), run_time=0.5)

        # animation sum = 0.25+0.75+0.45+0.45+0.5 = 2.4s; measured
        # narration = 13.94s. Both full branches stay on screen together
        # for the whole hold.
        self.wait(11.54)


# --------------------------------------------------------------------------- #
# B07 — TAKEAWAY: statement card.
# --------------------------------------------------------------------------- #
class B07_Statement(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        line1 = fit(Text(
            "A safeguard that's never once tested",
            color=PALETTE["ink"], font_size=54,
        ), 11.8)
        line2 = fit(Text(
            "against real input isn't protecting anything.",
            color=PALETTE["crimson"], font_size=56,
        ), 11.8)
        line3 = fit(Text(
            "It's just code that looks like protection.",
            color=PALETTE["slate"], font_size=38,
        ), 11.0)
        VGroup(line1, line2, line3).arrange(DOWN, buff=1.4).move_to(ORIGIN)

        self.play(Write(line1), run_time=1.0)
        self.wait(0.4)
        self.play(Write(line2), run_time=1.0)
        self.wait(0.3)
        self.play(FadeIn(line3, shift=UP * 0.1), run_time=0.6)
        # animation sum = 3.3s; measured narration = 10.56s
        self.wait(7.26)


# --------------------------------------------------------------------------- #
# B08 — SIGN-OFF: @HumanitariansAI, in for Sai Pranavi Jeedigunta.
# --------------------------------------------------------------------------- #
class B08_BrandOutro(Scene):
    def construct(self):
        self.camera.background_color = PALETTE["bg"]

        handle = Text("@HumanitariansAI", color=PALETTE["slate"], font_size=90)
        accent = Line(LEFT * 3.0, RIGHT * 3.0, color=PALETTE["gold"], stroke_width=3)
        tagline = fit(Text(
            "in for Sai Pranavi Jeedigunta", color=PALETTE["ink"], font_size=44,
        ), 9.5)
        VGroup(handle, accent, tagline).arrange(DOWN, buff=2.3).move_to(ORIGIN)

        tagline_underline = Line(color=PALETTE["sage"], stroke_width=1)

        self.play(FadeIn(handle, shift=UP * 0.2), run_time=0.6)
        self.play(Create(accent), run_time=0.4)
        self.play(FadeIn(tagline), run_time=0.5)
        tagline_underline.put_start_and_end_on(
            tagline.get_corner(DL) + DOWN * 0.12, tagline.get_corner(DR) + DOWN * 0.12
        )
        self.play(Create(tagline_underline), run_time=0.3)
        # animation sum = 1.8s; measured narration = 6.26s
        self.wait(4.46)
